### ISSUE TITLE
Limit git commit to path specified by 'Limit to files' option

### ISSUE THREAD

**Issue by mortezadadgar** [NeogitOrg/neogit#1014]
**Is your feature request related to a problem? Please describe.**
emacs's magit limit git diff to file path specified by `Limit to files`

**Describe the solution you'd like**
just like magit it would be nice to have git commit limited by path
magit:
![image](https://github.com/NeogitOrg/neogit/assets/27911493/91ef599a-4fc7-4c67-a083-1c6a59e58736)

neogit:
![image](https://github.com/NeogitOrg/neogit/assets/27911493/24d017be-a5c3-465c-ba14-2dc07b939358)
as shown magit limit diff to .zprofile

**Describe alternatives you've considered**
nil

**Additional context**
nil

**Comment by CKolkey** [comment]
Ahh, ok, so the commit view is constrained by the file filter set in the log buffer. Smart. I'll definitely do that.
