### ISSUE TITLE
allow changing orders of commits in rebase

### ISSUE THREAD

**Issue by ktsujister** [NeogitOrg/neogit#1032]
**Is your feature request related to a problem? Please describe.**
Before #1013, rebase buffer was just normal buffer, and I was able to change orders of commits by editing the buffer.

Edit this:
```
pick 00001 change A
pick 00002 change B
```
to
```
pick 00002 change B
pick 00001 change A
```
But after #1013, when I try to do `dd` to delete a line in line of `change B`, `d` is considered as `drop` and comments out line containing `change B`. 

**Describe the solution you'd like**
Magit-mode in emacs has below keybinds.

```
# M-p      move the commit at point up
# M-n      move the commit at point down
```
So something similar, or maybe more vim like mapping for doing this would be great.

**Describe alternatives you've considered**
There's still workaround. Instead of `dd`, I can do `0D` to yank the line and `O` to open line and `P` to paste, but having keybinds to move commit around is much safer.

**Comment by CKolkey** [comment]
Hi! It's not 100% done, but it's well underway: https://github.com/NeogitOrg/neogit/pull/1033

**Comment by ktsujister** [comment]
This is great!

That keybinding also looks great, so I'll be doing that as well.
