### ISSUE TITLE
Stage operation fails

### ISSUE THREAD

**Issue by Yinameah** [NeogitOrg/neogit#1047]
### Description

When trying to Stage some hunk, I get an error :

```
git apply --cached:

    error: C:\Users\Cibrario\code\pygris\pygris/src/pygris/macros/rf_pll.py: does not exist in index

An error occured.
```
Given the mix of `/` and `\`, I can guess it's windows related ?

### Neovim version

NVIM v0.9.4
Build type: RelWithDebInfo
LuaJIT 2.1.1696883897

### Operating system and version

Windows 11

### Steps to reproduce

Open Neogit buffer, go over an unstaged hunk and type `s`.

### Expected behavior

the hunk should be staged

### Actual behavior

the error occur

### Minimal config

```Lua
-- NOTE: See the end of this file if you are reporting an issue, etc. Ignore all the "scary" functions up top, those are
-- used for setup and other operations.
local M = {}

local base_root_path = vim.fn.fnamemodify(debug.getinfo(1, "S").source:sub(2), ":p:h") .. "/.min"
function M.root(path)
  return base_root_path .. "/" .. (path or "")
end

function M.load_plugin(plugin_name, plugin_url)
  local package_root = M.root("plugins/")
  local install_destination = package_root .. plugin_name
  vim.opt.runtimepath:append(install_destination)

  if not vim.loop.fs_stat(package_root) then
    vim.fn.mkdir(package_root, "p")
  end

  if not vim.loop.fs_stat(install_destination) then
    print(string.format("> Downloading plugin '%s' to '%s'", plugin_name, install_destination))
    vim.fn.system({
      "git",
      "clone",
      "--depth=1",
      plugin_url,
      install_destination,
    })
    if vim.v.shell_error > 0 then
      error(string.format("> Failed to clone plugin: '%s' in '%s'!", plugin_name, install_destination),
        vim.log.levels.ERROR)
    end
  end
end

---@alias PluginName string The plugin name, will be used as part of the git clone destination
---@alias PluginUrl string The git url at which a plugin is located, can be a path. See https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols for details
---@alias MinPlugins table<PluginName, PluginUrl>

---Do the initial setup. Downloads plugins, ensures the minimal init does not pollute the filesystem by keeping
---everything self contained to the CWD of the minimal init file. Run prior to running tests, reproducing issues, etc.
---@param plugins? table<PluginName, PluginUrl>
function M.setup(plugins)
  vim.opt.packpath = {}                      -- Empty the package path so we use only the plugins specified
  vim.opt.runtimepath:append(M.root(".min")) -- Ensure the runtime detects the root min dir

  -- Install required plugins
  if plugins ~= nil then
    for plugin_name, plugin_url in pairs(plugins) do
      M.load_plugin(plugin_name, plugin_url)
    end
  end

  vim.env.XDG_CONFIG_HOME = M.root("xdg/config")
  vim.env.XDG_DATA_HOME = M.root("xdg/data")
  vim.env.XDG_STATE_HOME = M.root("xdg/state")
  vim.env.XDG_CACHE_HOME = M.root("xdg/cache")

  -- NOTE: Cleanup the xdg cache on exit so new runs of the minimal init doesn't share any previous state, e.g. shada
  vim.api.nvim_create_autocmd("VimLeave", {
    callback = function()
      vim.fn.system({
        "rm",
        "-r",
        "-f",
        M.root("xdg")
      })
    end
  })
end

-- NOTE: If you have additional plugins you need to install to reproduce your issue, include them in the plugins
-- table within the setup call below.
M.setup({
  plenary = "https://github.com/nvim-lua/plenary.nvim.git",
  telescope = "https://github.com/nvim-telescope/telescope.nvim",
  diffview = "https://github.com/sindrets/diffview.nvim",
  neogit = "https://github.com/NeogitOrg/neogit"
})
-- WARN: Do all plugin setup, test runs, reproductions, etc. AFTER calling setup with a list of plugins!
-- Basically, do all that stuff AFTER this line.
require("neogit").setup({}) -- For instance, setup Neogit
```

**Comment by CKolkey** [comment]
Yeah, looks windows related. Kinda odd, because I haven't messed with anything related to staging/paths in a bit. I'll take a peek and see if anything looks suspicious.

**Comment by Yinameah** [comment]
Sure. Let me know if you need me to test something.

(And thanks for the work, really cool plugin)

**Comment by juliekoubova** [comment]
I can repro this as well. It seems like the path to the git repo uses
Windows-style backslashes, but the in-repo part of the path uses UNIX forward
slashes (`c:\myrepo\foo/bar/baz`). Maybe just normalizing the path to a
single standard would fix it?

**Comment by CKolkey** [comment]
Yea, though it's not totally clear where the unix path separators are coming from. If anyone feels like spelunking:

- [The function that handles staging on the status buffer](https://github.com/NeogitOrg/neogit/blob/master/lua/neogit/status.lua#L846-L8910)
- [git.index.* - used to stage hunks](https://github.com/NeogitOrg/neogit/blob/master/lua/neogit/lib/git/index.lua)
- [git.status.stage() - used to stage files](https://github.com/NeogitOrg/neogit/blob/master/lua/neogit/lib/git/status.lua#L173-L175)
- [Parsing git status - this is where the filepaths probably come from](https://github.com/NeogitOrg/neogit/blob/master/lua/neogit/lib/git/status.lua#L86-L130)

Looks like it's using the `name` attribute for each item.

**Comment by wrightjjw** [comment]
> I can repro this as well. It seems like the path to the git repo uses Windows-style backslashes, but the in-repo part of the path uses UNIX forward slashes (`c:\myrepo\foo/bar/baz`). Maybe just normalizing the path to a single standard would fix it?

This usually isn't a problem - you can even try mixing dir separators in cmd and it will take. Possibly there could be an issue in how git interprets it, not super sure how that's translated under the hood.

I don't ever stage hunks, but I'd love to do a bit of spelunking. Unfortunately I'm away from a Windows machine until later next week.

**Comment by Yinameah** [comment]
So, apparently, it's not just about the Unix/windows path.

I quickly added `absolute_path = vim.fs.normalize(absolute_path)` after
https://github.com/NeogitOrg/neogit/blob/801143ee4db4121fc11a6468daae6680ba9fab51/lua/neogit/lib/git/status.lua#L13

The error look like : 
```
git apply --cached:

    error: C:/Users/Cibrario/code/pygris/pygris/src/pygris/devkit.py: does not exist in index
```

So apparently there is something else to it. Trying to dig a bit further, but I'm no lua expert ...

**Comment by CKolkey** [comment]
I'm curious if the command history is helpful here: try hitting `$` after that fails, then find the command and expand it with Tab.

**Comment by Yinameah** [comment]
![image](https://github.com/NeogitOrg/neogit/assets/7933289/be7fe6cb-2b91-42a7-88c8-520d3768208f)
This is all I get. Not sure if there is a way to have more details.

But I noticed that if I try to stage an untracked file, it seems to work just fine.  The issue only seems to appear with already tracked file ... Could not find any other interesting information yet ...

**Comment by MoffunW** [comment]
Hey all.
I faced the same problem.
Downgrading the version I found out that the problem occurs after commit d3e3160.
And one commit before (159c545) works fine. I think problem is here:
 `local path = Path:new(item.absolute_path):make_relative(git_root)`
 
 Can anyone fix this please?

**Comment by saggitar** [comment]
I fixed it by converting the output of the command that gets the inital repo directory to a proper windows style path (by default git returned  a path with unix style path seperators which confused `plenary.path`)
Seems to solve the issue for me.

https://github.com/NeogitOrg/neogit/pull/1164
