### ISSUE TITLE
LogView empty

### ISSUE THREAD

**Issue by v0d1ch** [NeogitOrg/neogit#1078]
### Description

Whatever command I do to try and see the logs I end up with just the empty buffer. This is probably something on my end since I don't see any people complaining about it but how would I debug what is the problem here?

### Neovim version

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

NixOS 23.05.4974.d2e4de209881 (Stoat)

### Steps to reproduce

Just hit `ll` or any of the commands to view the logs.

### Actual behavior

LogView buffer is always empty

### Minimal config

```Lua
local neogit = require('neogit')
            neogit.setup {
              integrations = {
                  diffview = true,
                  -- telescope = true
              },
              status = {
                  recent_commit_count = 100,
              },
            }
```

**Comment by v0d1ch** [comment]
Oh, as soon as I submitted a bug I found the problem. If you set some flag, in my example it was `-S` to search for occurences one time, this is never reset to empty flag on the next log list invocation. So each time you need to make sure that the flags you are using make sense or you should reset them. I am not sure if I should close this or it would be better to reset the flags each time you want to look at the logs.

**Comment by CKolkey** [comment]
Yeah, I don't know if those are useful to remember between log invocations. You can ignore it manually via config, but maybe it should be ignored by default?

**Comment by v0d1ch** [comment]
Usually I would expect each invocation of a command to start from scratch since I change repos often grepping for stuff but it's up to you. Now that I got bitten by this problem this will not happen again to me but perhaps somebody falls into this pit in the future.

**Comment by CKolkey** [comment]
You can also enable "per project settings", so state is scoped to a repository. But its a reasonable point that filtering shouldn't persist.
