### ISSUE TITLE
Branch deletion failed when branch name contains forward slash

### ISSUE THREAD

**Issue by rami3l** [NeogitOrg/neogit#1086]
### Description

Similar to https://github.com/NeogitOrg/neogit/issues/578. When deleting a local branch, if the name of that branch contains a `/`, then Neogit somehow thinks it's a remote branch and issues the wrong git command.

It seems that `parse_remote_branch_name()` makes no distinction between remote branch names and local branch names with `/`, so probably all functionalities that depend on this function are influenced, not just branch deletion:
https://github.com/NeogitOrg/neogit/blob/4825a0a7263f73846424cab969c56f1c211b052f/lua/neogit/popups/branch/actions.lua#L13-L23

### Neovim version

NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1700008891

### Operating system and version

macOS 14.0

### Steps to reproduce

1. In any git repo, create a new branch named `test/foo`.
2. In Neogit:
  a. Press `b` to enter the "branches" menu.
  b. Press `D` to select a branch to delete.
  c. Choose `test/foo`.
  

### Expected behavior

The branch `test/foo` gets correctly deleted.

### Actual behavior

Neogit shows the following:

```console
Delete remote branch 'test/foo'?
(Y)es, [N]o: Y
... Command `git push test --delete foo` failed!
```

### Minimal config

```Lua
{
    'NeogitOrg/neogit', dependencies = 'nvim-lua/plenary.nvim',
    cmd = { 'Neogit' },
    config = function()
      require('neogit').setup({
        signs = {
          -- { CLOSED, OPENED }
          -- section = { '▶', '▼' },
          -- item = { '▶', '▼' },
          section = { '', '' },
          item = { '', '' },
          hunk = { '', '' },
        },
        integrations = {
          diffview = true,
        },
      })
    end,
  },
```

**Comment by CKolkey** [comment]
Thanks for the report! Pretty simple fix :)
