### ISSUE TITLE
Stash unstaged changes

### ISSUE THREAD

**Issue by hkupty** [NeogitOrg/neogit#11]
It would be nice if I could stash unstaged changes the same way I can stage them.

**Comment by TimUntersberger** [comment]
In magit the user has to stage the files he wants to stash and then open the stash popup and stash the index. 

Would this be acceptable for you?

**Comment by hkupty** [comment]
Well, I guess so. I mean, it depends on how much do you want to stick to magit or if you're willing to drift apart and make it different (to better suit neovim's workflow, for example). :)

**Comment by hkupty** [comment]
I might be wrong but it doesn't seem like the PR is related to this issue. To be fair, I'm not even sure the issue is valid anymore since it's been a while since I tested stashing.
