### ISSUE TITLE
Branch deletion failed: no branch to choose from

### ISSUE THREAD

**Issue by rami3l** [NeogitOrg/neogit#1106]
### Description

When trying out the fix for https://github.com/NeogitOrg/neogit/issues/1086, I'm surprised to find out that the menu allowing me to select a branch to delete won't show up anymore.

### Neovim version

NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1703358377

### Operating system and version

macOS 14.2.1 23C71 arm64

### Steps to reproduce

In Neogit:
a. Press b to enter the "branches" menu.
b. Press D to select a branch to delete.

### Expected behavior

A menu should show up letting me to choose which branch to delete.

### Actual behavior

Nothing happens. No branch gets deleted, I'm back to Neogit's main (dispatch) page, Neovim is (weirdly) in insert mode.

### Minimal config

```Lua
{
    'NeogitOrg/neogit', dependencies = 'nvim-lua/plenary.nvim',
    cmd = { 'Neogit' },
    config = function()
      require('neogit').setup({
        signs = {
          -- { CLOSED, OPENED }
          -- section = { '▶', '▼' },
          -- item = { '▶', '▼' },
          section = { '', '' },
          item = { '', '' },
          hunk = { '', '' },
        },
        integrations = {
          diffview = true,
        },
      })
    end,
  },
```

**Comment by CKolkey** [comment]
Huh, odd. Works fine for me. Could you remove any existing log file and launch neovim thusly:
```
rm ~/.cache/nvim/neogit.log
NEOGIT_LOG_LEVEL="trace" NEOGIT_LOG_FILE="true" NEOGIT_DEBUG=true nvim
```
Then open neogit and try to delete a branch. Close neogit, and copy whatever got logged in there.

**Comment by rami3l** [comment]
@CKolkey I looked into this issue today and found out that I cannot reproduce this error on another machine of mine, so it looks like a local state problem. Sorry for the noise!

**Comment by CKolkey** [comment]
No worries 👍
