### ISSUE TITLE
Tracking issue for _Rebase to reword a commit_

### ISSUE THREAD

**Issue by gollth** [NeogitOrg/neogit#1114]
I (would like to) use the `r` > `w` (Rebase to reword a commit) feature quite regularly, so here is a tracking issue for you to get insight if other people are in need of it. It's probably not the highest priority on your list, but from the surface it also doesn't seem to hard. If you give me a pointer where to start, I can also have a look at implementing this

![neogit-reword-a-commit](https://github.com/NeogitOrg/neogit/assets/31999281/f5c186a6-fa43-4910-a006-851324712063)

**Comment by CKolkey** [comment]
Hey! Yea, it's on the TODO ...pile.

Anyways, you'll pass the function here: https://github.com/NeogitOrg/neogit/blob/17750f58b0131d5c37654cd61bc6f80c9bba2e80/lua/neogit/popups/rebase/init.lua#L44

And define it here: https://github.com/NeogitOrg/neogit/blob/17750f58b0131d5c37654cd61bc6f80c9bba2e80/lua/neogit/popups/rebase/actions.lua#L1

It's (sometimes) handy to take a peek at the Magit implementation: https://github.com/magit/magit/blob/5c652a086e289e5a257745baa9eb7d98ee734516/lisp/magit-sequence.el#L783-L789

Lemme know if you have any other questions :)
