### ISSUE TITLE
Failing to commit changes

### ISSUE THREAD

**Issue by johannesrld** [NeogitOrg/neogit#1124]
### Description

When attempting to commit changes, instead of showing the commit message popup neogit instead shows a bunch of errors (things like `fatal: No names found, cannot describe anything` and `NVIM server address not set`)

### Neovim version

NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1693350652
Compilation: /usr/bin/cc  -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=auto -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/usr/include/luajit-5_1-2.1 -I/usr/include -I/usr/include/lua5.1 -I/home/abuild/rpmbuild/BUILD/neovim-0.9.5/build/src/nvim/auto -I/home/abuild/rpmbuild/BUILD/neovim-0.9.5/build/include -I/home/abuild/rpmbuild/BUILD/neovim-0.9.5/build/cmake.config -I/home/abuild/rpmbuild/BUILD/neovim-0.9.5/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Operating system and version

openSUSE Tumbleweed WSL (this also happens with Ubuntu on WSL)

### Steps to reproduce

1. load the minimal config provided
2. open `:Neogit`
3. stage your changes
4. attempt to commit your changes with `c` + `c`

### Expected behavior

staged changes are successfully committed

### Actual behavior

Instead I get this error message
![Screenshot 2024-01-11 223202](https://github.com/NeogitOrg/neogit/assets/71744831/9080a61f-0c04-4fc9-847d-1b67dfa6eca2)

note that this happens with every git repo I clone, no matter the directory or operating system

### Minimal config

```Lua
-- NOTE: See the end of this file if you are reporting an issue, etc. Ignore all the "scary" functions up top, those are
-- used for setup and other operations.
local M = {}

local base_root_path = vim.fn.fnamemodify(debug.getinfo(1, "S").source:sub(2), ":p:h") .. "/.min"
function M.root(path)
  return base_root_path .. "/" .. (path or "")
end

function M.load_plugin(plugin_name, plugin_url)
  local package_root = M.root("plugins/")
  local install_destination = package_root .. plugin_name
  vim.opt.runtimepath:append(install_destination)

  if not vim.loop.fs_stat(package_root) then
    vim.fn.mkdir(package_root, "p")
  end

  if not vim.loop.fs_stat(install_destination) then
    print(string.format("> Downloading plugin '%s' to '%s'", plugin_name, install_destination))
    vim.fn.system({
      "git",
      "clone",
      "--depth=1",
      plugin_url,
      install_destination,
    })
    if vim.v.shell_error > 0 then
      error(string.format("> Failed to clone plugin: '%s' in '%s'!", plugin_name, install_destination),
        vim.log.levels.ERROR)
    end
  end
end

---@alias PluginName string The plugin name, will be used as part of the git clone destination
---@alias PluginUrl string The git url at which a plugin is located, can be a path. See https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols for details
---@alias MinPlugins table<PluginName, PluginUrl>

---Do the initial setup. Downloads plugins, ensures the minimal init does not pollute the filesystem by keeping
---everything self contained to the CWD of the minimal init file. Run prior to running tests, reproducing issues, etc.
---@param plugins? table<PluginName, PluginUrl>
function M.setup(plugins)
  vim.opt.packpath = {}                      -- Empty the package path so we use only the plugins specified
  vim.opt.runtimepath:append(M.root(".min")) -- Ensure the runtime detects the root min dir

  -- Install required plugins
  if plugins ~= nil then
    for plugin_name, plugin_url in pairs(plugins) do
      M.load_plugin(plugin_name, plugin_url)
    end
  end

  vim.env.XDG_CONFIG_HOME = M.root("xdg/config")
  vim.env.XDG_DATA_HOME = M.root("xdg/data")
  vim.env.XDG_STATE_HOME = M.root("xdg/state")
  vim.env.XDG_CACHE_HOME = M.root("xdg/cache")

  -- NOTE: Cleanup the xdg cache on exit so new runs of the minimal init doesn't share any previous state, e.g. shada
  vim.api.nvim_create_autocmd("VimLeave", {
    callback = function()
      vim.fn.system({
        "rm",
        "-r",
        "-f",
        M.root("xdg")
      })
    end
  })
end

-- NOTE: If you have additional plugins you need to install to reproduce your issue, include them in the plugins
-- table within the setup call below.
M.setup({
  plenary = "https://github.com/nvim-lua/plenary.nvim.git",
  telescope = "https://github.com/nvim-telescope/telescope.nvim",
  diffview = "https://github.com/sindrets/diffview.nvim",
  neogit = "https://github.com/NeogitOrg/neogit"
})
-- WARN: Do all plugin setup, test runs, reproductions, etc. AFTER calling setup with a list of plugins!
-- Basically, do all that stuff AFTER this line.
require("neogit").setup({}) -- For instance, setup Neogit
```

**Comment by CFiggers** [comment]
I am seeing this same error when trying to make commits. Any leads on a fix?

**Comment by CKolkey** [comment]
I don't have windows, much less WSL, so I can't do much about this. If you want, you could use git bisect to try to find the changeset that broke things.

**Comment by CKolkey** [comment]
Like I said, I don't have windows/WSL, so without a bisection to point _somewhere_ there's not much I can do. I cannot replicate the issue, as I do not have windows or WSL.

**Comment by megalithic** [comment]
I'm seeing this with macos, too.

git version 2.43.0 from homebrew
nvim at HEAD

currently working my way back through commit history/quazi bisecting to find the breaking commit.

**Comment by CKolkey** [comment]
Yeah, no shade at Mr. Pope - he's the GOAT for a reason.

Very confused that you're having issues on macos... because I do not have issues on macos. If you can help reproduce this, or point to a commit that broke things, I'd really appreciate it :)

**Comment by BKDevelop** [comment]
Hey,
I encountered the same issue on WSL and decided to look into this a little.
I used htop to figure out the PID of the spawned git subprocess when commiting changes.

I used `cat /proc/<PID>/environ` to take a look at the subprocesses environment and - as you already said - the NVIM env var does not appear to be set.
Can someone confirm that on native linux or macos this env var is set and readable with environ? If that's the case, I feel like an issue should be raised in neovim base repo.

**Comment by CKolkey** [comment]
Thanks for looking into this. I agree, if that ENV var isn't set, it's a neovim issue, as it's the expected behaviour of a shell opened via nvim. I can confirm on macos that `NVIM=/var/folders/rx/m34cttj953q76nbyrfcw04j00000gn/T/nvim.cameron/Adn7En/nvim.67288.0` is set for the child git process as expected.

I haven't had much time to look into it, but I fully plan to migrate our process/job code to use that new `vim.system` API sooner than later :)

**Comment by BKDevelop** [comment]
@CKolkey FYI I opened an issue with nvim and will keep you updated.

Yes I was thinking about bisecting neovim, I just have to free up some time to do so ^^'

**Comment by sQVe** [comment]
I'm getting a bunch of these errors on Linux too. I'm getting them consistently when I'm being prompted to sign things with GPG. Most of the time it still works though.
![image](https://github.com/NeogitOrg/neogit/assets/2284724/46728546-fa10-47c3-8133-896de2739604)

**Comment by theherk** [comment]
Same here. Tons of these messages on MacOS, but it doesn't stop anything from working for me. Just a bunch of messages.

**Comment by BKDevelop** [comment]
I think we might be looking at two seperate issues here. As @CKolkey described if your repo has no tags you will see the `fatal: No names found` warning.

The issue OP described on wsl, which leads to neogit freezing/crashing always happens on git commands that try to open $EDITOR to get user input, like `git commit` or `git rebase --interactive`.

Maybe we could open a seperate issue for the warning @sQVe and @theherk described. I don't think we should print an error to the user if the repo does not contain tags.

**Comment by CKolkey** [comment]
Couldn't have put it any better - the `fatal: No names found` is just checking for tags. It looks scary (says fatal) but doesn't actually do anything. The reason it looks like you get them when you have to sign something is that the console opens up if a command is taking a while, and that check (for tags) is part of refreshing repo state, so it's run a lot. Totally harmless. The actual issue there is that it keeps asking for your password. 

Anyways, feel free to open a new issue and/or investigate it :)

Now, WSL....

**Comment by BKDevelop** [comment]
Just a heads up, @Ramilito figured out a workaround for WSL. It seems that using systemd on WSL leads to this behavior.
Setting this in `.wslconfig`

```
[boot]
systemd=false
```

will make the error disappear.

Now we have to figure out if this is actually is a nvim issue or if it should be raised with MS/WSL. Either way, I think this issue could be closed.

**Comment by CKolkey** [comment]
Thanks @BKDevelop - seems pretty clear this is either upstream, or up-upstream. I appreciate your help troubleshooting this :)

**Comment by zoeesilcock** [comment]
I ran into this issue under WSL but disabling systemd didn't help in my case. The workaround that worked for me was the second one listed in this comment, fixing permissions of the `/run/user/1000` directory: https://github.com/neovim/neovim/issues/27962#issuecomment-2024018548. Still unrelated to Neogit, just sharing to save some time for anyone that runs into this in the future.

**Comment by andreyugolnik** [comment]
Hello, I recently started using Neogit and also encountered a similar problem.
My work environment:
- macOS 14.4.1 (23E224)
- neovim v0.9.5
- git 2.39.3 (Apple Git-146)
<img width="1512" alt="Screenshot 2024-05-11 at 03 23 29" src="https://github.com/NeogitOrg/neogit/assets/1927370/2076d5f6-7108-48b2-afd2-1d8df6d3cd9e">

**Comment by CFiggers** [comment]
> I ran into this issue under WSL but disabling systemd didn't help in my case. The workaround that worked for me was the second one listed in this comment, fixing permissions of the `/run/user/1000` directory: https://github.com/neovim/neovim/issues/27962#issuecomment-2024018548. Still unrelated to Neogit, just sharing to save some time for anyone that runs into this in the future.
> 

This helped me—I investigated and found that there was no `/run/user/1000/` directory on my system. I created one and then did the chmod command at that link and that cleared up my issue.
