### ISSUE TITLE
Renamed file cannot be shown properly

### ISSUE THREAD

**Issue by rami3l** [NeogitOrg/neogit#1157]
### Description

When a file is renamed (similar to #715), the `Renamed` session in Neogit seems broken.

### Neovim version

NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377

### Operating system and version

macOS 14.2.1 23C71 arm64

### Steps to reproduce

I'm trying this on my neovim config repo, but it seems to me that this can be reproduced regardless of the actual repo.

1. Rename any file (in this case, `lsp/config/rust_analyzer.lua`) and stage. This will lead to a `git status` like the following:

```console
> git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        renamed:    lsp/config/rust_analyzer.lua -> lsp/config/rust-analyzer.lua
```

2. Launch magit.

### Expected behavior

The `Renamed` line and the diff are showing properly.
Pressing enter on the `Renamed` line will lead to the just-renamed `lsp/config/rust-analyzer.lua`.

### Actual behavior

 In my case Neogit gives:

```console
v Staged changes (1)
> Renamed        a -> lsp/config/rust-analyzer.lu

> Recent commits (10)
```

In this state not only is it impossible to see the diff, but pressing enter on the `Renamed` line will lead to an inexistent `lsp/config/rust-analyzer.lu` file.

### Minimal config

```Lua
{
  "NeogitOrg/neogit",
  opts = {
    signs = {
      item = { ">", "v" },
      section = { ">", "v" },
    },
  },
}
```

**Comment by rami3l** [comment]
I think I may have found out the problem.
https://git-scm.com/docs/git-status says:

```
Renamed or copied entries have the following format:

2 <XY> <sub> <mH> <mI> <mW> <hH> <hI> <X><score> <path><sep><origPath>
...
<sep>       When the `-z` option is used, the 2 pathnames are separated
	    with a NUL (ASCII 0x00) byte; otherwise, a tab (ASCII 0x09)
	    byte separates them.
```

**Comment by rami3l** [comment]
Aha! This is a combination of 2 separate issues so fixing only one of them (with #1165) won't work.

**Comment by rami3l** [comment]
It's actually fixed in https://github.com/NeogitOrg/neogit/pull/1167 rather than #1165, at least for a while...

**Comment by rami3l** [comment]
> Just for the record, the same issue keeps happening with the latest version ( [c0b1d4d](https://github.com/NeogitOrg/neogit/commit/c0b1d4dfc8ba6371857868ca7c4d33954cf002fd) ), and Neovim version 0.9.5
> 
> ![2024-04-02_15-43-56](https://private-user-images.githubusercontent.com/11479916/318925285-d64f7c96-3943-4dbc-bd64-b0ded014a5cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNTA1NjcsIm5iZiI6MTcxMjE1MDI2NywicGF0aCI6Ii8xMTQ3OTkxNi8zMTg5MjUyODUtZDY0ZjdjOTYtMzk0My00ZGJjLWJkNjQtYjBkZWQwMTRhNWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDEzMTc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNzIzZjQ5YjA1NzdmOTRiNDYxYjFlMDFjMjBjN2JiYTgzYWFkZTg4MWQzMGZkNjJhODAwYWJkZDZiNzRiZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q1oxuIHYZjac2KvQyU7sWyX44hi5SylAiIhe1SdU15I)

I'm on c0b1d4d + nvim 0.9 as well and it seems that I can't reproduce this issue 👀

**Comment by javoscript** [comment]
@rami3l The issue seems to happen when there are staged changes in renamed file, and unstaged changes to it's content.

Steps to reproduce, in an example repo without unstaged changes:

```bash
echo "example" > test.txt

git add -A && git commit -m "..."

mv test.txt test_2.txt

git add -A

echo "change" >> test_2.txt
```

Open neovim and neogit status buffer and the bug happens.

![2024-04-03_11-43-36](https://github.com/NeogitOrg/neogit/assets/11479916/2390c89b-7a5d-4836-80e4-fe6f4fed2430)

**Comment by rami3l** [comment]
Given that maybe we should reopen this issue. @CKolkey what do you think?
