### ISSUE TITLE
Logo for Neogit

### ISSUE THREAD

**Issue by azzamsa** [NeogitOrg/neogit#1168]
**Is your feature request related to a problem? Please describe.**
Let's make a logo for Neogit!

**Describe the solution you'd like**
I can't draw, but I will ask someone on [fiverr](https://www.fiverr.com/).

**Describe alternatives you've considered**
N/A

**Additional context**

*Why?*
Having a logo for the project gives it a sense of warmth and character.

*How*
Would you happen to have any more considerations for the logo?

I envision a logo akin to Magit, with a distinctive 'N' for Neovim.

- What primary color scheme do you envision?
- What thematic elements should be incorporated?

(Me): I'm envisioning a mystical vibe for the app.

*Reference*

1)

<div align="center">
<img src='https://github.com/NeogitOrg/neogit/assets/17734314/316930cb-b034-410a-acbb-a391fdf487c9' width=300px />
</div>

**Comment by CKolkey** [comment]
Love the idea :D

Here are the colors I'm partial to:
<img width="83" alt="Screenshot 2024-02-06 at 13 58 53" src="https://github.com/NeogitOrg/neogit/assets/7228095/ee93e283-1bfb-4cc5-84e5-f2238dcbe7bf">
<img width="138" alt="Screenshot 2024-02-06 at 14 00 26" src="https://github.com/NeogitOrg/neogit/assets/7228095/9129814b-a689-4881-bb60-4f221e0d65cc">
<img width="167" alt="Screenshot 2024-02-06 at 14 00 45" src="https://github.com/NeogitOrg/neogit/assets/7228095/787b721f-8286-4f5b-84fc-f12d36025b70">

For elements.. Some kind of graph (like a git-log graph kinda thing) might be cool, but I'm pretty open to ideas here. Maybe that wouldn't play well. I don't have anything as campy/charming as a magicians hat in mind, haha

**Comment by CKolkey** [comment]
I think if you have an idea then by all means run with it :)

**Comment by kolja** [comment]
Food for thought:
![neogit_logo](https://github.com/NeogitOrg/neogit/assets/28293/a2abcd00-3de9-4232-9858-5741be3baf6f)
I prefer the left version, because the distinctive color from the neovim logo is more pronounced and the characteristic node-structure from the git logo isn't obscured.

**Comment by CKolkey** [comment]
Honestly? Love it. Have you got png's or psd files? Something with transparency :)

**Comment by kolja** [comment]
Here is a png in higher resolution with transparency. It's more of a sketch at this point, but can make a vector version (e.g. svg). 
![neogit_logo](https://github.com/NeogitOrg/neogit/assets/28293/1e964e47-77ca-409f-bcb7-27214c1b8cb3)

**Comment by CKolkey** [comment]
Svg would be perfect 😄

**Comment by kolja** [comment]
Here is an SVG:
![neogit_logo](https://github.com/NeogitOrg/neogit/assets/28293/21423d01-6d46-4ebd-8b3e-c549273a18d9)

**Comment by CKolkey** [comment]
Really outstanding work - thanks for the art, Kolja

**Comment by kolja** [comment]
Wow, thank you! Perhaps you can sleep over it and get some feedback: I'm open to making changes to it.

**Comment by CKolkey** [comment]
Thank you, man. I wound up going with the hand drawn one - I really liked the little details it had, the highlights, shading. It feels a bit more friendly than the svg since its less perfect. I didn't realize I'd feel that way until I had the two side by side.

This is one of those designs that seems so obvious in hindsight. I really love it 🙏

**Comment by kolja** [comment]
Here is an improved SVG version of the logo. It now has those highlights, that were missing when compared to the hand drawn one. It is a "preview" as png (for some reason the colors get distorted when I use Affinity Designer to export ot SVG...). 
![neogit_logo_v2](https://github.com/NeogitOrg/neogit/assets/28293/295c0a09-4c1a-4e42-a8f1-b3ab7beba603)
If you choose to stick with the hand drawn version, I'll fix some kinks in there too.

**Comment by kolja** [comment]
...the SVG file to the png above:
![neogit_logo_v2](https://github.com/NeogitOrg/neogit/assets/28293/daa979b8-c16f-4b14-abcc-2cb2ae883c7a)

**Comment by CKolkey** [comment]
I really like the blur on that SVG version - gives the orange git logo a frosted-glass effect. The only thing that stands out is the bright orange highlight on the bottom tip (left side). Could that fade into the corner a bit more gradually as it rounds?
<img width="210" alt="Screenshot 2024-03-21 at 21 02 39" src="https://github.com/NeogitOrg/neogit/assets/7228095/f2b7bcdb-439b-44c3-a796-cca0d75229cc">

And the tip of this corner looks slightly off.
<img width="105" alt="Screenshot 2024-03-21 at 21 02 30" src="https://github.com/NeogitOrg/neogit/assets/7228095/e70acb91-3ff8-47d5-bef5-8cd4fda5b382">


Other than that, I think this version is definitely the right direction to go :)

**Comment by kolja** [comment]
fixed:
![neogit_logo](https://github.com/NeogitOrg/neogit/assets/28293/1d36044f-dbfb-49f0-908d-53530c77c0df)
I also tweaked the highlights on the bevel in some places and made parts of the "ribbon" slightly transparent.

**Comment by CKolkey** [comment]
I'm happy if you're happy. This is fantastic :D

**Comment by azzamsa** [comment]
@kolja awesome! 🎉

**Comment by azzamsa** [comment]
@CKolkey would you like to change the org profile picture with this one too?

**Comment by CKolkey** [comment]
Good call, yeah

**Comment by krmbzds** [comment]
I just wanted to drop by and say.. What the hell — this logo **absolutely kicks ass!** It has no business looking this *slick*. You've somehow woven two legends into one icon. This isn’t just a logo — it's a timeless mark of greatness. Amazing work @kolja! 🙂
