### ISSUE TITLE
`w` opens up worktree instead of jumping a word

### ISSUE THREAD

**Issue by mangelozzi** [NeogitOrg/neogit#1182]
### Description

When viewing the status, and looking at the diffs, say I wish to copy a variable name, when moving one word at a time, when I press `w` the worktree popup appears.
There is no mention in the Readme configuration <https://github.com/NeogitOrg/neogit#configuration> about how to disable this annoying hotkey. 

I love Neogit, but every month one has to disable a new hot key that is a standard vim motion.
Can you not make features opt in instead of one constantly having to check what next to disable to get one's vim motions back. That is the power of vim, is that one know how to jump around... until the rug is pulled out from under your feet again.

### Neovim version

NVIM v0.10.0-dev-1224+gdfa8b582a
Build type: RelWithDebInfo
LuaJIT 2.1.1695653777
Run "nvim -V1 -v" for more info

### Operating system and version

Ubuntu 22.04

### Steps to reproduce

1. Open up the status popup
2. Open a hunk
3. Press `w` to move one word

### Expected behavior

`w` to move one word

### Actual behavior

worktree popup shows

### Minimal config

```Lua
N/A
```

**Comment by CKolkey** [comment]
You can remap the worktree popup to a different key if you prefer, via the setup. There's details on that in the readme :)

**Comment by mangelozzi** [comment]
Thanks for the answer, but the phrase "worktree" does not appear in the readme.md, I already checked it before opening the issue.

**Comment by mangelozzi** [comment]
PS I also tried mapping `w` to false before opening this issue too, and that also didnt work.

**Comment by CKolkey** [comment]
> Thanks for the answer, but the phrase "worktree" does not appear in the readme.md, I already checked it before opening the issue.

Good catch - I forgot to add it along with the popup. It's the most recent one. I've added it now.

If mapping something to false didn't work, _that_ sounds like a bug.
