### ISSUE TITLE
Unusable diff highlight on NeogitStatus with the new default light colorscheme (nvim-0.10.0-nightly)

### ISSUE THREAD

**Issue by suliatis** [NeogitOrg/neogit#1192]
### Description

Using the default light colorscheme the diffview on the NeogitStatus view has a black or almost black bacground that makes the text in the diff context unreadable.

<img width="1311" alt="Screenshot 2024-03-06 at 8 25 26 AM" src="https://github.com/NeogitOrg/neogit/assets/6475233/68912ce2-eccf-4160-b236-8f2c84169873">

### Neovim version

NVIM v0.10.0-dev-2465+ga7788c2e2
Build type: RelWithDebInfo
LuaJIT 2.1.1707061634

### Operating system and version

macOS 14.2.1 but probably doesn't matter

### Steps to reproduce

1. remove/comment the colorscheme setting
2. set the background option to light
3. open NeogitStatus
4. toggle the diffview for any unstaged/staged file

### Expected behavior

The diff panel has a light background too.

### Actual behavior

---

### Minimal config

```Lua
-- comment or remove vim.cmd.colorscheme '???'
vim.opt.background = light
```

**Comment by CKolkey** [comment]
<img width="556" alt="Screenshot 2024-03-14 at 21 25 57" src="https://github.com/NeogitOrg/neogit/assets/7228095/f99b4d77-6409-47f7-8364-9c520c6792f3">

^^ Thats how it looks for me with nvim nightly with the default colorscheme. Are you doing anything else that might be confounding things?

**Comment by suliatis** [comment]
Meanwhile I started to use a custom colorscheme and what I realised that the colorscheme plugin must be loaded before neogit otherwise the same thing happens. I think maybe because I never set the default theme explicitly it was loaded after neogit too.

**Comment by suliatis** [comment]
Also I found this [issue](https://github.com/echasnovski/mini.nvim/issues/388) that might be related.

**Comment by CKolkey** [comment]
Makes sense - we derive colors from your colorscheme in order to make it look good without requiring every colorscheme add a bunch of highlight groups, but that does mean that if neogit is loaded _before_ your colorscheme, it might look off. I could probably add an autocmd to help with this, though.

**Comment by CKolkey** [comment]
Oh, shoot, I already added an autocmd for `ColorScheme` events. Huh. It _seems_ to work for me.

**Comment by suliatis** [comment]
I took another look on this and still not works with the default theme until I explicitly declare `vim.cmd.colorscheme 'default'`. Then I realised that it is because I load plugins eagerly. I tried to load neogit lazily with `MiniDeps.later` and it works as expected with the default theme.

So at the end it is the same for me. I need to make sure that the neogit plugin is loaded and set after the colorscheme. I have no idea why the colorscheme autocmd is not working for me.

**Comment by gegoune** [comment]
What's quite interesting here is that Neovim loads plugin before setting default colorscheme.

**Comment by andradei** [comment]
@suliatis thanks for finding that out.
Lazy loading it like this solved my problem:
```lua
 -- Lazy plugin manager
 {
    "NeogitOrg/neogit",
    cmd = "Neogit", ------------ Only load Neogit when I absolutely need to
    -- ...
  },

```

**Comment by CKolkey** [comment]
> @suliatis thanks for finding that out.
> 
> Lazy loading it like this solved my problem:
> 
> ```lua
> 
>  -- Lazy plugin manager
> 
>  {
> 
>     "NeogitOrg/neogit",
> 
>     cmd = "Neogit", ------------ Only load Neogit when I absolutely need to
> 
>     -- ...
> 
>   },
> 
> 
> 
> ```

For what its worth, this is my setup too :)
