### ISSUE TITLE
Neogit window fold carets/signs disappear when window loses focus

### ISSUE THREAD

**Issue by fnune** [NeogitOrg/neogit#1194]
### Description

When a window no longer has the cursor in it, the column with the `>` and `v` carets disappears. This moves the entire text of Neogit to the side, and cause it to move again once Neogit regains focus.

[Screencast from 2024-03-11 01-24-28.webm](https://github.com/NeogitOrg/neogit/assets/16181067/13db64bc-468d-4793-9e3b-cac38adf62e3)

Note that even though my diff shows a special config for signs, this happens with a default config as well.

### Neovim version

NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1693350652

### Operating system and version

Linux feanor 6.7.9 #1-NixOS SMP PREEMPT_DYNAMIC Wed Mar  6 14:54:01 UTC 2024 x86_64 GNU/Linux

### Steps to reproduce

1. Open Neogit
2. Move to another window
3. See the carets disappear

### Expected behavior

Carets don't disappear

### Actual behavior

Carets disappear & the layout moves

### Minimal config

```Lua
-
```

**Comment by fnune** [comment]
Closing: can't reproduce with the minimal config. Will investigate more.

**Comment by fnune** [comment]
One suspicious thing is that Neogit sets `signcolumn=auto` but my Neovim config sets it to `yes`...

**Comment by fnune** [comment]
d'oh! It was my own plugin causing this. Sorry about that. https://github.com/fnune/recall.nvim/issues/7

**Comment by CKolkey** [comment]
Haha, classic. Glad you sorted it out :)
