### ISSUE TITLE
Papercut: pressing x (discard) on stash does nothing, should tell user to use Zd (stash, drop) instead

### ISSUE THREAD

**Issue by LunarLambda** [NeogitOrg/neogit#1198]
This is something only first-time users like me are going to run into. Pressing x on a stash prompts me whether I want to drop \<stash name\>, confirming does nothing. Need to use Zd instead.

Don't know whether it would be better to allow x on stash to work like Zd, or whether it should print a message ('To drop stash, use Zd').

Also I noticed that using x on other random lines in the neogit buffer asks me if I want to 'discard nil?'. That should probably be checked against too.

**Comment by CKolkey** [comment]
Yeah, I've got a big rewrite of the status buffer that should be done very very soon, that'll do the right thing for stashes, and a lot more goodies. Because I totally agree, it's confusing.

**Comment by LunarLambda** [comment]
Looking forward to it! Used Neogit for a little bit today and it seems really nice, first time switching to an in-editor git integration. ^^

**Comment by CKolkey** [comment]
Try out the `nightly` branch if you want to use this before 0.10 is released :)
