### ISSUE TITLE
Ability to use normal mode when rewording a commit

### ISSUE THREAD

**Issue by stevenxxiu** [NeogitOrg/neogit#1241]
**Is your feature request related to a problem? Please describe.**

I can't enter normal mode when rewording commits. Hitting `Esc` exits the operation. This makes text editing rather challenging.

**Describe the solution you'd like**

I see <https://github.com/NeogitOrg/neogit/blob/c0b1d4dfc8ba6371857868ca7c4d33954cf002fd/lua/neogit/lib/input.lua#L37> using `vim.fn.input()`. Perhaps the new `vim.ui.input()` can be used instead? This allows the use of say *dressing*.

**Describe alternatives you've considered**

Using arrow keys isn't ideal.

**Additional context**

N/A

**Comment by CKolkey** [comment]
You will be very happy to know that on the `nightly` branch, the `rebase-reword` experience features a proper buffer :)

<img width="1722" alt="Screenshot 2024-04-07 at 21 19 10" src="https://github.com/NeogitOrg/neogit/assets/7228095/b005bd4b-2db9-49a4-85cf-55e18ac42070">
