### ISSUE TITLE
Opening vertical splits from status buffer messes up statuscolumn

### ISSUE THREAD

**Issue by igorlfs** [NeogitOrg/neogit#1254]
### Description

Hey!

Using the nightly branch, when opening a vertical split, Neogit overrides the 'statuscolumn' option if the file is first opened through Neogit. The real dealbreaker is that even if I close the bufffer with `:bd` and try to reopen it, I still get the overridden 'statuscolumn'.

My default 'statuscolumn', configured via statuscol.nvim:
![image](https://github.com/NeogitOrg/neogit/assets/84649544/89d6352b-d8a8-4b89-a5b8-cc24234ac5b8)

The 'overridden' statuscolumn:
![image](https://github.com/NeogitOrg/neogit/assets/84649544/81f23210-694e-49a4-bda2-3cab9b125fd9)

### Neovim version

NVIM v0.10.0-dev-2918+gb35f08ddb1
Build type: RelWithDebInfo
LuaJIT 2.1.1702233742

### Operating system and version

Linux 6.8.4

### Steps to reproduce

1. Launch Neogit
2. Move to a file in the unstaged changes section
3. Use `<C-v>` to open the file

### Expected behavior

Opening a file using the status buffer shouldn't interfere with the statuscolumn

### Actual behavior

The only way to recover the original statuscolumn is to relaunch neovim :(

### Minimal config

```Lua
-- NOTE: See the end of this file if you are reporting an issue, etc. Ignore all the "scary" functions up top, those are
-- used for setup and other operations.
local M = {}

local base_root_path = vim.fn.fnamemodify(debug.getinfo(1, "S").source:sub(2), ":p:h") .. "/.min"
function M.root(path)
  return base_root_path .. "/" .. (path or "")
end

function M.load_plugin(plugin_name, plugin_url)
  local package_root = M.root("plugins/")
  local install_destination = package_root .. plugin_name
  vim.opt.runtimepath:append(install_destination)

  if not vim.loop.fs_stat(package_root) then
    vim.fn.mkdir(package_root, "p")
  end

  if not vim.loop.fs_stat(install_destination) then
    print(string.format("> Downloading plugin '%s' to '%s'", plugin_name, install_destination))
    vim.fn.system({
      "git",
      "clone",
      "--depth=1",
      plugin_url,
      install_destination,
    })
    if vim.v.shell_error > 0 then
      error(string.format("> Failed to clone plugin: '%s' in '%s'!", plugin_name, install_destination),
        vim.log.levels.ERROR)
    end
  end
end

---@alias PluginName string The plugin name, will be used as part of the git clone destination
---@alias PluginUrl string The git url at which a plugin is located, can be a path. See https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols for details
---@alias MinPlugins table<PluginName, PluginUrl>

---Do the initial setup. Downloads plugins, ensures the minimal init does not pollute the filesystem by keeping
---everything self contained to the CWD of the minimal init file. Run prior to running tests, reproducing issues, etc.
---@param plugins? table<PluginName, PluginUrl>
function M.setup(plugins)
  vim.opt.packpath = {}                      -- Empty the package path so we use only the plugins specified
  vim.opt.runtimepath:append(M.root(".min")) -- Ensure the runtime detects the root min dir

  -- Install required plugins
  if plugins ~= nil then
    for plugin_name, plugin_url in pairs(plugins) do
      M.load_plugin(plugin_name, plugin_url)
    end
  end

  vim.env.XDG_CONFIG_HOME = M.root("xdg/config")
  vim.env.XDG_DATA_HOME = M.root("xdg/data")
  vim.env.XDG_STATE_HOME = M.root("xdg/state")
  vim.env.XDG_CACHE_HOME = M.root("xdg/cache")

  -- NOTE: Cleanup the xdg cache on exit so new runs of the minimal init doesn't share any previous state, e.g. shada
  vim.api.nvim_create_autocmd("VimLeave", {
    callback = function()
      vim.fn.system({
        "rm",
        "-r",
        "-f",
        M.root("xdg")
      })
    end
  })
end

-- NOTE: If you have additional plugins you need to install to reproduce your issue, include them in the plugins
-- table within the setup call below.
M.setup({
  plenary = "https://github.com/nvim-lua/plenary.nvim.git",
  telescope = "https://github.com/nvim-telescope/telescope.nvim",
  diffview = "https://github.com/sindrets/diffview.nvim",
  neogit = "https://github.com/NeogitOrg/neogit"
})
-- WARN: Do all plugin setup, test runs, reproductions, etc. AFTER calling setup with a list of plugins!
-- Basically, do all that stuff AFTER this line.
require("neogit").setup({}) -- For instance, setup Neogit
```

**Comment by CKolkey** [comment]
Oh, no worries, fixed here 8c69b8780 - lemme know if you still have any issues :)

**Comment by igorlfs** [comment]
Hey! I just tested the latest commit, and I'm still having the issue. I assumed the error was caused by 'statuscolumn' being unset, but that isn't the case. In fact, I restored the previous commit and the option was working just fine. It might be the 'statuscol.nvim' plugin, but I will need some time to investigate.

**Comment by igorlfs** [comment]
Okay, found out something interesting: it looks like it's a tab setting. Any file opened in the tab containing Neogit's status buffer will show this behavior, no matter how it was opened -- I tested using `:vnew` and telescope's `find_files`. So there must be a tab setting that should only apply to Neogit's windows inside tabs containing Neogit buffers, but it's currently being applied to every window inside tabs containing Neogit buffers. Any thoughts?

**Comment by igorlfs** [comment]
Update: latest commit on nightly is fine

**Comment by CKolkey** [comment]
Yeah, I ditched the statuscolumn thing for the status buffer entirely 😅 back to just using the sign column
