### ISSUE TITLE
Add different highlights for Status sections

### ISSUE THREAD

**Issue by petobens** [NeogitOrg/neogit#1255]
Hi! AFAICT all sections in the Status window are highlighted the same. I was wondering whether specific highlights could be added. In the image you can see how fugitive does it (i.e untracked in yellow, unstaged in red)  which I think is more intuitive/useful. Thanks in advance!

Bonus: can we add an icon symbol to untracked/modified akin to fugitive's `?` and `M` signs?

![image](https://github.com/NeogitOrg/neogit/assets/2583971/48461a07-21ad-420d-bc1f-c2a595da1e12)

**Comment by CKolkey** [comment]
Ok, with fd63c19287cb275ea38d2c85f41ce712a816c160 you can customize the text for item status :)

**Comment by petobens** [comment]
Thank you!
