### ISSUE TITLE
Add option to follow hunk and open in new tab/split

### ISSUE THREAD

**Issue by printfdebugging** [NeogitOrg/neogit#1257]
**Is your feature request related to a problem? Please describe.**
So when I follow a hunk from the status view, it closes the neogit tab, and opens that hunk's file in a new buffer. Where I was in neogit is lost. so I have to open neogit again, and then search for which file's which hunk I was looking at, and then repeate.

**Describe the solution you'd like**
I want an option in the config (something like newtab = true) such that whenever I follow a hunk, it goes into a new tab, where I can make changes to it, and once done, I come back to neogit tab, and find it refreshed. From there I can continue.

**Describe alternatives you've considered**
Split support can be added as well like pressing enter on a hunk from either the status view or the commit view (not implemented yet) should open that hunk in a split.

**Comment by CKolkey** [comment]
Thats a thing! `<c-t>` will to `TabOpen`, which keeps the existing neogit tab around :)
