### ISSUE TITLE
[Nightly] Add option to disable the commit diff view window

### ISSUE THREAD

**Issue by b0o** [NeogitOrg/neogit#1261]
It seems there's no way to disable the commit diff view in the configuration. I tested the following patch and it does what I want, but since `show_diff` is hard-coded, it's not configurable.

```patch
diff --git a/lua/neogit/popups/commit/actions.lua b/lua/neogit/popups/commit/actions.lua
index 16622fe5..12663832 100644
--- a/lua/neogit/popups/commit/actions.lua
+++ b/lua/neogit/popups/commit/actions.lua
@@ -31,7 +31,7 @@ local function do_commit(popup, cmd)
       success = "Committed",
     },
     interactive = true,
-    show_diff = true,
+    show_diff = false,
   })
 end
```

**Comment by CKolkey** [comment]
Fair - here you are: [`9f29110` (#978)](https://github.com/NeogitOrg/neogit/pull/978/commits/9f291107a9f26b775f501799d9c50bcf9d71b9cc) :)

**Comment by b0o** [comment]
Thank you!
