### ISSUE TITLE
Autorefresh not working after writing a file?

### ISSUE THREAD

**Issue by petobens** [NeogitOrg/neogit#1265]
Hi! AFAICT in nightly the `filewatcher` settings is always set to `true`. However, as it can be (almost) seen in the GIF, when I add a change to a file and write the file then the Status window doesn't autorefresh but rather I need to move to the Status window and press `<C-r>` for it to do so. Dunno if this a feature or bug:

![Peek 2024-04-28 16-55](https://github.com/NeogitOrg/neogit/assets/2583971/b6bbaa3e-1983-4239-8ba5-aa40b3b36b46)

**Comment by CKolkey** [comment]
Right, the filewatcher only watches files inside `./.git/`, so if you stage something from another place, or some internal rebase stuff, merge stuff, it'll do an update. Would be pretty cool to watch other open buffers, though. I'll see what it would take to track that stuff.

**Comment by CKolkey** [comment]
Ok! Turns out, there's already an autocmd that _should_ have been doing this.. But, because I had opted-out of updating non-focused buffers because you can make folds in unfocused buffers, it wasn't working. So, I rewrote how we do folds slightly so it's always called in the right context: 1d021f2d08e5f2eaa5055ffcec9914df7e48a135

Should be good now! Thanks for the tip.

**Comment by petobens** [comment]
Hi @CKolkey. Thanks for the quick reply. Mmm I tried this (as in the GIF) and i) I still need to press `<C-r>` for the status buffer to refresh and ii) now the folds are highlighted in gray instead of white (I guess that should be easy to fix/override)

![Peek 2024-04-28 23-32](https://github.com/NeogitOrg/neogit/assets/2583971/a5408e93-8425-4917-9d09-4170ef4fb50d)

**Comment by petobens** [comment]
Hi @CKolkey. Just to followup, after https://github.com/NeogitOrg/neogit/pull/978/commits/183212cf217f4741266f7a767740ca43deacc7b4 both ii) and iii) of my last comment are fixed :) 

However I do notice that i) is still not working. In fact, as it can be seen in the GIF, there is no "autorefresh" after any of the following: writing a file, commiting it, pushing. In each case I need to press `<C-r>` for the status buffer to refresh. In particular i think it would be really useful to have such autorefresh behavoir since it avoids having the  "Commited" and "Pushed to origin/master" messages.

![Peek 2024-05-01 16-40](https://github.com/NeogitOrg/neogit/assets/2583971/369dcc95-c2ca-4ff6-ac9f-d422b1046d8c)
