### ISSUE TITLE
Add file/directory to .gitignore

### ISSUE THREAD

**Issue by KorigamiK** [NeogitOrg/neogit#1268]
**Is your feature request related to a problem? Please describe.**
Currently its a pain to manually add file names to the .gitignore manually

**Describe the solution you'd like**
An action for items in the unstaged list for adding file to .gitignore would be appreciated

**Comment by CKolkey** [comment]
Looks like there was a little bug preventing the items from being listed. It's been fixed on `nightly`. Thanks for the tip :)

**Comment by KorigamiK** [comment]
If anyone is wondering `i` brings up the ignore popup :)
