### ISSUE TITLE
Disable context higlight

### ISSUE THREAD

**Issue by petobens** [NeogitOrg/neogit#1272]
Hi! I was looking into how to disable this thing were the highlighting in diffs turn bright as in the GIF. I saw there is a config option `disable_context_highlighting` but it doesn't seem to take effect? Dunno if this a bug or a feature request to add a config to that end. Thanks!

![Peek 2024-05-01 11-23](https://github.com/NeogitOrg/neogit/assets/2583971/8ea50ad6-d195-4927-bfba-3e1a19ee8905)

**Comment by CKolkey** [comment]
Thanks, missed that when rewriting some stuff - fixed here 5ee392a076c30eddb771ab87362876f0b4c9c2b5 :)
