### ISSUE TITLE
Add support for add --patch

### ISSUE THREAD

**Issue by clobrano** [NeogitOrg/neogit#1284]
**Is your feature request related to a problem? Please describe.**
The commit view only allows to add an entire hunk

**Describe the solution you'd like**
Very often is useful to only add part of the hunk, via [git add --patch](https://git-scm.com/docs/git-add#Documentation/git-add.txt--p)

**Describe alternatives you've considered**
There is no specific alternative

**Additional context**
This is one of the most useful features implemented in fugitive

**Comment by CKolkey** [comment]
You can partially stage a hunk by using visual-line mode `V` to select the region  to stage

**Comment by clobrano** [comment]
My bad, I didn't try the uppercase `V`
