### ISSUE TITLE
A lua api to open Commit view

### ISSUE THREAD

**Issue by ptn** [NeogitOrg/neogit#1288]
**Is your feature request related to a problem? Please describe.**
I use a different plugin for blaming files, and I still use the old Gina written in vimscript as it has an incomparable `git log` implementation that uses streaming. I would like to be able to assign a mapping to these other plugins where pressing Enter opens _Neogit's_ commit view. 

**Describe the solution you'd like**
Something like `neogit.open("commit", $commit_hash)` - or whatever really.

**Describe alternatives you've considered**
--

**Additional context**
--

**Comment by CKolkey** [comment]
I might add a more public api for this at some point, but for now (and the forseeable future) this will work:

```lua
require("neogit.buffers.commit_view").new("<hash>"):open()
```

The `open()` method can optionally take a string for what kind of buffer to create, like "split", "vsplit", etc.
