### ISSUE TITLE
Allow `show_staged_diff` to open in a vertical split

### ISSUE THREAD

**Issue by ptn** [NeogitOrg/neogit#1293]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'd like to be able to configure `show_staged_diff` to open in a vertical split. At the moment it always opens the diff buffer at the bottom, but I'd love to see it to the right.

**Describe alternatives you've considered**

**Additional context**
I'd love to send you a PR if you help me by pointing out where the code should go.

**Comment by CKolkey** [comment]
Sounds good - its defined on line 57 here:
lua/neogit/buffers/diff/init.lua

Check out some other buffers where a config value is passed there instead :)
