### ISSUE TITLE
un staged files showing folded without filename by default 

### ISSUE THREAD

**Issue by ashish10alex** [NeogitOrg/neogit#1294]
### Description

After the latest release `v1.0.0` , when running `:Neogit` the un-staged files and the commits are folded by default. which is hiding the filename. I am able to run `: lua vim.o.foldenable = false` to bring back the expected behaviour.  I assumed it must be some config change that I might have missed. I changed all the fold options to false but this only fixed the commit list folding. 

Is there a config that I am missing or is this by design ? 

https://github.com/NeogitOrg/neogit/assets/34306898/068f51ec-fb97-4ff5-9cc6-96970c988742

### Neovim version

NVIM v0.10.0-dev-565+g3688735c2-Homebrew
Build type: Release
LuaJIT 2.1.1713773202

### Operating system and version

macOS  Sanoma 14.4.1 

### Steps to reproduce

1. Run `:Neogit`
2. `: lua vim.o.foldenable = false`  to get expected UI with filenames

### Expected behavior

filenames should show with just the diff folded 

### Actual behavior

no filenames showing only shows `+ -- x line folded`

### Minimal config

```Lua
Neogit config used with Lazy nvim Plugin manager 


return {
    "NeogitOrg/neogit",
    dependencies = {
        "nvim-lua/plenary.nvim",  -- required
        "sindrets/diffview.nvim", -- optional - Diff integration

        -- Only one of these is needed, not both.
        "nvim-telescope/telescope.nvim", -- optional
    },
    config = function()
        local neogit = require('neogit')
        neogit.setup({
            sections = {
                sequencer = {
                    folded = false,
                    hidden = false,
                },
                bisect = {
                    folded = false,
                    hidden = false,
                },
                untracked = {
                    folded = false,
                    hidden = false,
                },
                unstaged = {
                    folded = false,
                    hidden = false,
                },
                staged = {
                    folded = false,
                    hidden = false,
                },
                stashes = {
                    folded = false,
                    hidden = false,
                },
                unpulled_upstream = {
                    folded = false,
                    hidden = false,
                },
                unmerged_upstream = {
                    folded = false,
                    hidden = false,
                },
                unpulled_pushRemote = {
                    folded = false,
                    hidden = false,
                },
                unmerged_pushRemote = {
                    folded = false,
                    hidden = false,
                },
                recent = {
                    folded = false,
                    hidden = false,
                },
                rebase = {
                    folded = false,
                    hidden = false,
                },
            },
        })

        vim.keymap.set('n', '<leader>gs', ':Neogit<CR>', { silent = true })
    end

}

```
```

**Comment by CKolkey** [comment]
What does `:lua print(vim.wo.foldtext)` show?

**Comment by ashish10alex** [comment]
Hi, It does not print out anything 

https://github.com/NeogitOrg/neogit/assets/34306898/ba5b7a66-bd7f-4ebc-bf59-a92d75663ab5

**Comment by avegancafe** [comment]
I'm also hitting this issue, and have been on nightly for quite a while. Seems like something was just merged into master?

**Comment by ashish10alex** [comment]
Hi @CKolkey , I used your minimum config. Had to change the url of neogit as I believe its Is hardcoded to your personal path. I still have the same issue though 

![CleanShot 2024-05-17 at 23 26 38@2x](https://github.com/NeogitOrg/neogit/assets/34306898/e0a7088c-6326-4f28-b7c7-b58b21629217)

**Comment by ashish10alex** [comment]
I uninstall neovim and re-installed the latest and greatest using which fixed the folding issue for me

```
brew unistall neovim
brew install neovim --HEAD
```

nvim version after the above commands

```
❯ nvim --version
NVIM v0.11.0-dev-3170+g0f4f7d32c-Homebrew
Build type: Release
LuaJIT 2.1.1713773202
```
