### ISSUE TITLE
`ZZ`/`ZQ` shortcuts for rebase message editor

### ISSUE THREAD

**Issue by chuckhousley** [NeogitOrg/neogit#1296]
nvim nightly, neogit master as of this evening
**Is your feature request related to a problem? Please describe.**
Feature parity with magit, expected behavior within nvim. Currently `ZZ` in a rebase message buffer does not edit the commit message but instead creates a new commit.

**Describe the solution you'd like**
Select a commit and use the [r]ebase -> re[w]ord action 
Pressing `ZZ` in normal mode (the vim "write and quit" shortcut) within the buffer should behave as <c-c><c-c> does and perform the reword action instead of creating a new commit. `ZQ` should behave as `<c-c><c-k>` does. If the reword buffer has been manually saved, `ZQ` will quit and create a new commit with the saved buffer as the message, `<c-c><c-k>` discards the new rewritten message even if the buffer was manually saved.

**Describe alternatives you've considered**
I have added the mappings to the `rebase_editor` map in `lua/neogit/config.lua`, this seems to match the behavior I am expecting but I haven't tested beyond a few commits.

Thanks

**Comment by CKolkey** [comment]
Good catch, thanks
