### ISSUE TITLE
Neogit doesn't work anymore with latest commit and default config

### ISSUE THREAD

**Issue by led0nk** [NeogitOrg/neogit#1297]
### Description

Hey,

i got some issues since I recently updated my Neogit.
I'm on branch `master` and commit `9040f6f`.

My first issue comes with default config. I copied the Default Config provided in the README.md.
It seems to not work anymore with the provided mappings, because it produces this error:

![image](https://github.com/NeogitOrg/neogit/assets/10290002/db42aa96-623b-46d6-9395-d9f1dd7622f7)

Therefore i went back to the minimal setup and only running:

```lua
require("neogit").setup({})
```

If i now try to run neogit, it leads me here:

![image](https://github.com/NeogitOrg/neogit/assets/10290002/3ecbeff1-79fd-49b6-b4c1-8afb20bca46f)

The latest commit, which worked for me was `4f0ca51`.
I'm not quite sure how to solve this problem since it came with latest update and default configuration.

### Neovim version

NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1707061634

### Operating system and version

Fedora 40

### Steps to reproduce

1. use neogit default config
2. try to run neogit

### Expected behavior

simply run neogit

### Actual behavior

getting the error, which you can see in provided screenshots

### Minimal config

```Lua
return {
	{
		"tpope/vim-fugitive",
	},
	{
		"NeogitOrg/neogit",
		dependencies = {
			"nvim-lua/plenary.nvim", -- required
			"sindrets/diffview.nvim", -- optional - Diff integration

			-- Only one of these is needed, not both.
			"nvim-telescope/telescope.nvim", -- optional
			"ibhagwan/fzf-lua", -- optional
		},
		config = function()
			require("neogit").setup({})
			vim.keymap.set("n", "<leader>ng", ":Neogit<CR>")
		end,
	},
}
```

**Comment by CKolkey** [comment]
If you're on `master` then you either need to update neovim to 0.10, or pin to the `v0.0.1` tag.

https://github.com/NeogitOrg/neogit/issues/1295
