### ISSUE TITLE
Open Current Branch in Browser

### ISSUE THREAD

**Issue by derethil** [NeogitOrg/neogit#1327]
**Is your feature request related to a problem? Please describe.**
As far as I know, there is no current way to open the current branch in the browser from Neogit. This is something I do quite often to quickly start going through issues, PRs, etc.  Before primarily moving to Neogit I had been using [git-open](https://github.com/paulirish/git-open) to accomplish this.

**Describe the solution you'd like**
It makes the most sense to me to remap the existing `b o`  to do this since the action is simply opening the branch URL. Opening a new pull request link is slightly different and hence could be remapped to `b p`  or something.

**Describe alternatives you've considered**
Alternatively, if remapping an existing action is an issue, a keymap that doesn't conflict with the current actions could be implemented as well.

**Additional context**
N/A

**Comment by CKolkey** [comment]
Good call! Bound to `o` on the status buffer.
