### ISSUE TITLE
Question: NeogitStatus based on a tree-sitter grammar

### ISSUE THREAD

**Issue by vheon** [NeogitOrg/neogit#138]
Hi, this is more of a "did you ever think about it" than an actual issue, just to know if you ever think about it if you find some problems etc. From what I gather right now the `NeogitStatus` is structured and handled all in lua so for example when I press `Tab` to fold something there is code to figure out where I am in the status buffer and do the appropriate thing regarding folding. What I was thinking is: if we have a tree-sitter grammar for the `NeogitStatus` will this be simplified? We would basically have a grammar for the sections and then injections for the diff (maybe using something like https://github.com/vigoux/tree-sitter-diff). At that point all the highlighting would be handled by tree-sitter and the "where I am with the cursor" would basically resolve to query the tree-sitter AST.

**Comment by TimUntersberger** [comment]
I have thought about this before and I would really like to have something like this! 

I never really took the time to learn how something like that would work, because the solution right now works decent.

Exploring something in that direction would be really cool 👍
