### ISSUE TITLE
Override palette in config

### ISSUE THREAD

**Issue by GordianDziwis** [NeogitOrg/neogit#1394]
**Is your feature request related to a problem? Please describe.**
The heuristics for defining the base palette do not work for my color schema.

**Describe the solution you'd like**
Being able to set the base palette as a config option

**Describe alternatives you've considered**
Hard-code my palette in `hl.lua`

```lua
local function make_palette()
  local bg     = Color.from_hex(get_bg("Normal") or "#151515")
  local fg     = Color.from_hex("#D0D0D0")
  local red    = Color.from_hex("#FF0086")
  local orange = Color.from_hex("#FD8900")
  local yellow = Color.from_hex("#ABA800")
  local green  = Color.from_hex("#00C918")
  local cyan   = Color.from_hex("#1FAAAA")
  local blue   = Color.from_hex("#3777E6")
  local purple = Color.from_hex("#AD00A1")

  local config = require("neogit.config")

  local bg_factor = vim.o.bg == "dark" and 1 or -1
...
```

**Comment by CKolkey** [comment]
Reasonable enough, sure.

**Comment by SheffeyG** [comment]
Totally on board with this, somehow the `get_fg("Error")` in my setup is black instead of red! so Neogit looks weird like this
![image](https://github.com/user-attachments/assets/cd6708ea-9d60-4830-9437-4d9498f6b878)
customizable palette or a configuration to use the default Neogit color palette would be a good idea.

**Comment by CKolkey** [comment]
Sorry, forgot to document it 😅 

You can provide a table to `config.highlight` to overload any derived colors.

https://github.com/NeogitOrg/neogit/commit/daad0e1b7df8da2260455339f9615c640b19c27d
