### ISSUE TITLE
Merging  branches

### ISSUE THREAD

**Issue by timsofteng** [NeogitOrg/neogit#142]
Hello. How can i merge one local branch to another with `neogit`?

**Comment by TimUntersberger** [comment]
This is not possible yet. What would you expect of this feature?

I think having a merge popup (M) like in magit would be a good idea.

**Comment by timsofteng** [comment]
> This is not possible yet. What would you expect of this feature?
> 
> I think having a merge popup (M) like in magit would be a good idea.

Got it. I didn't use magit, but in lazygit it works by pressing M to some of branch which you want to merge to current. I'm not sure is it better than magit's solution or not.
Popup sounds good for me as well.

**Comment by TimUntersberger** [comment]
We could the same as with diff, where `M` opens the general merge popup and `m` tries to merge a hovered branch.

**Comment by timsofteng** [comment]
> We could do the same as with diffing, where `M` opens the general merge popup and `m` tries to merge a hovered branch.

Sounds good. Again I dunno how it works in magit. But for me personal it is enough for merging. You can see many options in magit doc:
https://magit.vc/manual/magit/Merging.html

So popup sounds good.

**Comment by CKolkey** [comment]
The merge popup is added
