### ISSUE TITLE
Cursor jumps to the top of the screen when saving a file when Neogit is open

### ISSUE THREAD

**Issue by igorlfs** [NeogitOrg/neogit#1429]
### Description

Saving a file causes the cursor to jump to the of the window.

### Neovim version

NVIM v0.11.0-dev-485+g9322b7e059
Build type: Release
LuaJIT 2.1.1720049189

### Operating system and version

Linux 6.9

### Steps to reproduce

1. Launch neovim and open a file inside a git repo
2. `:Neogit`
3. `gt` to switch back to the tab containing the file
4. `20j` to scroll down a bit
5. `:w`

### Expected behavior

The cursor shouldn't randomly jump.

### Actual behavior

The cursor jumps to random position at the top of the file.

### Minimal config

```Lua
for name, url in pairs({
	"https://github.com/NeogitOrg/neogit",
	"https://github.com/nvim-lua/plenary.nvim",
}) do
	local install_path = vim.fn.fnamemodify("nvim_issue/" .. name, ":p")
	if vim.fn.isdirectory(install_path) == 0 then
		vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
	end
	vim.opt.runtimepath:append(install_path)
end

require("neogit").setup()
```

**Comment by CKolkey** [comment]
Fixed in https://github.com/NeogitOrg/neogit/pull/1430 - thanks for the report :)
