### ISSUE TITLE
FEATURE REQUEST: cherry picking

### ISSUE THREAD

**Issue by timsofteng** [NeogitOrg/neogit#143]
Hey!
I have another feature request. It is commits cherry picking. Hope it can be implemented someday.

**Comment by timsofteng** [comment]
hello. any news about it?

**Comment by TimUntersberger** [comment]
@timsofteng none. I am willing to accept any PRs 😄

**Comment by CKolkey** [comment]
https://github.com/TimUntersberger/neogit/pull/466

**Comment by timsofteng** [comment]
@CKolkey I guess we may close it as it has been implemented
