### ISSUE TITLE
Suggestion: Submit commit if .git/COMMIT_EDITMSG is saved and closed

### ISSUE THREAD

**Issue by Miyelsh** [NeogitOrg/neogit#1432]
Currently, the way to submit a commit is with the `<CTRL-C><CTRL-C>` keybind. If I save and quit a commit with ":wq", the commit is not submitted.

Suggestion: saving and quitting the .git/COMMIT_EDITMSG should commit instead of quitting. This would make neogit behave identically to if a commit was initiated in the command line with "git commit"

If the commit file is closed without saving, then the commit should be aborted.

**Comment by CKolkey** [comment]
I just tried `:wq` and it did work to submit the commit. Maybe something else is going on?

**Comment by Miyelsh** [comment]
> I just tried `:wq` and it did work to submit the commit. Maybe something else is going on?

You are right. I just updated to latest and this works as expected. Wonderful! Closing now.
