### ISSUE TITLE
Properly Colored Unicode Graphs

### ISSUE THREAD

**Issue by raxyte** [NeogitOrg/neogit#1442]
**Is your feature request related to a problem? Please describe.**
Currently, Neogit does not have the ability to show colored unicode graphs (much cleaner), unlike the ASCII version. This results in an unfortunate look for them.

**Describe the solution you'd like**
Similar coloring to the ASCII graphs would be fantastic.

**Describe alternatives you've considered**
Switch back to the ASCII version. (I much prefer to not go back.)

**Additional context**
Since it looks like this was initially inspired by [vim-flog](https://github.com/rbong/vim-flog), perhaps looking at it is of help?

**Comment by CKolkey** [comment]
Check out the "kitty" style graph :)

**Comment by raxyte** [comment]
I already had checked that out, unfortunately I use alacritty which doesn't support that. I'm fine with closing the issue however. Thank you for the amazing work you and everyone else does on the plugin!

**Comment by CKolkey** [comment]
I believe you can get that working with this font https://github.com/rbong/flog-symbols - though I have not tested it.

**Comment by raxyte** [comment]
I was kind of holding off on patching fonts but I guess that is a path. 👍

**Comment by camoz** [comment]
@raxyte It is also possible without patching the font, see here: https://github.com/rbong/flog-symbols/issues/4
