### ISSUE TITLE
Cannot discard files/directories in visual mode

### ISSUE THREAD

**Issue by enrique-villarrealp** [NeogitOrg/neogit#1471]
### Description

When wanting to discard more than one whole file / directory at once, Neogit slightly freezes up, and no popup appears. A mere press of the Esc key is enough to restore function. No error message at all pops up, and no command appears if I try to show the command history with $ on the status window.

Discarding files individually works, whether they're unstaged, staged, new files , or not.
Also, trying to discard all items by category (all unstaged files, for example) by trying to use the corresponding header works fine.

### Neovim version

NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1724512491

### Operating system and version

macOS 14.4.1

### Steps to reproduce

1. Install neogit using lazy as per the configuration below.
2. Open Neogit status on a repo with more than one change
3. Use V to enter Visual Line mode, select various items and press x to discard.

### Expected behavior

Popup to confirm discarding multiple files appears

### Actual behavior

Nothing happens, Neogit status freezes up until Esc is pressed

### Minimal config

```Lua
return {
  "NeogitOrg/neogit",
  lazy=false,
  dependencies = {
    "nvim-lua/plenary.nvim",
    "sindrets/diffview.nvim",
  },
  cmd = { "Neogit", "NeogitResetState" },
  opts = {
    integrations = {
      diffview = true,
    },
    kind = "split"
  },
}
```

**Comment by enrique-villarrealp** [comment]
Turns out that indeed the issue isn't on neogit, but Folke's noice :) Removed that and neogit is back to normal. Closing this issue and raising it there!

**Comment by CKolkey** [comment]
glad to hear it - I was a little confused, since it works fine for me :)
