### ISSUE TITLE
DISABLING spell checker

### ISSUE THREAD

**Issue by Kyren223** [NeogitOrg/neogit#1479]
I find the spellchecker introduced recently really annoying and it's impossible to disable.
There should be a config option to disable it.
And in my opinion, it should be opt-in, but I wouldn't mind opt-out either.

**Comment by rami3l** [comment]
I second this. Personally I use `cspell` for spell checking already, so I've disabled the native spellchecker. However, `neogit` seems to have ignored the global setting...

**Comment by CKolkey** [comment]
Fair - I added an option to toggle it. Feel free to make a PR if you think this could hook into nvim better. I have no time right now to do much more than this, I'm afraid.
