### ISSUE TITLE
Change in modes not detected

### ISSUE THREAD

**Issue by acampove** [NeogitOrg/neogit#1482]
**Is your feature request related to a problem? Please describe.**
The plugin does not detect changes in file permissions, e.g. if I do chmod 644 file, the mode change normally is caught by git status.

**Describe the solution you'd like**
Maybe a message like `mode change 744 -> 644` next to the file in the unstaged section or a message like this when toggling.

**Describe alternatives you've considered**
None really

**Additional context**
When toggling no change appears.

![image](https://github.com/user-attachments/assets/9068775e-d518-427d-aab8-62a224259444)

**Comment by CKolkey** [comment]
Yeah, good call. Done here 43060b2053c6715e218c0b21bd74f71c77b1e677 :)
