### ISSUE TITLE
Commit log cursor location

### ISSUE THREAD

**Issue by mehalter** [NeogitOrg/neogit#1487]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I open a commit log with something like `ll` or `lo` and my cursor is at the bottom of the buffer with the log. I nearly always begin with `:2<CR>` to go to the latest commit in the log first.

**Describe the solution you'd like**
It would be nice if the default location of the cursor when opening a commit log is the latest commit. That way I always know where my cursor will be in my workflow. By being at the last line in the window, the commit I find myself is at some arbitrary distance from the latest commit depending on the size of my window.

**Describe alternatives you've considered**
I currently just do `ggj` or `:2<CR>` every time I open the log.

**Additional context**
n/a

**Comment by CKolkey** [comment]
Yeah, that was super annoying. Fixed here: https://github.com/NeogitOrg/neogit/commit/2a2bde6dfe5460ae12c2f1b7d6de8fcd3d505bcd

Feel free to reopen if you still have issues.
