### ISSUE TITLE
Discarding untracked folders not working

### ISSUE THREAD

**Issue by AlejandroSanchez90** [NeogitOrg/neogit#1502]
### Description

When i try to discard an untracked folder with x, nothing happens, if i expend the untracked folder to see its content nothing shows up, i have to stage this untracked folder, and then discard each file and then the untracked folder disapear

### Neovim version

10.0.0

### Operating system and version

macos

### Steps to reproduce

create new folder, add file, and try to discard without staging or tracking the folder

### Actual behavior

untracked folder cant be discarded, and i cant see the files inside them unless i stage them

### Minimal config

```Lua
return {
	"NeogitOrg/neogit",
	dependencies = {
		"nvim-lua/plenary.nvim", -- required
		"sindrets/diffview.nvim", -- optional - Diff integration

		-- Only one of these is needed, not both.
	},
	config = function()
		local neogit = require("neogit")
		neogit.setup({})

		local keymap = vim.keymap -- for conciseness
		keymap.set("n", "<leader>go", "<cmd>Neogit<cr>", { desc = "Open NeoGit" })
		keymap.set("n", "<leader>gf", "<cmd>Neogit fetch<cr>", { desc = "Fetch" })
		keymap.set("n", "<leader>gb", "<cmd>Neogit branch<cr>", { desc = "Branch" })
		keymap.set("n", "<leader>gg", "<cmd>Neogit commit<cr>", { desc = "Commit" })
		keymap.set("n", "<leader>gp", "<cmd>Neogit push<cr>", { desc = "Push" })
		keymap.set("n", "<leader>gs", "<cmd>FzfLua git_status<cr>", { desc = "Status" })

		keymap.set("n", "<leader>gdh", "<cmd>DiffviewFileHistory % --base=LOCAL<cr>", { desc = "File github history" })

		--DiffviewFileHistory % --base=LOCAL
	end,
}
```

**Comment by CKolkey** [comment]
I think there's a misunderstanding here: neogit is an interface for _git_ operations, not _filesystem_ operations. `x` (discard) functions to discard changes to a file and revert it to `HEAD`. A directory that isn't tracked by git is just kinda... nothing. Doesn't exist. So, no bug, you just can't remove directories by design.

That said, you _should_ be able to see files that are in directories that are untracked:

<img width="364" alt="Screenshot 2024-10-11 at 13 21 36" src="https://github.com/user-attachments/assets/2875ad10-0840-4ef4-bb26-e14c86802a29">

**Comment by AlejandroSanchez90** [comment]
I understand thanks, I do single files that are untracked, but if I create
new folder with files in it, the only way to see those files is by tracking
the folder and then I can discard files inside the folder

**Comment by CKolkey** [comment]
Do you mind making a screen recording so I can see what you mean? Maybe I'm missing something 🤷

**Comment by AlejandroSanchez90** [comment]
> Do you mind making a screen recording so I can see what you mean? Maybe I'm missing something 🤷

lets say i create a new folder named 'test', this will be untracked right?, now if i add files a.ts and b.ts, i dont see them in the untracking files because they are behind an untracked folder, so in order to discard b.ts, i have to first track the folder then discard b.ts
