### ISSUE TITLE
Major Bug: attempt to call field 'detach' (a nil value)

### ISSUE THREAD

**Issue by Alan-John-Byrne** [NeogitOrg/neogit#1503]
### Description

Upon running the *<u>:Neogit<u>* command (or any other command) to open up the status of a repository (whilst located within a buffer, somewhere in that project's root), we get the following error:

*attempt to call field 'detach' (a nil value)*
 
***Full Stack Trace:***
 
Error executing Lua callback: ...ta/Local/nvim-data/lazy/neogit/lua/neogit/lib/buffer.lua:350: attempt to call field 'detach' (a nil value)
stack traceback:
	...ta/Local/nvim-data/lazy/neogit/lua/neogit/lib/buffer.lua:350: in function 'show'
	...ta/Local/nvim-data/lazy/neogit/lua/neogit/lib/buffer.lua:615: in function 'create'
	...nvim-data/lazy/neogit/lua/neogit/buffers/status/init.lua:93: in function 'open'
	...alanj/AppData/Local/nvim-data/lazy/neogit/lua/neogit.lua:114: in function 'open_status_buffer'
	...alanj/AppData/Local/nvim-data/lazy/neogit/lua/neogit.lua:178: in function 'open'
	...nj/AppData/Local/nvim-data/lazy/neogit/plugin/neogit.lua:5: in function <...nj/AppData/Local/nvim-data/lazy/neogit/plugin/neogit.lua:3>

### Neovim version

NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1713484068

### Operating system and version

Microsoft Windows Version 23H2 (OS Build 22631.4317)

### Steps to reproduce

1. Have neogit installed via lazy.nvim (LazyVim), or any other way.
2. Go into a git repository, and open a files contents in a buffer.
3. Try run the :Neogit command.

### Expected behavior

You should see the status window show in a separate window below your current buffer, with all of the options to stage and commit etc....

### Actual behavior

This error pops up, and an empty window with a blank buffer is opened wither below your current buffer, or as a new blank window instead.
![image](https://github.com/user-attachments/assets/72ea59ff-1640-40e1-a03e-b84347e003b7)

### Minimal config

```Lua
-- NOTE: See the end of this file if you are reporting an issue, etc. Ignore all the "scary" functions up top, those are
-- used for setup and other operations.
local M = {}

local base_root_path = vim.fn.fnamemodify(debug.getinfo(1, "S").source:sub(2), ":p:h") .. "/.min"
function M.root(path)
  return base_root_path .. "/" .. (path or "")
end

function M.load_plugin(plugin_name, plugin_url)
  local package_root = M.root("plugins/")
  local install_destination = package_root .. plugin_name
  vim.opt.runtimepath:append(install_destination)

  if not vim.loop.fs_stat(package_root) then
    vim.fn.mkdir(package_root, "p")
  end

  if not vim.loop.fs_stat(install_destination) then
    print(string.format("> Downloading plugin '%s' to '%s'", plugin_name, install_destination))
    vim.fn.system({
      "git",
      "clone",
      "--depth=1",
      plugin_url,
      install_destination,
    })
    if vim.v.shell_error > 0 then
      error(string.format("> Failed to clone plugin: '%s' in '%s'!", plugin_name, install_destination),
        vim.log.levels.ERROR)
    end
  end
end

---@alias PluginName string The plugin name, will be used as part of the git clone destination
---@alias PluginUrl string The git url at which a plugin is located, can be a path. See https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols for details
---@alias MinPlugins table<PluginName, PluginUrl>

---Do the initial setup. Downloads plugins, ensures the minimal init does not pollute the filesystem by keeping
---everything self contained to the CWD of the minimal init file. Run prior to running tests, reproducing issues, etc.
---@param plugins? table<PluginName, PluginUrl>
function M.setup(plugins)
  vim.opt.packpath = {}                      -- Empty the package path so we use only the plugins specified
  vim.opt.runtimepath:append(M.root(".min")) -- Ensure the runtime detects the root min dir

  -- Install required plugins
  if plugins ~= nil then
    for plugin_name, plugin_url in pairs(plugins) do
      M.load_plugin(plugin_name, plugin_url)
    end
  end

  vim.env.XDG_CONFIG_HOME = M.root("xdg/config")
  vim.env.XDG_DATA_HOME = M.root("xdg/data")
  vim.env.XDG_STATE_HOME = M.root("xdg/state")
  vim.env.XDG_CACHE_HOME = M.root("xdg/cache")

  -- NOTE: Cleanup the xdg cache on exit so new runs of the minimal init doesn't share any previous state, e.g. shada
  vim.api.nvim_create_autocmd("VimLeave", {
    callback = function()
      vim.fn.system({
        "rm",
        "-r",
        "-f",
        M.root("xdg")
      })
    end
  })
end

-- NOTE: If you have additional plugins you need to install to reproduce your issue, include them in the plugins
-- table within the setup call below.
M.setup({
  plenary = "https://github.com/nvim-lua/plenary.nvim.git",
  telescope = "https://github.com/nvim-telescope/telescope.nvim",
  diffview = "https://github.com/sindrets/diffview.nvim",
  neogit = "https://github.com/NeogitOrg/neogit"
})
-- WARN: Do all plugin setup, test runs, reproductions, etc. AFTER calling setup with a list of plugins!
-- Basically, do all that stuff AFTER this line.
require("neogit").setup({}) -- For instance, setup Neogit
```

**Comment by CKolkey** [comment]
This is from a workaround I had to add for users of ufo:
- https://github.com/kevinhwang91/nvim-ufo/blob/main/lua/ufo.lua#L98
- https://github.com/NeogitOrg/neogit/blob/bab8703a4d5406548ab7feb47efbabf023f5ae1a/lua/neogit/lib/buffer.lua#L347-L351

It would seem that the "detach" function isn't present for you? Not sure why that would be, as the API for ufo hasn't changed in two years.

**Comment by Alan-John-Byrne** [comment]
> This is from a workaround I had to add for users of ufo:
> 
> - https://github.com/kevinhwang91/nvim-ufo/blob/main/lua/ufo.lua#L98
> 
> - https://github.com/NeogitOrg/neogit/blob/bab8703a4d5406548ab7feb47efbabf023f5ae1a/lua/neogit/lib/buffer.lua#L347-L351
> 
> 
> 
> It would seem that the "detach" function isn't present for you? Not sure why that would be, as the API for ufo hasn't changed in two years.

Hi, sorry for the late reply. See it's a strange issue because I never made any changes or messed with the ufo plugin. To be completely honest, I didn't know it even existed or was in the background. I'm not confident fixing something I don't understand nor am I closing this issue yet, cause I can't properly diagnose the source of the issue. It just appeared out of nowhere. Thanks again for your suggestions, and I will take a deeper look when I get the chance.

**Comment by CKolkey** [comment]
My guess is that you have _something_ in the lua runtime's lookup path called "ufo", which is possibly not related to the plugin with that name. Hence, calling a `detach` function on that table fails.

I can add an extra safeguard in neogit to verify the function exists, which should at least resolve your issue for now.

**Comment by Alan-John-Byrne** [comment]
I've checked my runtimepath contents to verify using:

:lua print(vim.inspect(vim.api.nvim_list_runtime_paths()))

I then checked 'messages' and then searched "ufo". Nothing was found unfortunately. Although there was an update 8 days ago including a handler for ufo:

![image](https://github.com/user-attachments/assets/ad0dc9be-747a-49c9-ae44-429c6b2adf56)

Not sure if this means anything, but after even updating the plugin, I'm getting the same error. Very annoying.

**Comment by Alan-John-Byrne** [comment]
I'll start from scratch with a fresh nvim install, then install only neogit, if the problem persists its not a me problem (ie: no clashing plugins) which I suspect it is. If it goes away, I'm a doof lol XD

**Comment by CKolkey** [comment]
Heh, happens to the best of us 🤷‍♂️ Lemme know :)

**Comment by Alan-John-Byrne** [comment]
I ended up having to make a backup of my config, reinstalling neovim with the LazyVim Distro from scratch, then painstakingly adding everything back in from the backup. Checking on each addition ff the problem came back. It never did, my config is back to where it was and more. So it's either something weird happened in the background whilst I was just programming regularly, or I accidentally made a typo in a config file I wasn't supposed to touch.

Thanks again for the assist.
