### ISSUE TITLE
[Feature Request] Set foldcolumn=0 by default

### ISSUE THREAD

**Issue by igorlfs** [NeogitOrg/neogit#1507]
**Is your feature request related to a problem? Please describe.**
When foldcolumn is set to a value other than `"0"`, duplicate signs may be shown, e.g.

![image](https://github.com/user-attachments/assets/04aebd7b-3bc0-4221-a012-00e0f23d8ecc)

**Describe the solution you'd like**
`set foldcolumn=0` by default for Neogit related buffers

**Describe alternatives you've considered**
So far, I've been using an autocmd to set the foldcolumn, which works fine for me, but I think the default experience could be improved with this setting.

**Additional context**
Relates to https://github.com/NeogitOrg/neogit/issues/1258 and https://github.com/NeogitOrg/neogit/issues/1400

**Comment by CKolkey** [comment]
Yea, good call. Done in 3e44062d164d11848a1663831e4366b86ef6d889

**Comment by igorlfs** [comment]
Hey there! Thanks for the fix! I was wondering if the fix could also be applied to other Neogit related buffers, such as the `NeogitCommitView`, the `NeogitLogView` and so on. IMO the `foldcolumn` doesn't convey any info for these buffers and just fills space.

**Comment by CKolkey** [comment]
Sure :)

**Comment by windowsrefund** [comment]
TBH, I think this should be undone as it overrides a setup where foldcolumn is set to auto. Honestly, I think foldcolumn is more useful than signcolumn which I've disabled with `disable_sign = true`.
