### ISSUE TITLE
Status is not updated after 'Worktree > Goto'

### ISSUE THREAD

**Issue by paidhi** [NeogitOrg/neogit#1537]
### Description

If I switch to a Git worktree ('Worktree > Goto') the interface is not updated to reflect the new location/branch.
The 'NeogitStatus' buffer still shows information about the prior location/branch.

### Neovim version

NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1727870382

### Operating system and version

Fedora Linux 40

### Steps to reproduce

1. Open `NeogitStatus`
2. Change to another worktree ('Worktree > Goto')

### Expected behavior

The interface in the NeogitStatus buffer updates to reflect the new location & branch.

### Actual behavior

The 'NeogitStatus' buffer still shows information about the prior location/branch:

- Infos: Head, Merge, Push
- Recent Commits
- Lualine branch name

`<c-r>` to refresh does not update the information.
The only change I can see is that `:pwd` shows the path to the worktree I switched into.
Also 'Log > Current' or 'Log > HEAD' use the prior branch.

The only way I can update the interface to refelect the new location is to quit
the 'NeogitStatus' buffer and reopen it.

### Minimal config

```Lua
-- Installed Neogit via Lazy.nvim

{ 'NeogitOrg/neogit',
  cmd = 'Neogit',
  dependencies = {
    'nvim-lua/plenary.nvim',
    'nvim-telescope/telescope.nvim',
    'sindrets/diffview.nvim',
  },
  config = true
},
```

**Comment by CKolkey** [comment]
fixed: 2eae717f6b6b95650f243293033037f9a46ec4a7
