### ISSUE TITLE
When cherry picking and Pick (A) others commits disappear

### ISSUE THREAD

**Issue by AlejandroSanchez90** [NeogitOrg/neogit#1563]
### Description

when i use "l" > "o" select branch i want to cherry pick, then select commit, and hit "A" > "A" , i can see the commits in my branch, but the other commits disapear

before cherry picking
![image](https://github.com/user-attachments/assets/519104d3-3ab1-4e86-b2bd-d66eef32c686)

after
![image](https://github.com/user-attachments/assets/222622a8-55dc-4d26-ac94-ce8c320d1953)

### Neovim version

nvim 0.10.2

### Operating system and version

wsl 2

### Steps to reproduce

 use "l" > "o" select branch i want to cherry pick, then select commit, and hit "A" > "A"

### Actual behavior

it hides rest of commits after Pick commnd cherry picking

### Minimal config

```Lua
return {
	"NeogitOrg/neogit",
	event = "VeryLazy",
	dependencies = {
		"nvim-lua/plenary.nvim", -- required
		"sindrets/diffview.nvim", -- optional - Diff integration

		-- Only one of these is needed, not both.
		"ibhagwan/fzf-lua",
	},
	config = function()
		local neogit = require("neogit")
		neogit.setup({})

		local keymap = vim.keymap -- for conciseness
		keymap.set("n", "<leader>go", "<cmd>Neogit<cr>", { desc = "Open NeoGit" })
		keymap.set("n", "<leader>gf", "<cmd>Neogit fetch<cr>", { desc = "Fetch" })
		keymap.set("n", "<leader>gb", "<cmd>Neogit branch<cr>", { desc = "Branch" })
		keymap.set("n", "<leader>gg", "<cmd>Neogit commit<cr>", { desc = "Commit" })
		keymap.set("n", "<leader>gp", "<cmd>Neogit push<cr>", { desc = "Push" })
		keymap.set("n", "<leader>gs", "<cmd>FzfLua git_status<cr>", { desc = "Status" })

		keymap.set("n", "<leader>gdh", "<cmd>DiffviewFileHistory % --base=LOCAL<cr>", { desc = "File github history" })

		--DiffviewFileHistory % --base=LOCAL
	end,
}
```

**Comment by CKolkey** [comment]
Yeah, if theres a remote or upstream, with unmerged commits the "recent" section isn't shown. Instead you see whats unmerged or unpushed.
