### ISSUE TITLE
(Un)staging visually selected items fails

### ISSUE THREAD

**Issue by d-miketa** [NeogitOrg/neogit#187]
Selecting one or multiple files in the Unstaged section, and then pressing `s` to stage them, throws out the following error:
```
E5108: Error executing lua ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: ...nvim/site/pack/packer/start/neogit/lua/neogit/status.lua:391: bad argument #1 to 'ipairs' (table expected, got nil)
```

The same happens when attempting to unstage. Individual staging works.

**Comment by TimUntersberger** [comment]
Staging multiple files based on selection is not supported yet.

**Comment by lalitmee** [comment]
I think this feature is very interesting and it can be used sometimes to increase productivity.

Is there any plan for this feature to be developed?

**Comment by CKolkey** [comment]
This is now supported.
