### ISSUE TITLE
Feature request: git blame for whole buffer

### ISSUE THREAD

**Issue by timsofteng** [NeogitOrg/neogit#189]
Hello. Is it possible to implement git blame feature for all buffers lines?

**Comment by TimUntersberger** [comment]
Could be possible, but I don't know whether overlapping with features from gitsigns.nvim is a good idea.

**Comment by ericpubu** [comment]
@TimUntersberger well, the gitsigns.nvim feature only has current line blame, and most of the time, you'd like to see the blame on a chunk of code, even on the whole file, and having to move the cursor on each line is not the most optimal, also you can't compare multiple lines. So having a blame for the whole file, something like the temporal buffer vim-fugitive shows on Git blame, would be an amazing addition here! 

btw, amazing plugin! thanks for your work

**Comment by lewis6991** [comment]
What do you need to configure in regard to this? From what I can tell, fugitive has very little config and all of that can be done in lua anyway.

I get Lua plugins are great and all, but let's stop blindly making a Lua version of everything just because it's Lua. `Git blame` in fugitive is a super cool feature, and re-implementing that in Lua won't be easy, or worth it.

**Comment by ericpubu** [comment]
In my case, I'm using fugitive, alongside, with neogit and gitsings, mainly cause I use quite a lot the `Git blame` in fugitive, but for the rest of my git flow, I do enjoy more the default keybindings and usage with neogit.
I don't have an issue, having all of them, but I do try to remove "duplicate" behavior on the plugins I use, having a similar blame behavior in this plugin I might remove fugitive (even though is an amazing plugin by its own! but I don,t use any other feature ther).
But if it is not easy or worth implementing such a feature, I agree that having amazing vimscript plugins shouldn't be a blocker for anyone using lua configs

**Comment by emmanueltouzery** [comment]
if that helps, i wrote a simple plugin which also offers such a git blame.
https://github.com/emmanueltouzery/agitator.nvim

I prefer it to the one from fugitive, it's quite a lot more compact in terms of width on the screen.

**Comment by timsofteng** [comment]
> if that helps, i wrote a simple plugin which also offers such a git blame. https://github.com/emmanueltouzery/agitator.nvim
> 
> I prefer it to the one from fugitive, it's quite a lot more compact in terms of width on the screen.

Cool. I would see similar blame in `neogit`.
BTW looks like time machine from your plugin does exactly what `DiffviewFileHistlry` does from `Diffview` plugin.

**Comment by melkster** [comment]
I'm also looking to swap out (vim-fugitive)[https://github.com/tpope/vim-fugitive] for Neogit, and therefore think that an equivalent to fugitive's `:Git blame` for Neogit would be sweet :)

**Comment by ten3roberts** [comment]
Would [diffviews](https://github.com/sindrets/diffview.nvim) file history work for your case.

`:DiffviewFileHistory %` and gitsigns `current line blame` is what I use, depending on the size of blame I am doing

**Comment by Liverm0r** [comment]
@ten3roberts I just tried `DiffviewFileHistory` and that's awesome! It's even possible to select a line and then invoke `DiffviewFileHistory` — you will be able to see all the history of that piece. I didn't even dream of having something like this :)

**Comment by CKolkey** [comment]
I'd recommend using something like https://github.com/emmanueltouzery/agitator.nvim or https://github.com/FabijanZulj/blame.nvim to solve this problem. I have no plans to add this to Neogit, as it seems like others have done a fine job with it already :)
