### ISSUE TITLE
Support diff syntax highlighting in commit buffer

### ISSUE THREAD

**Issue by stasjok** [NeogitOrg/neogit#204]
When I use `-v` switch in git, diff section have syntax highlighting, but in neogit it commented out.

Also can I change default switches? For example I'd like `-v` to be enabled by default.

**Comment by TimUntersberger** [comment]
> When I use -v switch in git, diff section have syntax highlighting, but in neogit it commented out.

Basically you would like to have syntax highlighting for the diff output in the commit buffer?

> Also can I change default switches? For example I'd like -v to be enabled by default.

https://github.com/TimUntersberger/neogit/issues/80

**Comment by stasjok** [comment]
> Basically you would like to have syntax highlighting for the diff output in the commit buffer?
Yes. Usually I'm using -v when commiting (or `cvc` in fugitive), and I'd like to verify that I commit exactly what I wanted. With syntax highlighting it's easier.

**Comment by gegoune** [comment]
Did anything changed recently that would make highlighting in commit window working? I was just committing something and got surprised by highlights in there. @ten3roberts perhaps some of your recent work (thanks!)?

**Comment by ten3roberts** [comment]
I guess.

The commit now uses git for calling neovim to edit the commit, rather than neogit calling git commit with the full commit message which was entered by the user.

**Comment by gegoune** [comment]
In which case I think that issue can be closed.
