### ISSUE TITLE
Commit filetype gets reset to conf

### ISSUE THREAD

**Issue by gowep** [NeogitOrg/neogit#216]
### Description

When I write a commit message and I open telescope in this window - I use telescope for spellchecking - the filetype gets changed to conf after telescope closes. This does not happen with a normal gitcommit.

### Neovim version

NVIM v0.6.0-dev+279-g9d5d72c38

### Operating system and version

Arch Linux

### Steps to reproduce

Open commit message, open telescope in commit message.

### Expected behavior

Filetype remains as NeogitCommitMessage

### Actual behavior

Filetype becomes conf

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
      {
        "nvim-telescope/telescope.nvim",
  	requires = { {'nvim-lua/plenary.nvim'} },
	cmd = "Telescope"
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by TimUntersberger** [comment]
This issue might help you: https://github.com/TimUntersberger/neogit/issues/181#issuecomment-919013652

Do you have telescope set to lazy load?

**Comment by gowep** [comment]
Sorry I forgot to update to minimal config. Yes its set to lazy load and does not happen when not lazy loading.

**Comment by CKolkey** [comment]
Closing this - if it's still a problem, open a new issue.
