### ISSUE TITLE
Log Buffer

### ISSUE THREAD

**Issue by TimUntersberger** [NeogitOrg/neogit#22]
- [x] Checkout commit
- [x] revert commit (https://github.com/TimUntersberger/neogit/issues/22#issuecomment-898465278)
- [x] improve visual representation of log (https://github.com/TimUntersberger/neogit/issues/22#issuecomment-913260485)

**Comment by asymmetric** [comment]
I would like for the log buffer to re-apper after i've finished looking at a specific commit (I think magit works this way too).

So I would type <kbd>L</kbd>, find a commit, type <kbd>Enter</kbd>, type <kbd>q</kbd> when I'm done, and I'd be shown the log buffer again.

**Comment by TimUntersberger** [comment]
@asymmetric how about adding a seperate keybinding for that? Something like `Shift+Enter` or `Control+Enter`?

I have been thinking about introducing something similiar to hooks in magit for neogit, which would make something like this easy to introduce in user config.

**Comment by itmecho** [comment]
Would be cool to have a map to revert a commit from the list! Flow would be something like:

 `L` -> `l` -> move cursor to commit -> `r` or `R` etc -> results in `git revert <selected-commit>`

**Comment by JA-Bar** [comment]
Hello!, great plugin.

At the moment during log exploration (L->b or any other option), commits of one a feature branch and commits that occurred on the main branch appear to be at the same level.

In neogit:
![image](https://user-images.githubusercontent.com/57547764/132146044-dbec4235-7b99-48ad-9321-130daf0071b3.png)

Using `git log --oneline --decorate --graph --all`:
![image](https://user-images.githubusercontent.com/57547764/132146060-6c0cee2a-a3d4-4715-a1a7-511c740c325d.png)

Is there a way of showing them separated currently and I'm just missing an option?

Also, it would be a great addition if the log buffer showed branch locations!

**Comment by asymmetric** [comment]
> @asymmetric  how about adding a seperate keybinding for that? Something like Shift+Enter or Control+Enter?

@TimUntersberger I'd say that incurs more of a cognitive load than thinking of it as "navigating through a stack". In the stack metaphor, it just makes sense that `q` pops, so you'd have to type it a couple times to get back to where you want to be.

I would rather have a special keybinding to pop *everything* from the stack - that would actually be quite useful :)

**Comment by asymmetric** [comment]
I would like to filter logs affecting only one file, something like `git log src/foo.c`.
