### ISSUE TITLE
Unexpected behavior when deleting local and remote branch

### ISSUE THREAD

**Issue by wizard-28** [NeogitOrg/neogit#222]
### Description

Deleting local and remote branches produces unexpected behavior for me.

Similar to https://github.com/TimUntersberger/neogit/issues/168#issuecomment-879576750

I'm using SSH key with passphrase.

### Neovim version

```
NVIM v0.6.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Pop!_OS 20.04

### Steps to reproduce

1. Open Neogit
2. Try to delete local and remote branch using <kbd>b</kbd> + <kbd>D</kbd> 
3. See unexpected behavior.

### Expected behavior

Deal with the prompts asked by git in the command section.

Same way it's dealth with when pushing.
![img](https://0x0.st/-gB5.png)

### Actual behavior

![img](https://0x0.st/-gBd.png)

I can't type `yes`/`no` or answer any prompts, whole Neovim freezes.

Here's the command log
```bash
128 git push origin --delete remotes/origin/fix/-A (0.010 ms) [stderr 5]
  | Host key verification failed.^M
  | fatal: Could not read from remote repository.
  |
  | Please make sure you have the correct access rights
  | and the repository exists.
```

### Minimal config

```Lua
Done, same issue.
```

**Comment by TimUntersberger** [comment]
@wizard-28 does the new commit fix the problem for you?

**Comment by wizard-28** [comment]
No, it's still broken

**Comment by TimUntersberger** [comment]
@wizard-28 does it still freeze? What do you see now?

**Comment by sid-maddy** [comment]
@TimUntersberger, I think the last error is because Neogit doesn't handle branch names with slashes in them.
Specifically, because of [this branch name truncation logic](https://github.com/TimUntersberger/neogit/blob/master/lua/neogit/lib/git/branch.lua#L58)

**Comment by CKolkey** [comment]
I don't think this is an issue anymore, but feel free to reopen it if thats incorrect.
