### ISSUE TITLE
Error on exiting Neogit: No previous directory

### ISSUE THREAD

**Issue by kazhala** [NeogitOrg/neogit#226]
### Description

After commit 2e02df46e9cb0b80c1947149c773da50d4b53e01, neogit start showing error while exiting it. This also cause neogit not able to start again normally.

### Neovim version

NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

MacOS & Windows WSL2

### Steps to reproduce

1. `nvim -u minimal.lua`
2. `:Neogit kind=split`
3. `:q`

### Actual behavior

The screenshot below uses the minimal.lua.

![image](https://user-images.githubusercontent.com/43941510/136475909-345bd5fa-b8a8-4177-a9e6-0df474154465.png)

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by n3wborn** [comment]
Awesome, as usual; Thanks  !

**Comment by kazhala** [comment]
Thanks for the quick fix. Can confirm it's working as expected now.
