### ISSUE TITLE
Support customizing status buffer layout

### ISSUE THREAD

**Issue by TimUntersberger** [NeogitOrg/neogit#242]
### Discussed in https://github.com/TimUntersberger/neogit/discussions/241

<div type='discussions-op-text'>

<sup>Originally posted by **andreicorpo** October 29, 2021</sup>
I have a lot of stashes. And when I open Neogit see a list of them and it kinda gets confusing since I expect Neogit to be empty since I don't have any changes. Would it be possible to hide that section somehow?</div>

As a user you may want to hide sections that are irrelevant for your use case.

Edit:

> it would be great to be able to configure what sections are expanded by default

**Comment by sindrets** [comment]
In addition to being able to configure what sections are hidden, it would be great to be able to configure what sections are expanded by default. Like i.e. in Magit I think the "Recent commits", "Unpulled changes", and "Stashes" sections are closed by default. Unless that's what you meant by 'hide'?

**Comment by CKolkey** [comment]
This can be done.
