### ISSUE TITLE
Create pull request feature

### ISSUE THREAD

**Issue by timsofteng** [NeogitOrg/neogit#249]
**Is your feature request related to a problem? Please describe.**
It would be nice to have ability to create pull request in repo by opening tab in browser.

**Describe the solution you'd like**
Press some key in `Neogit` which will open page with pull request opening in browser.

**Additional context**
It works in lazygit by pressing `o` btn.
Super useful.

**Comment by CKolkey** [comment]
At this time I have every intention of keeping this agnostic to which git-site you are using. I think something like https://github.com/chrishrb/gx.nvim or the new `vim.ui.open()` api would better be suited for this.

**Comment by timsofteng** [comment]
@CKolkey may you provide an example please?

**Comment by CKolkey** [comment]
Haven't got one, sorry. But off the top of my head you could do something like
```lua
vim.ui.open = function()
  -- if the filetype is `NeogitStatus`, send the PR URI to get opened
end
```
