### ISSUE TITLE
Commit fails for directories with spaces

### ISSUE THREAD

**Issue by TC72** [NeogitOrg/neogit#257]
### Description

Commit doesn't work if the path to the git repository has a space.
The failure is due to the commit command using a path with a space to reference the NEOGIT_COMMIT_EDITMSG file.

```
git commit --file=/Users/tc72/Sites/my site/web-content/.git/NEOGIT_COMMIT_EDITMSG
```

### Neovim version

NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

macOS 12.0.1

### Steps to reproduce

1. stage a changed file
2. cc to commit
3. edit commit message and save with :x!
4. Confirm commit with Y

### Expected behavior

The changes should be committed.

### Actual behavior

An error is reported and the log shows:
```
  1 git commit --file=/Users/tc72/Sites/my site/web-content/.git/NEOGIT_COMMIT_EDITMSG  --  (6.490 ms) [stderr 1]
```

Copying the command and running it in a terminal manually shows the issue is because of the space in the path without escaping it or quoting the whole path.

### Minimal config

```Lua
Don't think this is an issue with my config.
```

**Comment by wizard-28** [comment]
I'm on Linux, and I face the same issue

**Comment by CKolkey** [comment]
Just tested this - seems to be working fine now. Feel free to reopen if needed.
