### ISSUE TITLE
Add files to `.gitignore` with a predefined key. 

### ISSUE THREAD

**Issue by rafamadriz** [NeogitOrg/neogit#260]
**Is your feature request related to a problem? Please describe.**

No, it's not related to a problem.

**Describe the solution you'd like**

It would be awesome to add files to `.gitignore` with some predefined key. When you open Neogit, there's a couple of predefined keys: `[s]` for `stage` or `[x]` for `discard`, etc. For adding files to `.gitignore` we could use the `[i]` key,   

**Describe alternatives you've considered**

None.

**Additional context**

None

**Comment by CKolkey** [comment]
theres an ignore popup
