### ISSUE TITLE
Support preview untracked files

### ISSUE THREAD

**Issue by thuan1412** [NeogitOrg/neogit#284]
**Is your feature request related to a problem? Please describe.**
I usually review my changes before adding them to the stage. However, neogit does not support previewing the untracked file. It would be like if I can view my untracked files inside the neogit window.

**Describe the solution you'd like**
Be able to preview/view the untracked files in the neogit window like `unstaged changes` and `staged changes` sections.

**Describe alternatives you've considered**
I have to open the untracked files and view them.

**Comment by CKolkey** [comment]
This works now :)
