### ISSUE TITLE
Git branch interactive list.

### ISSUE THREAD

**Issue by timsofteng** [NeogitOrg/neogit#289]
Would be cool to see `git branch` interactive list like in fugitive or lazygit to checkout or rename or delete or merge branch.
Really helpful feature.

**Comment by Strongleong** [comment]
Agree. It would be nice to have at least list of branches

**Comment by abusch** [comment]
I think that's what #307 does?

**Comment by Strongleong** [comment]
Almost. Still must type branch name when rebasing.

**Comment by CKolkey** [comment]
Not really sure what "interactive" means, but we now use telescope or `vim.ui.select()` to provide a fuzzy-finding interface for branches, so unless I'm mistaken, this is done.
