### ISSUE TITLE
Fugitive-like git commands

### ISSUE THREAD

**Issue by Strongleong** [NeogitOrg/neogit#293]
I'd like to have an ability to exec git commands with NeoVim command line

I like Neogit more than Fugitive's git screen, but I am really miss ability to just do `:G pull` or `:G checkout` or just ':G something`
I have a few custom git commands that I also can't do with Neogit

And I know that I can do `:!git <command>`, but with Fugitive it was more pleasant to do with auto completions and stuff

P. S. Sorry for bad English :sweat_smile:

**Comment by CKolkey** [comment]
While I appreciate the idea, this isn't on our roadmap. I'd recommend using fugitive for those kind of things :)
