### ISSUE TITLE
Neogit commit message window does not respect keyboat layout 

### ISSUE THREAD

**Issue by Strongleong** [NeogitOrg/neogit#297]
### Description

When I type commit message in Russian letters `б` and `ю` changes to `,` and `.` respectively.
If I try to copy-pase these letters it works

Must note that `б` and `,` physically located at the same key (so `ю` and `.`)

Sorry for bad English 

### Neovim version

NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui

### Operating system and version

Arch linux 5.17.9

### Steps to reproduce

1. create git repo
2. create file in that repo
3. open neogit
4. make commit
5. try to type letters `б` or `ю`

### Expected behavior

Letters `б` or `ю` shows up

### Actual behavior

Symbols `,` or `.` appears 

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by ten3roberts** [comment]
Are you using `Neovide` or a terminal.

I have noticed that neovide sometimes uses the raw HID keycode instead of the virtual keycode.

**Comment by Strongleong** [comment]
I use both and experienced this bug in terminal and neovide

**Comment by Strongleong** [comment]
I can't reproduce this issue no more, so I am closing this one
