### ISSUE TITLE
Standalone Fetch pop-up and Git logs with Diffview

### ISSUE THREAD

**Issue by asmodeus812** [NeogitOrg/neogit#299]
Hi, amazing work on that plugin so far, i was wondering about two different functionalities that can be added to further enhance neogit

- Fetch pop-up - similar to the other core type of pop-ups such as pull, pull, logs etc. One for fetch would (with some very basic customizable cmd options/args) be helpful as well. Usually instead of going to all available pop-ups from neogit status (the main one). I have bound a lot of them directly to mnemonics such as 
     * <leader>gp -     require("neogit.popups.pull").create()
     * <leader>gP -     require("neogit.popups.push").create()
     * similarly for the other available popups that are often used

- Logs - on an unrelated note to the popup, now that DiffviewFileHistory supports a very customizable git log, i thought that might be used in the diffview integration part in neogit. As of now the basic logs window is cool and all, but once you go to review the commit, the default diff view even though very nice (very thankful that it is not just a dump of !git log *cough fugitive*, instead you can act on and toggle file diffs etc), is somewhat limited in what it can display (side by side, filter files etc - something that diffview has pretty much solved already) Credits to @sindrets  for the amazing work on that.

**Comment by TimUntersberger** [comment]
Hey, I currently don't have a lot of free time, so I don't know how long it would take me to implement this. I can guide you through the codebase, if you want to add this yourself.

**Comment by CKolkey** [comment]
There is now a fetch popup and a more loggy log buffer.
