### ISSUE TITLE
Open Neogit for git repository of current buffer

### ISSUE THREAD

**Issue by alexander-born** [NeogitOrg/neogit#305]
**Is your feature request related to a problem? Please describe.**
While editing a file which is in another git repository compared to my cwd I want to open `:Neogit` to show the status of the repository of my current buffer

**Describe the solution you'd like**
In fugitive the git repository is automatically chosen for the current buffer.
This is such a nice feature and would be awesome to be integrated here as well.

**Comment by lmburns** [comment]
I agree, this would be much more convenient. But you might be able to create a command like this:
```lua
    vim.api.nvim_create_user_command(
        "NeogitCWD",
        function()
            require("neogit").open({cwd = vim.fn.expand("%:p:h")})
        end,
        {nargs = 0}
    )
```

**Comment by festeh** [comment]
Thanks for the tip! Unfortunately, for me setting `cwd` argument led to a side-effect of changing working directory globally  for some plugins, so this command worked for me better (I use a tab mode).

```
vim.api.nvim_create_user_command(
        "Git",
        function()
            local cwd = vim.fn.expand('%:p:h')
            require("neogit").open()
            vim.cmd(":lcd" .. cwd)
        end,
        {nargs = 0}
)

```
