### ISSUE TITLE
Delete branch not working

### ISSUE THREAD

**Issue by Danielwsx64** [NeogitOrg/neogit#308]
### Description

When I try to delete a branch (local or local+remote) nothing happens. Not even an error message.

### Neovim version

NVIM v0.8.0-dev+265-g12f45fd69
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system and version

Ubuntu 20.04.4 LTS

### Steps to reproduce

1. Open nvim in git folder with multiple branches
1.   `:Neogit'
1. Try to delete a local branch using `b` + `d`
1. Choose a branch to delete

### Expected behavior

The selected branch deleted

### Actual behavior

Nothing happens, not even an error message, the branch isn't deleted.

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by kessejones** [comment]
After trying to delete a branch check the command history if the command `git branch -d` has the correct branch name

**Comment by ten3roberts** [comment]
@CKolkey I know you've been tackling branches recently.

This issus may be of relevance

**Comment by CKolkey** [comment]
This issue is probably defunct - i've pretty much rewritten all of the branch deletion logic since this was opened.
