### ISSUE TITLE
Add interactive rebase feature

### ISSUE THREAD

**Issue by sotte** [NeogitOrg/neogit#317]
Add magit-like interactive rebase feature.

* reorder commits
* squash
* fixups
* reword
* deleting commits
* continue/abort merge conflicts etc

Reference:
* https://magit.vc/manual/magit/Rebasing.html
* Demo of the magit rebase workflow: https://systemcrafters.net/mastering-git-with-magit/using-interactive-rebase/

**Comment by kessejones** [comment]
Hello
I haven't opened a PR yet, but I've been doing some testing on this implementation and I've arrived at a version that seems to be working.
My implementation is simple but I think it's a start for this functionality.

**Comment by sotte** [comment]
@kessejones I'm more than happy to test it. Just open a PR.

**Comment by ten3roberts** [comment]
Great. This feature alone is what still keeps me with a foot on `vim-fugitive`

**Comment by ten3roberts** [comment]
As the related PR is merge, should this issue be closed.

**Comment by TimUntersberger** [comment]
@sotte said he is going to test the PR, whether it fits his requirements if I remember correctly. Does the PR solve your issue?

**Comment by sotte** [comment]
Hey, I gave it a quick test. There were some "surprises" ;) I haven't had the chance to do a deep dive though.

I think some ppl should test it more and then we can merge it.

(I won't be in front of the computer for the next week.)

**Comment by ten3roberts** [comment]
While this issue is being worked on, I thought it may be worth to fix some other issues with rebasing.

When doing `rp` rebase onto master, you have to manually refresh using `<C-r>` to see the merge conflict. There is also no way to continue the rebase by opening a commit popup prepopulated with the existing commit, such as `git rebase --continue` does it. `rr` would be a great binding for this, which is what fugitive uses, and is in the same fashion as `cc`

**Comment by ten3roberts** [comment]
Are there any plans for continuing rebase and rebase continue work?

**Comment by ten3roberts** [comment]
Hey @TimUntersberger I have opened a pr which fixes the above mentioned issues

**Comment by gegoune** [comment]
@ten3roberts Is there a way to pass in `--committer-date-is-author-date` to rebase command?

**Comment by ten3roberts** [comment]
No but it could be made into a switch.

How does magit handle it?

**Comment by gegoune** [comment]
I am not sure, never used emacs. :-)

**Comment by sotte** [comment]
I think this feature can be closed. neogit supports this now.
