### ISSUE TITLE
Customisation of CommitView highlighting doesn't work properly

### ISSUE THREAD

**Issue by Nexmean** [NeogitOrg/neogit#318]
### Description

I am using NvChad with [custom config](https://github.com/Nexmean/dotfiles/tree/main/nvim/lua/custom). It is using [base46](https://github.com/NvChad/base46) for theming. I did [setup](https://github.com/Nexmean/dotfiles/blob/main/nvim/lua/custom/ui/hl_add.lua) it for highlighting Neogit in colors of theme, so via `:lua =vim.api.nvim_get_hl_by_name(hl_name, true)` I checked that base46 works fine. But when I use Neogit I noticed that highlighting in `NeogitStatus` buffer differs from `NeogitCommitView`:
![Снимок экрана 2022-07-17 в 23 56 56](https://user-images.githubusercontent.com/3821520/179424455-e72c0a5c-865b-49bb-aa49-873ff2055b36.png)
![Снимок экрана 2022-07-17 в 23 58 07](https://user-images.githubusercontent.com/3821520/179424500-a05eb390-cf6e-4af8-9f44-43e675c8c59c.png)
First is from `NeogitStatus`, second is from `NeogitCommitView`.

Then I tried to play with `:hi` command for debug and noticed that changing of [his described in README.md](https://github.com/TimUntersberger/neogit/blob/master/README.md#contextual-highlighting) doesn't affect `NeogitCommitView` buffer.

### Neovim version

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled  _nixbld5

Features: +acl +iconv +tui

### Operating system and version

macOS 12.4

### Steps to reproduce

- `:hi NeogitDiffContextHighlight guibg=#000000 guifb=#ffffff`
- `:hi NeogitDiffAddHighlight guibg=#000000 guifb=#ffffff` 
- `:hi NeogitDiffDeleteHighlight guibg=#000000 guifb=#ffffff`

### Expected behavior

`NeogitCommitView` buffer is affected by `:hi` command.

### Actual behavior

`NeogitCommitView` stay as it was.

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by CKolkey** [comment]
Feel free to reopen this if this is still an issue.
