### ISSUE TITLE
Stash index Zi show error

### ISSUE THREAD

**Issue by tuanha168** [NeogitOrg/neogit#322]
### Description

when i try to stash 1 file when i have other files modified,
when just only 1 file modified that i can use `Zz` and stash it without any error, but `Zi` still have the same error

### Neovim version

NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

### Operating system and version

macOS M1 Montery 12.4

### Steps to reproduce

open neogit status
stash unstaged changes with index ( `Z` `i` )

### Expected behavior

stash only file i have cursor on

### Actual behavior

Error

![image](https://user-images.githubusercontent.com/71129995/181195075-58ed6b0a-9594-453e-8d29-51682a2091bc.png)

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by kskarthik** [comment]
@TimUntersberger i have also observed when pressing `x` key on a stash, It is prompting with Discard confirmation. but, opting "Yes" does not delete it. is it working as expected for you?
