### ISSUE TITLE
Request for customizable highlights for not-highlighted hunks

### ISSUE THREAD

**Issue by mizlan** [NeogitOrg/neogit#330]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'd like a set of highlight groups to control the highlights of the hunks that are not currently highlighted. For example, I'd like to dim the context lines much more than normal. However, I can't seem to find even where those highlights are applied in the source code 😅

**Describe alternatives you've considered**
Changing DiffAdd/DiffDelete etc but this is not a great solution.

**Additional context**
\-

**Comment by mizlan** [comment]
It seems its a problem with not documented NeogitDiff{Add,Delete,...} (minus the highlight).

Think this resolves #318 as well. Except that NeogitDiffContext doesn't seem to exist (since it's the default Normal text). But that should be changed easily enough by elaborating on the following conditional:

https://github.com/TimUntersberger/neogit/blob/f9cb5a4ad10288be568129fb71de2d7e559adad2/lua/neogit/status.lua#L182-L186

**Comment by mizlan** [comment]
I'd also like for there to be Neogit*Highlight as well as Neogit (not highlighted) in the commit view buffer, as far as I can tell this is the way it works in Emacs magit (i.e., have the same UI where the hunk under cursor uses the other set of highlights)

**Comment by mizlan** [comment]
I would gladly make a PR, if I could figure out why the current commit view hunk text fg turns blue. (Can't locate that in the code)

**Comment by nullchilly** [comment]
@mizlan You missed the second CursorMoved event here, I guess?

https://github.com/TimUntersberger/neogit/blob/f9cb5a4ad10288be568129fb71de2d7e559adad2/lua/neogit/buffers/commit_view/init.lua#L69

**Comment by mizlan** [comment]
Oopsie haha. Didn't catch that even though I scoured the codebase for "hl"/"highlight". I'll try to see what's up.

**Comment by nullchilly** [comment]
Yeah it's just 

https://github.com/TimUntersberger/neogit/blob/f9cb5a4ad10288be568129fb71de2d7e559adad2/lua/neogit/buffers/commit_view/init.lua#L77

This is how it turned blue

```vim
:hi Directory guifg=#cdd6f4
```

**Comment by mizlan** [comment]
Yeah, changing that to a Neogit* highlight group is an important part of it, then we'd have to have new context/add/delete groups for inactive/active "hunks" as well as probably another hlgroup for the info at the top, which may not be suitable for inactive/active context hlgroup.

**Comment by CKolkey** [comment]
Feel free to reopen this if this is still an issue.
