### ISSUE TITLE
change dir/repo reset race condition resulting in empty NeogitStatus view

### ISSUE THREAD

**Issue by cfal** [NeogitOrg/neogit#334]
### Description

half the time i open neogit with `neogit.open({ cwd = '/my/repo/path' })`, the view is empty and doesn't show staged files, because of a race condition.

1. `status.create` is called in `neogit.open` which results in a `cd` call: https://github.com/TimUntersberger/neogit/blob/dd383b74967ca3169329d981cbd4e06e60e992e9/lua/neogit/status.lua#L917
2. the `DirChanged` hook to call `dispatch_reset` is executed https://github.com/TimUntersberger/neogit/blob/06e986fab0d0c31ba981b9f21c712dc72b3d237f/plugin/neogit.vim#L24
3. `M.repo:update_status()` is called which updates the object with the new data: https://github.com/TimUntersberger/neogit/blob/06e986fab0d0c31ba981b9f21c712dc72b3d237f/lua/neogit/lib/git/status.lua#L104
4. AT THE SAME TIME, the `dispatch_reset` async operation fires, replacing `M:repo` with a brand new object https://github.com/TimUntersberger/neogit/blob/06e986fab0d0c31ba981b9f21c712dc72b3d237f/lua/neogit/status.lua#L473
5. by the time `update_status` completes, M:repo is now an empty object that has no data, and `render_header()` calls renders a completely empty view

### Neovim version

N/A

### Operating system and version

Ubuntu

### Steps to reproduce

N/A

### Actual behavior

N/A

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by ten3roberts** [comment]
This would be fixable with a simple check which ignores dispatch_reset if the status buffer is about to be filled, indicated via a flag.

The question however is if it is neccesary to background refresh the whole status buffer each time the cwd changes, but rather flag it as out of date so that the next time is is opened, or focused, and `cwd == nil`, the status buffer is refreshed,

I have myself noticed noticeable hangups when saving buffers and having the refresh autocommands fire, taking a bit because I have a large diff
