### ISSUE TITLE
Use native vim folds for sections and hunks

### ISSUE THREAD

**Issue by austinliuigi** [NeogitOrg/neogit#344]
**Is your feature request related to a problem? Please describe.**

As of now, the primary function we have for opening/closing folds is toggle (default `<Tab>`). It would be nice if there were also bindings for opening/closing the current fold which behave similar to vim's own `zo` and `zc`. We would then be able to close a higher level fold that we are nested in without needing to jump to its line.

**Additional Context**

So far, the only thing that makes this plugin a bit unintuitive/clunky for me personally is the vertical navigation. I think that treating the folds more like vim folds would greatly aid in that. Then again, I have never used magit before so my perspective is a bit narrow.

**Comment by CKolkey** [comment]
The `nightly` branch contains a rewrite of all the folding logic, including using native folds :)

One caveat: On the status buffer we lazily load diffs for performance reasons. This means you need to open the fold with `<tab>` at least once to run the callback function. Afterwords, it's a normal fold.
