### ISSUE TITLE
no blank line between commit message and body

### ISSUE THREAD

**Issue by aleprovencio** [NeogitOrg/neogit#359]
### Description

When `neogit`'s commit viewport window shows up, it is not placing a blank line between the commit message to be written and the default body comments below with git instructions.

Unless you put a blank line manually (or delete the commented body), logs will get pretty messed up.

### Neovim version

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

archlinux

### Steps to reproduce

1. stage files and commit using neogit
2. window appears without a blank line below the cursor

### Actual behavior

This causes bad commit messages

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by anachronic** [comment]
Same thing is happening to me. I took a look and it seems like it has to do with setting `verbose = true` in my `.gitconfig` is the culprit. If I set verbose back to default it doesn't happen anymore. I know this is not a solution, but maybe it's worth knowing.

It also looks like adding an empty line does not help 😭

Here's a representation of the problem 👇

![image](https://user-images.githubusercontent.com/3452930/193427950-bca69bb2-ebb6-41e5-8305-0a6f8af2e8e5.png)

**Comment by aleprovencio** [comment]
you are right @anachronic, 
while putting a blank line improves the log somehow, those diff messages will still mess the message body

**Comment by sstark** [comment]
When doing a commit using git on the command line and with Neogit, I can not see any notable difference in the  `.git/COMMIT_EDITMSG` that is written when saving the commit message. So whatever goes wrong, goes wrong afterwards.

**Comment by asymmetric** [comment]
I also experience this, and it led me to stop using NeoGit for committing.

I also have `commit.verbose = true` in my config.

**Comment by CKolkey** [comment]
Feel free to reopen this if it's still an issue.

**Comment by asymmetric** [comment]
@CKolkey has this been fixed in a recent commit?

**Comment by CKolkey** [comment]
Not sure, but enough things have changed since then that I'm closing old issues. If its still a problem, by all means, let me know :)
