### ISSUE TITLE
rewording while having staged changes might break the working repositories cache

### ISSUE THREAD

**Issue by ttytm** [NeogitOrg/neogit#367]
### Description

I discovered another bug while working on #366

This is tested on the current main branch efb9a7e81a1adf35a30d5ea72e412fc5b2d21c98

Might be also true for other extending and amending.

### Neovim version

v0.8

### Operating system and version

linux

### Steps to reproduce

I cannot give a 100% step by step reconstitution, but it eventually breaks the repo when rewording while having staged files.

### Expected behavior

An easy fix would be to unstage all changes prior to starting it. Maybe including a confirmation prompt when starting reword with staged changes. Or going full on with an automation to restore the staged state after a reword action.

### Actual behavior

Further default actions to git repository become hardly possible due to errors.
`128 git --no-optional-locks ls-files --others --cached --modified --deleted --full-name <foldername> (0.002 ms) [stderr 2]`

### Minimal config

```Lua
Just neogit
```

**Comment by CKolkey** [comment]
Feel free to reopen this if it's still a problem.
