### ISSUE TITLE
neovim v0.8: Cannot commit, tries to access unrelated file in /usr/share and shows server error.

### ISSUE THREAD

**Issue by oddlama** [NeogitOrg/neogit#369]
### Description

I've installed Neogit without changing any options. I can also commit just fine by using `git commit` on the command line, but neogit completely fails. See below for what happens.

### Neovim version

NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/x86_64-pc-linux-gnu-gcc -mabm -madx -maes -mavx -mavx2 -mbmi -mbmi2 -mcx16 -mf16c -mfma -mfsgsbase -mfxsr -mlzcnt -mmmx -mmovbe -mpclmul -mpopcnt -mprfchw -mrdrnd -mrdseed -msahf -msse -msse2 -msse3 -msse4.1 -msse4.2 -mssse3 -mxsave -mxsavec -mxsaveopt --param=l1-cache-line-size=64 --param=l1-cache-size=32 -O2 -pipe -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/var/tmp/portage/app-editors/neovim-0.8.0-r1/work/neovim-0.8.0_build/cmake.config -I/var/tmp/portage/app-editors/neovim-0.8.0-r1/work/neovim-0.8.0/src -I/usr/include -I/var/tmp/portage/app-editors/neovim-0.8.0-r1/work/neovim-0.8.0_build/src/nvim/auto -I/var/tmp/portage/app-editors/neovim-0.8.0-r1/work/neovim-0.8.0_build/include
Compiled by portage@localhost

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "/etc/vim/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Operating system and version

Gentoo

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. `:Neogit`
3. `cc` (fails)
4. `:messages`

### Actual behavior

![image](https://user-images.githubusercontent.com/31919558/195110914-bbc8a563-79ff-489b-8dfa-f8a017dccb94.png)

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by vinibispo** [comment]
I tried the exact version you are using, and it works successfully.
Can you update neogit and try again?

**Comment by CKolkey** [comment]
Feel free to reopen this if this is still an issue.
