### ISSUE TITLE
autocmds are not firing for Neogit's COMMIT_EDITMSG buffers

### ISSUE THREAD

**Issue by cultab** [NeogitOrg/neogit#376]
### Description

When using the plugin [rhysd/committia.vim](https://github.com/rhysd/committia.vim), opening a buffer with the name COMMIT_EDITMSG fires off an autocmd that makes commitia open extra windows. This autocmd does not fire in Neogit's commit buffers, unless you run `:e `  after they have opened.

Below is the relevant autocmd from committia.
```vim
let g:committia_open_only_vim_starting = get(g:, 'committia_open_only_vim_starting', 1)

function! s:should_open(ft) abort
    " NOTE: I put an echo and a syntax error (yes just 'asdkjhvuf') here to bring up `:messages` and an error
    " to check if the autocmd was running when trying to find a solution
    return &ft ==# a:ft && (!g:committia_open_only_vim_starting || has('vim_starting')) && !exists('b:committia_opened')
endfunction

augroup plugin-committia
    autocmd!
    autocmd BufReadPost COMMIT_EDITMSG,MERGE_MSG if s:should_open('gitcommit') | call committia#open('git') | endif

    " ... Add other VCSs' commit editor filetypes
augroup END
```

Relevant issue also exists here: https://github.com/rhysd/committia.vim/issues/59

I tried playing around with committia's autocmd's event, filename and Neogit's popup's filetype with no real results. So I thought I'd open an issue.

### Neovim version

NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by void-buildslave@a-fsn-de

Features: +acl +iconv +tui

### Operating system and version

void

### Steps to reproduce

1. Install both neogit and commitia.
2. Set g:commitia_open_only_vim_starting=0 in your config (otherwise it's expected to not work)
3. Open Neogit and attempt to commit a change.
4. See that commitia's windows did not open (and that the autocmd did not fire).

### Expected behavior

Autocmd fires and commitia works.

### Actual behavior

Autocmd does not fire.

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
      { "rhysd/committia.vim" },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()

vim.g.committia_open_only_vim_starting = 0 -- to enable starting committia even when vim is not instantly entering into a commit buffer
```

**Comment by ten3roberts** [comment]
Can you confirm if
`autocmd! BufReadPost * echoerr "Buffer opened"`

works at all?

It is not firing for me when opening buffers using telescope or similar, and only when doing `:e file`

Seems to be because they are using the lua api and not triggering the BufReadPost. If that is the case, it seems to be an issue with telescope as well and not just neogit.

Otherwise, using `autocmd FileType NeogitCommitMessage ...` could work

NVIM v0.9.0-dev-202+g19dab2ead                                                                                                                                                
Build type: RelWithDebInfo                                                                                                                                                    
LuaJIT 2.1.0-beta3

**Comment by cultab** [comment]
> Can you confirm if
> `autocmd! BufReadPost * echoerr "Buffer opened"`
>
>works at all?
>
>It is not firing for me when opening buffers using telescope or similar, and only when doing :e file

Same here, it's only firing with `e: file`.

**Comment by gegoune** [comment]
Not sure if that's related but might be and might be the reason for this issue as well (will open separate issue if it's not). 

It seems that my autocommand to start terminal windows in insert mode ('startinsert') gets triggered for Neogit window (new tab). It starts in insert mode, which obviously makes no sense.

**Comment by CKolkey** [comment]
Feel free to reopen this if this is still an issue.
