### ISSUE TITLE
Unable to stage a hunk

### ISSUE THREAD

**Issue by hovnatan** [NeogitOrg/neogit#395]
### Description

I get error when trying to stage a hunk

    > git --no-pager -c color.ui=always --no-optional-locks apply --cached
    Command running for: 1999.21 ms

### Neovim version

NVIM v0.8.0-1210-gd367ed9b2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system and version

Ubuntu 22.04

### Steps to reproduce

NA

### Actual behavior

NA

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by Mange** [comment]
I have the same issue. Actually, I even get hanging processes that never finishes until I kill them or exit neovim.

I've found processes to kill which have been alive for days before I noticed this problem and I hadn't restarted neovim.

I can stash hunks via other Git integrations (like `gitsigns`).

**Comment by vheon** [comment]
@ten3roberts @TimUntersberger any updates on this?

**Comment by ten3roberts** [comment]
Is this when staging any kind of hunk, in any repo, or a specific one?

Will soon push some changes which will allow better output in the console window, as other commands, e.g; git commit can be running for a long time if the user newer closes the commit buffer etc.

**Comment by vheon** [comment]
I have this in any repo in any hunk

**Comment by ten3roberts** [comment]
Is it any different on https://github.com/TimUntersberger/neogit/tree/dev?

**Comment by CKolkey** [comment]
Feel free to reopen this if this is still an issue.

**Comment by CarlosMed** [comment]
So this is still an issue actually. It seems like it goes hand-in-hand with #691.

Steps to produce:
1. Open nvim inside a project where git is initialized that's not the root folder.
> In my case I would nvim open `dotfiles/.config/nvim`. But the root folder is the `dotfiles`
2. Open up `neogit`
2. Try hunk stashing a change.
3. I get an error saying:
```
git --no-pager -c color.ui=always --no-optional-locks apply --cached:
    error: packages/common/.config/nvim/../../../mac/Brewfile: does not exist in index

Open the console for details
Git Error (1), press $ to see the git command history
```

What fixes the issue is opening nvim on the root folder where git is initialized. In my case, that's the `dotfiles/` folder. If you need more info let me know. I don't mind helping out the most I can.

**Comment by ten3roberts** [comment]
I made this into a new issue as it seems to be a different cause than this one :)

I managed to replicate and then fix it on my end. Could you try #901 and see if it also fixes it for you?
