### ISSUE TITLE
Use git commit file type for commits

### ISSUE THREAD

**Issue by bagel897** [NeogitOrg/neogit#405]
**Is your feature request related to a problem? Please describe.**
Neovim has a git commit file type. Several plugins, like cmp-git use this. However, neogit uses its own git file type, preventing cmp-git and others from working.

**Describe the solution you'd like**

Neogit should use the built-in file type 
**Describe alternatives you've considered**
Adjust other plugins to use the neogit type. This seems inefficient.

**Comment by gegoune** [comment]
nvim-treesitter just merged in `gitcommit` parser, https://github.com/nvim-treesitter/nvim-treesitter/pull/3855.

@TimUntersberger what was the original intention of introducing specific filetype rather than using `gitcommit`?

**Comment by vinibispo** [comment]
> **Is your feature request related to a problem? Please describe.** Neovim has a git commit file type. Several plugins, like cmp-git use this. However, neogit uses its own git file type, preventing cmp-git and others from working.
> 
> **Describe the solution you'd like**
> 
> Neogit should use the built-in file type **Describe alternatives you've considered** Adjust other plugins to use the neogit type. This seems inefficient.
I agree with you. I looked at all code, and no part really needs the NeogitCommitMessage filetype.
I'll create a PR turning it back to gitcommit filetype.

**Comment by chrisgrieser** [comment]
I agree. also, until the PR is merged, you can use this autocmd to basically fix it yourself, to get the benefits of gitcommit treesitter parser

```lua
vim.api.nvim_create_augroup("neogit-additions", {})
vim.api.nvim_create_autocmd("FileType", {
		group = "neogit-additions",
		pattern = "NeogitCommitMessage";
		command = "silent! set filetype=gitcommit",
})
```

**Comment by CKolkey** [comment]
We've enabled the treesitter parsers for `gitcommit` and `git_rebase` if they are present on the users system. Beyond that, I see value in keeping the filetypes as they are.

**Comment by gegoune** [comment]
Out of interest. What value does it have over plain `gitcommit`?

**Comment by CKolkey** [comment]
It's mostly in terms of being a good citizen. People can customize their neogit experience without stepping on normal git stuff, and conversely we can modify the experience without it impacting normal git stuff.
