### ISSUE TITLE
When git commit from the worktree, neogit window shows the main directory

### ISSUE THREAD

**Issue by D00mch** [NeogitOrg/neogit#409]
### Description

When you open vim with the path of the [worktree](https://git-scm.com/docs/git-worktree) and make a commit, neogit window switches to the state of the initial folder (more details in `steps to reproduce`).

![Screen Recording 2022-12-10 at 12 33 33](https://user-images.githubusercontent.com/14236531/206844045-bad2e81c-ef90-44f6-9f9b-a2d61eb6aad3.gif)

### Neovim version

NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local
Features: +acl +iconv +tui

### Operating system and version

macOS 13.0

### Example with the current repo:
1. `git clone /Users/m1/IdeaProjects/vim/neogit/README.md`;
2. `cd neogit`;
3. `git worktree add -b emergency-fix ../temp master`;
4. `vim ../temp/README.md`;
5. Make changes to the file, open neogit and make a commit;
6. In the neogit window you don't see your commit.

### One thing I noticed. It works if you do it like this:
1. same as above
2. same as above
3. same as above
4. `vim .`;
5. Open directory for the worktree. Inside vim: `:e ../temp/README.md`;
7. Set current directory as root: `:cd %:p:h<CR>`;
8. Make changes to the file, open neogit and make a commit;

### Expected behavior

Neogit state should not be switched.

### Actual behavior

Neogit state switched.

### Minimal config

```Lua
any config
```

**Comment by lalitmee** [comment]
@D00mch , this is happening for me too but in a different way. 

For me it shows the branch from where I have created the worktree after committing in the worktree's branch and then I will close the `neogit` popup and then open `neogit` again. Then it shows the branch in which I have committed.

It started happening recently around 1 month. Not sure though.
