### ISSUE TITLE
log.showSignature breaks log parsing

### ISSUE THREAD

**Issue by swsnr** [NeogitOrg/neogit#422]
### Description

If `log.showSignature` is enabled in git config, neogit fails to parse logs correctly (see below)

I wanted to make a pull request right away, but I'm opening a bug ticket first, because I'm unsure how to fix this.  Basically I see three different approaches:

1. Always pass `--no-show-signature`.  That'd be easiest, but I don't know if this could break Git compatibility (I don't know which version introduced that flag, and which version neogit aims to support).
2. Properly parse the signatures out of logging, and somehow include them in the output; this seems rather complex, because the signature information isn't exactly well-formatted, depends on the type of the signature, etc.  This would also require a new UI to show signatures somehow.
3. Allow to pass additional flags per command in `setup {}`.  This would be a flexible approach, which would conveniently address similar issues in future, but it could also introduce new issues (e.g. users specifying flags incompatible with neogit's parsing code).

I tried to find out whether 3) is already possible in neogit, but it doesn't look like it is.

What would be a proper fix here?

Note that I'd rather not like to turn of showSignature globally, because I work with signed commits a lot, and would like to see signature information in `git log` and `git show` on command line.

### Neovim version

NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Operating system and version

Arch Linux

### Steps to reproduce

1. `git` config log.showSignature true`
5. `:Neogit<cr>` in any repository; ideally one which includes signed commits.

### Expected behavior

Preferably neogit shows signatures correctly, or ignores them at least.

### Actual behavior

Neogit parses the signature lines as if they were dedicated commits.  In a repo with signatures `git log --format=oneline` isn't actually one line, but instead includes the signature upfront.

```console
$ git l --format=oneline
* b893f44 Good "git" signature for sebastian@swsnr.de with ED25519 key SHA256:xBUrqiiYS+mY5fCndm8Ye+SDU3Gr578hRbUL7ZzHbiY
| Configure burn my windows extension
```

Note that the signature isn't necessarily just one additional line as in the above example; for commits signed with gpg or smime certificates git includes more lines with information about whether the GPG key or certificate is trusted, and also which CA signed the smime certificate (I can give you an example if need be, but only privately, since I only have SMime signing set up for work, and that's not something I can share publicly).

Neogit renders the signature information completely:

```
Hint: [<tab>] toggle diff | [s]tage | [u]nstage | [x] discard | [c]ommit | [?] more help

Head: main Good "git" signature for sebastian@swsnr.de with ED25519 key SHA256:xBUrqiiYS+mY5fCndm8Ye+SDU3Gr578hRbUL7ZzHbiY
Push: origin/main Good "git" signature for sebastian@swsnr.de with ED25519 key SHA256:xBUrqiiYS+mY5fCndm8Ye+SDU3Gr578hRbUL7ZzHbiY

Recent commits (20)
b893f44 Good "git" signature for sebastian@swsnr.de with ED25519 key SHA256:xBUrqiiYS+mY5fCndm8Ye+SDU3Gr578hRbUL7ZzHbiY
Configure burn my windows extension
f1191e6 Good "git" signature for sebastian@swsnr.de with ED25519 key SHA256:xBUrqiiYS+mY5fCndm8Ye+SDU3Gr578hRbUL7ZzHbiY
Enable flypie extension
37bccbc Good "git" signature for sebastian@swsnr.de with ED25519 key SHA256:xBUrqiiYS+mY5fCndm8Ye+SDU3Gr578hRbUL7ZzHbiY
Install gst pipewire for screen recordings
319390a Good "git" signature for sebastian@swsnr.de with ED25519 key SHA256:xBUrqiiYS+mY5fCndm8Ye+SDU3Gr578hRbUL7ZzHbiY
Fix formatting
90fb2e4 Good "git" signature for sebastian@swsnr.de with ED25519 key SHA256:xBUrqiiYS+mY5fCndm8Ye+SDU3Gr578hRbUL7ZzHbiY
Install fly-pie extension
f83273d Good "git" signature for sebastian@swsnr.de with ED25519 key SHA256:xBUrqiiYS+mY5fCndm8Ye+SDU3Gr578hRbUL7ZzHbiY
Update flatpak overrides and user remotes
12984eb Good "git" signature for sebastian@swsnr.de with ED25519 key SHA256:xBUrqiiYS+mY5fCndm8Ye+SDU3Gr578hRbUL7ZzHbiY
Track more notes about plugins
64354d3 Good "git" signature for sebastian@swsnr.de with ED25519 key SHA256:xBUrqiiYS+mY5fCndm8Ye+SDU3Gr578hRbUL7ZzHbiY
Install nodejs for treesitter
8a2c67a Good "git" signature for sebastian@swsnr.de with ED25519 key SHA256:xBUrqiiYS+mY5fCndm8Ye+SDU3Gr578hRbUL7ZzHbiY
Automatically add keys to ssh agent
e8e3d20 Good "git" signature for sebastian@swsnr.de with ED25519 key SHA256:xBUrqiiYS+mY5fCndm8Ye+SDU3Gr578hRbUL7ZzHbiY
Add new UI plugins to nvim
```

This breaks various other things, e.g. pressing Enter on any message line above triggers an error.

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by CKolkey** [comment]
Feel free to reopen this if it's still an issue.
