### ISSUE TITLE
feat: diffview for range in log

### ISSUE THREAD

**Issue by Fabian-programmer** [NeogitOrg/neogit#425]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I have to get insights of a range of commits.
When working with small/atomic commits, several commits represent a substantial change.
To get an overview of that substiantial change a display of a range of commits is needed

**Describe the solution you'd like**

1. In visual mode select commits:
![grafik](https://user-images.githubusercontent.com/65787013/211011650-35f0d8a9-8b3f-41e1-8be0-21b93529cf76.png)

2. Press d

3. sth like this happens: `:DiffviewOpen 947811c..2f3e3e4 <CR>`

**Describe alternatives you've considered**
My alternative would be to write my own keymapping, but then nobody would profit from it :)

**Additional context**
It would be also nice to have this available for branches.

**Comment by Fabian-programmer** [comment]
Quick&dirty autocmd implementation.

```
local function commit_range()
  local first_commit_line = string.gsub(vim.fn.getline('v'), '*', '')
  local second_commit_line = string.gsub(vim.fn.getline('.'), '*', '')

  local first_commit = vim.split(first_commit_line, '%s+')[2]
  local second_commit = vim.split(second_commit_line, '%s+')[2]

  local range = first_commit .. ".." .. second_commit

  return range
end

vim.api.nvim_create_autocmd("FileType", {
  pattern = {
    "NeogitLogView",
  },
  callback = function(event)
    vim.keymap.set("v", "d", function ()
      vim.api.nvim_command("DiffviewOpen " .. commit_range())
    end, {buffer = event.buf})
  end,
})
```

**Comment by Fabian-programmer** [comment]
Update: with the new log layout, you have to replace following:

```
  local first_commit = vim.split(first_commit_line, '%s+')[1]
  local second_commit = vim.split(second_commit_line, '%s+')[1]
```


@CKolkey what do you think about this as a part of neogit? :)

**Comment by CKolkey** [comment]
Yeah! How's this? https://github.com/NeogitOrg/neogit/pull/957

**Comment by Fabian-programmer** [comment]
Superb <3
