### ISSUE TITLE
Integrate with `statuscolumn`

### ISSUE THREAD

**Issue by hinell** [NeogitOrg/neogit#430]
**Describe the solution you'd like**

New `statuscolumn` PR just [landed into neovim](https://github.com/neovim/neovim/pull/20621) recently. Now we can configure `statuscolumn` just like `statusline`.

**Describe alternatives you've considered**
Currently embedded signs are fine, but integration via new `statuscolumn` may be considered.

**Additional context**
* See plugin: [luukvbaal/statuscol.nvim](https://github.com/luukvbaal/statuscol.nvim)

**Comment by CKolkey** [comment]
Pretty happy with the current sign-based approach. We use it for a lot of stuff, like line highlighting.
