### ISSUE TITLE
Allow Staging Visual Selection of *Files*

### ISSUE THREAD

**Issue by austinliuigi** [NeogitOrg/neogit#435]
**Is your feature request related to a problem? Please describe.**
As far as I know, staging a visual selection works if the visual selection contains hunks but not files.

**Describe the solution you'd like**
If you visually select more than one file, it stages all of the files.

**Comment by FredeEB** [comment]
I'd love for this to be possible too

**Comment by CKolkey** [comment]
This can be done now :)
