### ISSUE TITLE
Neogit help popup doesn't match "hints"

### ISSUE THREAD

**Issue by embeddedpenguin** [NeogitOrg/neogit#437]
### Description

It looks like the hints don't match up with the help popup. It's weird because there is some overlap. For example, both the hint and the help popup have c for commit, while only the hint has x for discard, and the popup has things that the hint doesn't. These two things don't necessarily conflict, but they aren't synced up.

### Neovim version

NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

5.15.80-gentoo-dist

### Steps to reproduce

1. `:Neogit`
2. See output

### Actual behavior

![image](https://user-images.githubusercontent.com/33668314/214446094-0e2a01fc-4c46-4d58-9eaa-0edd71651dc4.png)

### Minimal config

```Lua
N/A
```

**Comment by CKolkey** [comment]
This has been implemented.

**Comment by embeddedpenguin** [comment]
> This has been implemented.

Thanks for this. It's looking fantastic! Appreciate the hard work.
![image](https://github.com/NeogitOrg/neogit/assets/33668314/709c3c14-9a6e-4c10-ab1c-39d7dd1b9e0a)
