### ISSUE TITLE
Canceling an amend still sends a commit

### ISSUE THREAD

**Issue by ttytm** [NeogitOrg/neogit#439]
### Description

I would like to be able to cancel amending to the last commit and do not have it commited anyway.

Especially while amending it's important to have cancellation working, as it can get time consuming to restore the previous state.

For now, I quit the editor(lol :smiling_face_with_tear: ) if I enter a commit amend dialog and want to stop the amend process.

### Neovim version

stable v0.8.x | nightly

### Operating system and version

Linux

### Steps to reproduce

Trigger commit amend in neogit <kbd>ca</kbd> then e.g., <kbd>q</kbd> to quit.

### Expected behavior

Commit won't get amended when just quitting without saving / confirming.

### Actual behavior

Commit amend happens anyway.

### Minimal config

```Lua
-
```

**Comment by ten3roberts** [comment]
Does this issue still happen?

**Comment by tobealive** [comment]
I'm using #441 since months as it also solves this.

But it still does happen checking back on current master 36ffabb09974d3cdc3f3b31a639280da36a2b79f
