### ISSUE TITLE
Neogit error during commit performance

### ISSUE THREAD

**Issue by Carlosmape** [NeogitOrg/neogit#447]
### Description

When trying to commit it appears a new NeogitStatus tab with the following message:

### Neovim version

NVIM v0.8.3
Build type: RealWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system and version

Windows 10

### Steps to reproduce

1. open up any file in the git repository
2. invoke Neogit wiht cmd `:Neogit`
3. stage some file changed
4. press `c` to perform a commit (and leave default commit parameters):
    ![image](https://user-images.githubusercontent.com/5487555/220583498-94dbe599-5fa2-4693-b3f5-8694972df94b.png)
6. press `c` again
7. NeogitStatus tab appears with the error below

### Expected behavior

Commit message windows should appears and allow me to enter the commit message.

Additional information:
I can perform `git commit -m "<message>"` in a terminal/powershell perfectly
CWD is the root of the git repository (where the .git/ folder is placed)

### Actual behavior

![image](https://user-images.githubusercontent.com/5487555/220582260-6e740438-76ac-4902-8f83-e3285576bacc.png)

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by yngwi** [comment]
I think it's the same error as https://github.com/TimUntersberger/neogit/issues/424

**Comment by CKolkey** [comment]
Feel free to reopen this if it's still an issue.
