### ISSUE TITLE
Implement a git reset keybinding/popup

### ISSUE THREAD

**Issue by fnune** [NeogitOrg/neogit#490]
Thank you for Neogit :bow: 

**Describe the solution you'd like**

When I'm hovering a commit, I would like to use a key (for example `g`) to reset to a certain commit.

Neogit could offer flags `-s` for `--soft`, `-h` for `--hard`, etc. (find more in `git reset --help`), and then issue the following command:

```sh
git reset $flags <commit-under-cursor>
```

**Describe alternatives you've considered**

Use the `git` CLI, or use lazygit, which supports this (see default keybinding [`g`](https://github.com/jesseduffield/lazygit/blob/master/docs/keybindings/Keybindings_en.md#commits)).

**Comment by CKolkey** [comment]
Hi! This is implemented in my upstream branch - use `X` to bring up the reset popup. 

https://github.com/CKolkey/neogit

**Comment by fnune** [comment]
Thanks!

Does it make sense to try to upstream that? I see that #475 is closed for some reason.

**Comment by CKolkey** [comment]
Oh, yea, I'd love to - but I don't think @TimUntersberger is available to review things right now, and I have no official capacity on the upstream repo, so for now it lives in my fork 🤷🏼

**Comment by practicalli-john** [comment]
For reference, Magit uses the `O` (capital o) key binding to reset a commit.

It would be helpful to use the same key if possible, should this feature be adopted into neogit itself.

> Thanks for a great project

**Comment by ten3roberts** [comment]
> Oh, yea, I'd love to - but I don't think @TimUntersberger is available to review things right now, and I have no official capacity on this repo, so for now it lives in my fork 🤷🏼

For reference, we are currently upstreaming in bit by bit in separate PRs, the most recent one is #503

**Comment by CKolkey** [comment]
> For reference, Magit uses the `O` (capital o) key binding to reset a commit.

Is it the case that Doom Emacs has different bindings then? Or maybe evil? Because I have doom installed as a reference, and the binding for reset is `x`.. but, no matter, someone on reddit asked if the help popup could show user defined bindings, which was a great idea, so I built that tonight. So, bind reset to `O` via setup and it'll get first class treatment :)

**Comment by CKolkey** [comment]
So, this was a great idea, and I pretty much implemented it all: https://github.com/CKolkey/neogit/tree/master/lua/neogit/popups/help

So, instead of hard-coding things, just use the user-settings to build the popup.

**Comment by MaxKiv** [comment]
It feels like every time I think 'hey this should be added to neogit' @CKolkey already has it covered 😉
Great work!

**Comment by ten3roberts** [comment]
I truly is as such.

I am extremely contempt with the current (and future) state of Neogit. The popup api we have makes it very easy to add new functionalities.

**Comment by CKolkey** [comment]
> I am extremely content with the current (and future) state of Neogit. The popup api we have makes it very easy to add new functionalities.

Yeah, no doubt about it. I've been focused on polish, and adding missing capabilities (config, fuzzy-finding, the testing story), but once that is all done, it should be very straightforward to just implement new popups/actions without much fussing about in the underlying libraries.
