### ISSUE TITLE
Better toast colors

### ISSUE THREAD

**Issue by alexmozaidze** [NeogitOrg/neogit#494]
**Is your feature request related to a problem? Please describe.**

Both the success toast and the progress toast are colored green, which is a bit confusing.

**Describe the solution you'd like**

I'd like if the toast that indicates that an operation is ongoing to be colored differently (yellow). An example of an ongoing operation would be when pushing to remote.

**Describe alternatives you've considered**

_

**Additional context**

_

**Comment by ten3roberts** [comment]
By toast, do you refer to the right side notifications that "pop out like a toast"?

Never heard the expression before, but sounds fitting.

**Comment by CKolkey** [comment]
Yea, I guess those messages (smaller than a popup, bigger than a tooltip) are called "toasts" https://daisyui.com/components/toast/

**Comment by alexmozaidze** [comment]
Also, I think it wouldn't be unwise to use [nvim-notify](https://github.com/rcarriga/nvim-notify) in place of toasts, and use the old toast system as backup option.

**Comment by CKolkey** [comment]
Toast colors now use the diagnostic highlight groups.
