### ISSUE TITLE
Do not persist dangerous flags such as push --force or --force-with-lease by default

### ISSUE THREAD

**Issue by fnune** [NeogitOrg/neogit#497]
![image](https://user-images.githubusercontent.com/16181067/235676876-080f55b1-a1e1-4b27-99c2-1502c4233a8c.png)

The `--force` and `--force-with-lease` flags are seemingly persisted across different pushes. This is most likely unwanted and runs users into the danger of force-pushing to a branch they don't want to force-push to.

**Describe the solution you'd like**

Simply avoid persisting these flags' values across pushes.

**Comment by fnune** [comment]
Thanks for pointing out that there's something for this. Adding it to my config as well!

Still, I believe those would be good defaults.

**Comment by CKolkey** [comment]
Yea, my thinking was that I would leave it up to the user to disable, but maybe sensible defaults are a better way to go.

**Comment by CKolkey** [comment]
This has been merged :)
