### ISSUE TITLE
Open tab in browser on the pull request creating page

### ISSUE THREAD

**Issue by timsofteng** [NeogitOrg/neogit#509]
**Is your feature request related to a problem? Please describe.**
It is annoying to open github manually in browser after pushing something and to make PR. 

**Describe the solution you'd like**
Lazygit have cool feature. If you press `o` it triggers action which opens tab in browser for pull request creating.

**Comment by CKolkey** [comment]
It's a cool idea. Check out https://github.com/chrishrb/gx.nvim for a similar feature - You could even check out https://github.com/chrishrb/gx.nvim/blob/main/lua/gx/git.lua for how to get the remote URL from a repo and implement the function yourself :)
