### ISSUE TITLE
#210 broke again?

### ISSUE THREAD

**Issue by Arisa-Snowbell** [NeogitOrg/neogit#510]
### Description

It works with vim-fugitive so therefore I have gotten to the conclusion that it's caused by Neogit.

When attempting to commit while having gpg signing turned on it doesn't prompt me for the password even though it does in the terminal or vim-fugitive. And I do have set in gpg confs pinentry-program to loopback.

### Neovim version

NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

Arch Linux with latest updates

### Steps to reproduce

1. Add to staged some changes
2. Try to commit
3. Fails

### Expected behavior

To ask me for the passphrase for the commit to be signed with my gpg key.

### Actual behavior

It doesn't ask me and just weirdly fails, with my level of English I am not capable to describe it properly but it shows some log that the commit failed and it took like 65 seconds or something.

### Minimal config

```Lua
I just installed it without any changes to the config.
```

**Comment by CKolkey** [comment]
Would it be possible for you to bisect that commit and HEAD to try and find the change that broke it?
