### ISSUE TITLE
Neogit breaks when using Noice.nvim

### ISSUE THREAD

**Issue by redyf** [NeogitOrg/neogit#515]
### Description

Everytime after confirming a commit on neogit, it spams an error. I noticed that it only happens when noice.nvim plugin is enabled. LazyGit works fine with noice.

### Neovim version

NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

NixOS 23.11.20230523.d30

### Steps to reproduce

1. Enable noice.nvim and neogit
2. Stage files and try to commit
3. Confirm commit

### Expected behavior

Message was succesfully commited after confirmation with no errors.

### Actual behavior

![image](https://github.com/TimUntersberger/neogit/assets/98139059/66c96201-1edb-45e2-82c5-66b162d3ac9f)
Neogit spam an error after confirming the commit, it keeps showing up until I close neovim entirely!

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
   {
     "folke/noice.nvim",
     event = "VeryLazy",
     config = function()
       require("noice").setup {
         lsp = {
           hover = {
             enabled = false,
           },
           override = {
             ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
             ["vim.lsp.util.stylize_markdown"] = true,
             ["cmp.entry.get_documentation"] = true,
           },
           signature = {
             enabled = false,
           },
        },
  
         presets = {
           bottom_search = true,         -- use a classic bottom cmdline for search
           command_palette = true,       -- position the cmdline and popupmenu together
           long_message_to_split = true, -- long messages will be sent to a split
           inc_rename = false,           -- enables an input dialog for inc-rename.nvim
           lsp_doc_border = false,       -- add a border to hover docs and signature help
        },
       }
     end,
     dependencies = {
       "MunifTanjim/nui.nvim",
     },
   },

    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by ten3roberts** [comment]
I also encountered the exact same issue when a confirmation dialogue popped up.

Seems to perhaps be an issue with `vim.fn.confirm` no longer blocking the editor as it is now async as it needs to display a floating window render it.

I am not sure how noice does it; the default vim behaviour of vimscript `confirm()` is to stop/freeze everything and render a special prompt in the echo area, and then resume the scripting engine from where it was, none the wiser of the time passed.

https://github.com/folke/noice.nvim/issues/388
https://github.com/folke/noice.nvim/issues/337
https://github.com/folke/noice.nvim/issues/232
https://github.com/neovim/neovim/issues/20416 (maybe)

**Comment by IndianBoy42** [comment]
If its a problem of vim.fn.confirm being called from BufUnload, then could a potential solution be to simply "save" the contents of the buffer (and whatever is needed) and defer doing the actual work to after BufUnload? Like using `vim.schedule` or `vim.defer_fn`.

**Comment by CKolkey** [comment]
I've got some ideas for this - might be able to get to it soon.
