### ISSUE TITLE
Feature Request: Checkout new branch should default to remote branch name

### ISSUE THREAD

**Issue by wrightjjw** [NeogitOrg/neogit#517]
**Is your feature request related to a problem? Please describe.**
At my org, we typically create branches on our git server instead of locally to link them to work items. I fetch, then use `b c` in neogit to checkout the remote branch. Neogit prompts me to name the new local branch. To keep git happy - and to keep things consistent - I have to type out the entire branch name as it is on remote, which can get a bit lengthy. I do this all the time at work.

**Describe the solution you'd like**
I think neogit should handle this the same way magit does: When you `b c` a remote branch, it should autofill the new branch name with the remote branch name, minus "origin" (or whatever the remote is named). I presume this is what most people usually want when they do this anyway.

**Comment by CKolkey** [comment]
While not _exactly_ the same (and not to say this isn't a good idea - it absolutely is), Coming Soon™️, we'll introduce branches that only exist on remotes and NOT locally to the `b l` list, and if selected, will check out a new branch locally and set the upstream automatically. 

https://github.com/CKolkey/neogit/blob/master/lua/neogit/popups/branch/actions.lua#L42:L65
