### ISSUE TITLE
Feature Request: Option to force delete a branch

### ISSUE THREAD

**Issue by wrightjjw** [NeogitOrg/neogit#518]
**Is your feature request related to a problem? Please describe.**
I have a local branch tracking a remote branch. I have commits on my local branch that I do not wish to push. I'd like to delete my local branch.
When I use `b d` on my branch in neogit, the command fails, as `git branch -d <branch_name>` does. Git recommends using `git branch -D <branch_name>` (aka `git branch -d --force <branch_name>`). Logically, I would assume that neogit's `b D` would do this, but it says that it will delete the remote branch, which I don't want to do.

This is probably a rare use case, but it happened to me today, so I thought I'd at least note it down!

**Describe the solution you'd like**
It would great if there was some kind of branch force delete option. Magit has a y/n prompt after an unmerged branch is selected for deletion. Maybe that would be a good way to handle this in neogit?

**Comment by CKolkey** [comment]
Well, this finally happened to me. Quite annoying. I've implemented it on my branch https://github.com/TimUntersberger/neogit/commit/1ceced35afa9cf2161526e13b210f2289fca95cc

No special command, but behind the scenes we check if a branch has unmerged commits (if `git cherry master <branch name>` isn't empty) and prompt the user to confirm. If they do, use `--force`.

Thanks for the suggestion!
