### ISSUE TITLE
Enable option to disable notify_move check

### ISSUE THREAD

**Issue by polarmutex** [NeogitOrg/neogit#545]
**Is your feature request related to a problem? Please describe.**
I use nix to configure neogit and this check fails since git info does not exist for the plugin even though I have switch to new location

**Describe the solution you'd like**
add a setup option to disable check to prevent errors from displaying on launch

**Describe alternatives you've considered**
none

**Additional context**

**Comment by ten3roberts** [comment]
Would 06113a4 solve your issue?

I will remove `notify_move` in a short while as well, the warning is only temporary.
