### ISSUE TITLE
Annoying popup 

### ISSUE THREAD

**Issue by TakenMC** [NeogitOrg/neogit#546]
### Description

I would get this annoying popup every time I would open neovim on a non git repo folder
I know it has to check if it's a git repo but it's annoying to have it show
![image](https://github.com/NeogitOrg/neogit/assets/68560840/8bacb475-e806-4e61-8d60-a47fa7836714)

### Neovim version

NVIM v0.9.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system and version

Windows 10

### Steps to reproduce

Opening neovim in a non git directory 

### Expected behavior

To not have 4 notification on at once saying i am not in a git directory 

### Actual behavior

4 annoying notifications 

### Minimal config

```Lua
local setup, neogit = pcall(require, "neogit")
if not setup then
    return
end

neogit.setup {
    auto_refresh = true,
    remember_settings = true,
    disable_insert_on_commit = false,
    commit_popup = {
        kind = "split",
    },
    preview_buffer = {
        kind = "split",
    },
    popup = {
        kind = "split",
    },
    signs = {
        section = { "", "" },
        item = { "", "" },
        hunk = { "", "" },
    },
    integrations = {
        diffview = true
    },
    sections = {
        untracked = {
            folded = false
        },
        unstaged = {
            folded = false
        },
        staged = {
            folded = false
        },
        stashes = {
            folded = true
        },
        unpulled = {
            folded = true
        },
        unmerged = {
            folded = false
        },
        recent = {
            folded = true
        },
    },
    mappings = {
        status = {
            ["p"] = "PushPopup",
            ["P"] = "PullPopup"
        }
    }
}
```

**Comment by ten3roberts** [comment]
What does the console say?

Also, which remote are you using for the plugin itself?

**Comment by wrightjjw** [comment]
This just happens on Windows, and it suppresses the new remote notification. Even after changing it over to NeogitOrg it still pops up. Also, this seems to happen for me every time I open Neogit, not just in a git repo.

The console just says ` 1 git --no-pager -c color.ui=always --no-optional-locks config --get remote.origin.url (470.000 ms) [stderr 1]`.

Haven't used Windows since 2de09534a25993550f3aa2abf4c05d2496e55b94 was put out so I'm thinking it happened somewhere in adding the new notification. I'll dig a bit deeper sometime today.

**Comment by ten3roberts** [comment]
Ok. Thanks for the insights.

Managed to reproduce on Mac by `remote.orign.url` (mispelled). Perhaps it is just a git config key difference then

**Comment by ten3roberts** [comment]
6c83d8f should silence it

I'll remove it all together on friday

**Comment by wrightjjw** [comment]
> https://github.com/NeogitOrg/neogit/commit/6c83d8f6ba26a1313199225994857b516ab921de should silence it

That did the trick on my end.

**Comment by TakenMC** [comment]
ill check that later when i can

**Comment by TakenMC** [comment]
It's ok now and I don't get those anymore
Tho the console still pops up
