### ISSUE TITLE
Documentation request: vim.opt.autochdir = true

### ISSUE THREAD

**Issue by aadi58002** [NeogitOrg/neogit#547]
### Description

Please add the above configuration option to docs.
As it is confusing when running the Neogit command it open the original dir in which nvim was run from the cli rather than the currently open file.

### Neovim version

NVIM v0.9.1
Build type: None
LuaJIT 2.1.0-beta3
Compilation: /usr/lib/ccache/bin/cc  -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/usr/include/luajit-2.1 -I/usr/include -I/usr/include -I/builddir/neovim-0.9.1/build/src/nvim/auto -I/builddir/neovim-0.9.1/build/include -I/builddir/neovim-0.9.1/build/cmake.config -I/builddir/neovim-0.9.1/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

### Operating system and version

Void linux

### Steps to reproduce

1. Open neovim from the home dir and after that navigated to a git project file.
2. Run `:Neogit` 
3. It prompted me to initialize a git repo on my home folder. 

### Expected behavior

Detect the top level git repo with respect to the currently open file.

### Actual behavior

Prompts or open the git repo in which neovim was originally run from the cli.

### Minimal config

```Lua
-- plugins/neogit.lua:
return {
    'NeogitOrg/neogit',
    dependencies = 'nvim-lua/plenary.nvim',
    keys = {
        { "<leader>gg", "<cmd>Neogit<cr>", mode = "n", desc = "Neogit" },
    }
}
```

**Comment by ten3roberts** [comment]
What does `:echo system("pwd")` display in the Neogit status buffer?

I think the issue is that the working directory set by `autochdir` is only buffer local so it does not follow to new buffers (like neogit, other plugins or other files)

**Comment by aadi58002** [comment]
if vim.opt.autochdir = false
It display /home/<username>
after setting it to true
It display the path the file which is currently open

I know what the issue is for it to work correctly the neovim config option of chdir has to be set to true so that the neovim process directory follows the currently open buffer.

**Comment by ten3roberts** [comment]
Yes, I think that is because the jobstart run in an async thread which is not attached to a window.

**Comment by aadi58002** [comment]
It took me some time to figure out what the issue is why it is not following the currently open file.
So I think it should be mentioned in the documentation that this variable has to be set to true so that Neogit command follows the currently open buffer.

**Comment by ten3roberts** [comment]
Oh sorry 😅, then I misunderstood the issue.

I thought you had `autochdir=true` and neogit still used the global working directory rather than the buffer local one.

`autochdir=true` works and will make neogit open the repo for the current file, if I've understood your config correctly.

Have never used `autochdir` myself, and know that it is not favored that much because it causes a lot of problems related to ghost handles and context.

**Comment by ten3roberts** [comment]
Perhaps a better alternative is an option with the Neogit command using the current file as a context, `Neogit cwd=path_to_parent_dir` already exists, but a `:Neogit local_file=true` or alike would be even better as you don't have to type out the current dir

**Comment by aadi58002** [comment]
Adding support for the expand function will also help 
```lua
            {
                "<leader><space>",
                "<cmd>Telescope file_browser path=%:p:h select_buffer=true hidden=true<cr>",
                desc =
                "Find Files (root dir)"
            },
```
I actually use it set the current path for a telescope file manager plugin

**Comment by ten3roberts** [comment]
I would in general advice against using to use `autochdir` as it inteferes with a lot of other plugins, so it may cause more harm than good, and therefore it should probably not be mentioned in the readme.

If that is ok?

The `Neogit cwd=%:p:h` will get a mention in the readme as it is quite useful

**Comment by aadi58002** [comment]
I am quite new to neovim ecosystem so I am not sure of the best practices. If setting the cwd with %:p work then I don't feel any need to mention autochdir.
