### ISSUE TITLE
Neogit hangs when committing changes

### ISSUE THREAD

**Issue by ghostbuster91** [NeogitOrg/neogit#555]
### Description

Thanks for this great plugin, most of the time it works flawlessly and I really enjoy using it!

> git --no-pager -c color.ui=always --no-optional-locks commit
Command "git --no-pager -c color.ui=always --no-optional-locks commit" running for more than: 1345.2 seconds

This happens almost immediately so I am sure that 1345 seconds haven't passed during that time. 

From time to time neogit fails to commit with the above message and I have to retry commit operation (including writing the commit message). Now, my laptop is fairly fast, and repositories that I have encountered that issue with, are quite small, so I don't think that this is a performance issue. 

Sometimes I commit from the command line and I haven't seen such behavior there, tough I guess it is a matter of used switches. 

### Neovim version

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

nixos 23.11

### Steps to reproduce

I am happy to provide you more info if needed but since I don't have a good way of reproducing this with my current config I am not able to provide a minimized one :( Maybe I could enable some more extensive logging, and start collecting logs? Having said that my config is pretty vanilla, I updated the minimal config below with my changes. 

In general it happens when I try to commit. 
1. do some changes it the codebase
2. call `neogit.open()`
3. stage changes
4. commit changes
5. write commit message
6. save and quite commit message buffer
7. the message appears

### Expected behavior

Message should not appear and the commit should happen. 

### Actual behavior

Console appears with the mentioned warning but nothing happens next. After closing the console changes are not committed and there is no trace of the commit that was supposed to happen. 

### Minimal config

I am using this commit - 72824006f2dcf775cc498cc4a046ddd2c99d20a3 (almost the newest)

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          local neogit = require('neogit')
          neogit.setup {
            disable_commit_confirmation = true,
          }

        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by ten3roberts** [comment]
Good to know that you are enjoying this plugin 😊 

I have encountered this as well, and it seems to be because the buffer is closed but the headless neovim client that git spawn fails to terminate through the pipe.

What happens with the 1345 seconds is likely that an *older* commit also failed, and it has just been hanging around waiting for nothing.

There are two things that need to be solved for this:

1. Tracing calls and finding out if the rpc client fails to quit
2. Make sure all subcommands time out after some good few minutes to prevent situations where a command was started but aborted too quick.

**Comment by ghostbuster91** [comment]
I saw that case mentioned in some other issue, that is not the case as I don't have any git hooks in my repos.

**Comment by CKolkey** [comment]
Closing this - feel free to open a new issue if you're still experiencing this.
