### ISSUE TITLE
Checkout commit/revision under the cursor and in the log buffer

### ISSUE THREAD

**Issue by ten3roberts** [NeogitOrg/neogit#556]
**Is your feature request related to a problem? Please describe.**
Ability to checkout (not reset) a commit under the cursor or in the log buffer

**Describe the solution you'd like**
Magit allows doing this by entering an arbitrary commit in the branch checkout.

We show a list of branches, and not commits

https://magit.vc/manual/magit/Branch-Commands.html#index-b-b

![image](https://github.com/NeogitOrg/neogit/assets/25723553/30819f66-d2d6-4658-b767-e7b2f23b9ff0)

**Comment by CKolkey** [comment]
Super cool idea. One of the advantages to the telescope integration is the ability to overload the on_select function. Should be possible to add a check for if the selection is nil, but the input buffer has content, and try to use that as raw input. Something similar needs to be done with the remotes popup, when adding a remote, iirc

**Comment by CKolkey** [comment]
Yea that was the idea, that it would just kinda "do the right thing" if you enter a valid revision/oid. I know its a slight divergence from normal behaviour, but I think it would be alright. Lets see - maybe the idea needs some massage.

But isn't branch-popup/revision already for that? It doesn't open a log view, but maybe inverting this idea would work: from the log view, allow a user to checkout the revision under the cursor

**Comment by ten3roberts** [comment]
This has now been implemented and merged in #734
