### ISSUE TITLE
Neogit error on startup: not a git repository

### ISSUE THREAD

**Issue by ten3roberts** [NeogitOrg/neogit#557]
Feel free to hide this pass by comment (or should I open an issue for that?).

Well done on all your hard work!

I am getting an error when running setup (at nvim's startup) when not in git repo:
```
git rev-parse --show-toplevel:
fatal: not a git repository (or any of the parent directories): .git
Open the console for details
```

_Originally posted by @gegoune in https://github.com/NeogitOrg/neogit/issues/554#issuecomment-1633955161_

**Comment by CKolkey** [comment]
@ten3roberts Pretty sure that fixes it - check it out and if it works for you too we can merge it

**Comment by gegoune** [comment]
Does Neogit need that information during setup? Couldn't it only detect root when actually used? At the moment Neogit is single slowest plugin at start up (it's still fast, not complaining here so please don't get me wrong) and there is quite a few occasions where I don't use Neogit.

**Comment by CKolkey** [comment]
Yeah, it does, at least for now - we build a big table for the repo state, and use the git root to check if we should run all the updates or not, basically as a guard clause. IMO it could probably happen at _open_ instead of at _setup_, however.

**Comment by gegoune** [comment]
Not doing it at setup time would alleviate need for any lazy loading shenanigans. :)

**Comment by CKolkey** [comment]
Fair. `Lazy.nvim` makes it so easy, but not everyone will use it. I've got some stuff in development that overhauls this, so it might get sorted out.
