### ISSUE TITLE
Prompt to set upstream when pushing local branch

### ISSUE THREAD

**Issue by RianFuro** [NeogitOrg/neogit#56]
The push operation should prompt the user to select an upstream to synchronize the branch to, if the branch does not have an upstream yet.

On that topic, since we've copied over the `pushRemote` vs `upstream` distinction from magit, do we want to keep going with that?

**Comment by TimUntersberger** [comment]
I think having a distinction is import for differencing between pushing to the `orignal repo` vs `your forked version` right? I am not to sure how this exactly should work yet 🤷‍♂️

**Comment by CKolkey** [comment]
We do this now :)
