### ISSUE TITLE
All of the status commands are mapped as a normal mode commands

### ISSUE THREAD

**Issue by pastalian** [NeogitOrg/neogit#561]
### Description

tbl_add_reverse_lookup modifies the input therefore all status command names are mapped as normal mode commands.

https://github.com/NeogitOrg/neogit/blob/4ed8336fc54a66102617f82d01a68fc3b0e94594/lua/neogit/popups/help/actions.lua#L6

```
:nmap GoTo
n  GoToPreviousHunkHeader *@<Cmd>lua require 'neogit.lib.mappings_manager'.invoke(2, 48)<CR>
n  GoToNextHunkHeader *@<Cmd>lua require 'neogit.lib.mappings_manager'.invoke(2, 32)<CR>
n  GoToFile    *@<Cmd>lua require 'neogit.lib.mappings_manager'.invoke(2, 13)<CR>
```

### Neovim version

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

Gentoo Linux

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. `:lua require('neogit').open()`
3. `:nmap`

### Expected behavior

Only "key" is mapped, not "command name".

### Actual behavior

Both "key" and "command name" are mapped.

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by treatybreaker** [comment]
Hey @pastalian, can you try my [patch](https://github.com/treatybreaker/neogit/tree/fix/status-mappings-normal-cmds) and let me know if it resolves the problem for you?

For me typing `nmap GoTo` after that patch does not show any of the status commands in my output.

**Comment by pastalian** [comment]
@treatybreaker Yep, that fixed it for me too.

**Comment by treatybreaker** [comment]
> @treatybreaker Yep, that fixed it for me too.

Cool, I'll open a PR.
