### ISSUE TITLE
Modify the hint according to user keymappings

### ISSUE THREAD

**Issue by IndianBoy42** [NeogitOrg/neogit#564]
**Is your feature request related to a problem? Please describe.**
I want to keep 's' to use leap.nvim in the neogit buffer, so i have made `a = Stage`  (mnemonic add) 

**Describe the solution you'd like**
I want to modify the hint at the top of the neogit buffer to say `st[a]ge` instead. Maybe also add a few other helpful hints. I think this part can be manual, but the `?` popup should also be adjusted to include new mappings (it still says `s Stage` after the above mapping)

**Comment by treatybreaker** [comment]
With the current way the keymaps are layed out in Neogit this isn't exactly *trivial*, but it's not *hard*. If #604 is ok and merged with `vim.tbl_add_reverse_lookup` then the solution for the hints at the top of the Neogit status buffer are pretty easy to update.

What might be more difficult to set is the help menu bindings in the Neogit status buffer.

**Comment by treatybreaker** [comment]
Since #604 got merged, I'll see if I can get around to this tomorrow (ideally).

**Comment by treatybreaker** [comment]
@CKolkey As a heads up #618 only updates the hint mappings at the top of the buffer, it still does not show the correct keybindings in the help popup. 

May want to reopen this or I can create a separate issue for that.

**Comment by CKolkey** [comment]
Oh, it auto closed since I merged the linked PR. Why don't you make a new issue and we can circle back to it when https://github.com/NeogitOrg/neogit/pull/601 is merged (assuming conflicts)
