### ISSUE TITLE
Installation error: Duplicate tag

### ISSUE THREAD

**Issue by ckt114** [NeogitOrg/neogit#565]
### Description

Unable to install using lazy.nvim. Got the error below.

```
  Failed (1)
   * neogit 
        ...hare/nvim/lazy/lazy.nvim/lua/lazy/manage/task/plugin.lua:79: Vim:E154: Duplicate tag "neogit_c" in file /Users/ctran/.local/share/nvim/lazy/neogit/doc//neogit.txt
```

### Neovim version

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

macOS Ventura 13.4

### Steps to reproduce

Add block below to lazy.nvim plug list.

```
return {
  "NeogitOrg/neogit",
  dependencies = "nvim-lua/plenary.nvim",
}
```

### Expected behavior

Plugin should be installed.

### Actual behavior

Plugin didn't install and errored out.

### Minimal config

```Lua
return {
  "NeogitOrg/neogit",
  dependencies = "nvim-lua/plenary.nvim",
}
```
```

**Comment by skoch13** [comment]
I can confirm that the very same error is shown, still the plugin works. It looks like setup part is missed in your config

```
  {
    "NeogitOrg/neogit",
    dependencies = "nvim-lua/plenary.nvim",
    config = function()
      require("neogit").setup({})
    end,
  },
```

**Comment by CKolkey** [comment]
Thanks!
