### ISSUE TITLE
commit_popup kind floating not working

### ISSUE THREAD

**Issue by mystilleef** [NeogitOrg/neogit#579]
### Description

I am having an issue where the commit message window is not appearing as a floating popup, even though I have configured it to do so in the options.

### Neovim version

NVIM v0.10.0-dev-664+g0ce391086
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

Fedora Linux 38 (Workstation Edition)

### Steps to reproduce

1. Show the `neogit` view with `: Neogit`
2. Stage a commit
3. Press `c` twice to write a commit message

### Expected behavior

The commit message window should open in a floating window.

### Actual behavior

The commit message window opens in a split window.

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "NeogitOrg/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup({popup = {kind = floating}, commit_popup = {kind= floating}})
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by wolves** [comment]
Not sure if it helps at all but I have one machine that I haven't updated Neogit on and another that I have where this appears. To help in the fix the commit sha range that this bug was introduced appears to between

1b6edb56e8c754494be1564912d33e50ddd8a023 (Older commit where this bug doesn't exist)

33016ad20b92b7eb83d27880b4abfbce53b467ad (More recent commit where it does exist)

Hope this helps in tracking down the bug

**Comment by treatybreaker** [comment]
Among other things I'll take a git bisect to this and check it out myself tomorrow. Thanks for some base commits to look at.

**Comment by treatybreaker** [comment]
This isn't a *bug*, it's a failure of documentation it seems.

Try this:

```lua
require("neogit").setup({
    commit_editor = { kind = "floating" },
})
```

We just need to update the README.

**Comment by mystilleef** [comment]
@treatybreaker that fixed my issue. Thanks!

**Comment by wolves** [comment]
Ahhh so `commit_popup` -> `commit_editor`, I see. Thank you for sorting this out for me. This change fixed the issue for me as well
