### ISSUE TITLE
Error for commiting without staging

### ISSUE THREAD

**Issue by TakenMC** [NeogitOrg/neogit#580]
**Is your feature request related to a problem? Please describe.**
Not really tho seeing an error message makes it seem something bad happened

**Describe the solution you'd like**
If no files are currently staged it would be nice to have a message say "Please stage files before commiting" same as the message when pushing and pulling

**Describe alternatives you've considered**
I have none

**Additional context**
The request seems self explanatory

**Comment by ten3roberts** [comment]
Good idea.

I suppose that the error you are getting now is the underlying `git commit` error of "no changes added to commit" and makes it sound like the world is about to end.

This would be covered by the aforementioned git output parsing in #537. Feel free to add a comment under that issue for a git error which can be parsed and recognized.

**Comment by TakenMC** [comment]
ok

**Comment by CKolkey** [comment]
Well, the possible issue is that you can do an empty commit with the `--allow-empty` flag, so... and empty commit is valid. Maybe parsing and explaining to the user more concisely what went wrong is the way to go

**Comment by rami3l** [comment]
@CKolkey Thanks for making https://github.com/NeogitOrg/neogit/commit/9e3ae89a7101468f7d69434685232d49440b3916! However didn't this make `git commit --allow-empty` no longer possible, since it is currently covered in the early-returning branch?

**Comment by CKolkey** [comment]
Thanks - fixed: [`568415f` (#1594)](https://github.com/NeogitOrg/neogit/pull/1594/commits/568415f236c6b0cef1f55f957112cdf0689c150a) 😅
