### ISSUE TITLE
Provide a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by miguelcrespo** [NeogitOrg/neogit#581]
Hi, I was checking out the code of this plugin since I use it a lot and I wanted to understand the code and I notice there's no `CONTRIBUTING.md`, it might be beneficial to include one to give a brief introduction of how to contribute to this project, some sections I have in mind:

- Introduction to the project and architecture
- Code standards
- How to run the project locally and start developing

**Comment by ten3roberts** [comment]
That is a good idea and would further help Neogit becoming an active project.

I'll also add for myself to remember that the `todo.txt` could be removed as it is mow far from relevant
