### ISSUE TITLE
Neogit seems to call TermOpen via setup

### ISSUE THREAD

**Issue by KodyVB** [NeogitOrg/neogit#587]
### Description

One of the recent Neogit updates seems to be causing Neovim to call TermOpen when the setup function is called. I like to have my terminals in Neovim open in insert mode, so I have the following in my config: `vim.api.nvim_create_autocmd("TermOpen", { command = "startinsert" })`. 

This results in Neovim's normal buffers opening in insert mode, rather than normal mode, when it should only be applied to the terminal buffers.

I installed Neogit for the first time yesterday and didn't have this problem, but after updating my plugins today I noticed it, which is why I think a recent update is the culprit. 

### Neovim version

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

Arch Linux

### Steps to reproduce

1. Update Neogit to the current release with the TermOpen autocmd
2. Open Neovim

### Expected behavior

Neovim opens in normal mode

### Actual behavior

Neovim opens in insert mode

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
vim.api.nvim_create_autocmd("TermOpen", { command = "startinsert" })
```

**Comment by treatybreaker** [comment]
From `git bisect` seems the commit causing this behavior is 66bdfe592b038fbeb129921a05e2d45b1ebd097a

**Comment by treatybreaker** [comment]
Seems to be this line: https://github.com/NeogitOrg/neogit/blob/015c27c5b74eba9b151c683579c838e742bf36a2/lua/neogit/process.lua#L104

**Comment by treatybreaker** [comment]
This line is the root where this problem is coming from ultimately:

https://github.com/NeogitOrg/neogit/blob/ea570537d6ee1893a6ec66d2c46cc646d602e493/lua/neogit/lib/git/cli.lua#L451

This is because the `process` lib spawns a terminal in the background.

**Comment by treatybreaker** [comment]
Hey @KodyVB, mind giving my patch a shot?

https://github.com/treatybreaker/neogit

That defers the nvim term open until absolutely needed so it doesn't interfere with your insert enter autocmd.

**Comment by KodyVB** [comment]
From what I've seen, those changes do seem to fix it and I haven't noticed any unwanted behaviors from it.

**Comment by treatybreaker** [comment]
I have actually found one issue that I'm currently battling with it. The console key (by default `#`) doesn't scroll to the end of output, it scrolls to the entire end of the buffer with the modifications I have made.

Currently working on resolving it.

**Comment by treatybreaker** [comment]
Fixed.
