### ISSUE TITLE
Colors not loading after Neogit or if colorscheme is changed

### ISSUE THREAD

**Issue by riddlew** [NeogitOrg/neogit#590]
### Description

It seems that the colors for Neogit do not load if the colorscheme is loaded after Neogit setup, or if the colorscheme is changed at any time. I usually load my colorscheme after loading all plugins because some plugins have overridden my colors in the past. If I load the colorscheme before the Neogit plugin, it works fine. But if I load it after Neogit has been loaded, or if I at any time change my colorscheme with `:colorscheme` while using neovim, the colors disappear entirely.

I use lazy.nvim, and the only way I was able to get around this was by lazy loading neogit, and manually requiring it to load it at the very end of my init file after my colorscheme is loaded. It will still break if I change my colorscheme while using neovim.

### Neovim version

```
nvim --version
NVIM v0.10.0-dev-528+g1f8fb7c00
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-10 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_TS_HAS_SET_MAX_START_DEPTH -I/__w/neovim/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/__w/neovim/neovim/.deps/usr/include -I/__w/neovim/neovim/build/src/nvim/auto -I/__w/neovim/neovim/build/include -I/__w/neovim/neovim/build/cmake.config -I/__w/neovim/neovim/src -I/usr/include -I/__w/neovim/neovim/.deps/usr/include -I/__w/neovim/neovim/.deps/usr/include -I/__w/neovim/neovim/.deps/usr/include -I/__w/neovim/neovim/.deps/usr/include -I/__w/neovim/neovim/.deps/usr/include -I/__w/neovim/neovim/.deps/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"
```

### Operating system and version

Linux Mint  21.1 Cinnamon

### Steps to reproduce

1. Check `:Neogit` and ensure colors are showing correctly.
2. Change color scheme, such as `:colorscheme torte`.
3. Colors are no longer working, even after closing and reopening Neogit.
4. Edit `minimal.lua` and uncomment the line that changes colorscheme after setup has been called.
6. Colors are no longer working.

### Expected behavior

Colors should still work after changing your colorscheme while using Neovim or after Neogit setup has been called.

### Actual behavior

Changing the colorscheme while using Neovim or after Neogit setup has been called causes colors to disappear entirely.

### Minimal config

```Lua
if vim.fn.exists('+termguicolors') then
    vim.cmd('let &t_8f="\\<Esc>[38;2;%lu;%lu;%lum"')
    vim.cmd('let &t_8b="\\<Esc>[48;2;%lu;%lu;%lum"')
    vim.opt.termguicolors = true
end
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
          -- vim.cmd('colorscheme torte')
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by katawful** [comment]
I have this issue as well due to my setup that changes colorscheme/background based on time. Does not seem to be install dependent, as this call is done on a timer

**Comment by jemag** [comment]
I think the highlights are configured only on Neogit's setup instead of being properly configured on autocmd.

The usual pattern for plugins is to configure it instead on the `ColorScheme` autocmd to avoid these kinds of issues.

**Comment by CKolkey** [comment]
Thanks - I'll do the same :)

**Comment by CKolkey** [comment]
Lemme know if everything is good with #617 - I think it should do the trick.

**Comment by riddlew** [comment]
Just checked it out, everything looks good to me :+1:  Thanks for the fast updates!

**Comment by jemag** [comment]
works great on the branch, thanks

**Comment by alextricity25** [comment]
I'm not getting any color when I run `Neogit` :( Presumeably it's because of this issue, even though I am loading my colorscheme _before_ neogit. 
<img width="777" alt="image" src="https://github.com/NeogitOrg/neogit/assets/4964964/fc837388-614f-4780-90ed-3ba0009d6946">

**Comment by CKolkey** [comment]
Does this branch fix it?

**Comment by alextricity25** [comment]
Yes! Looks like it! Sorry I didn't mention it before. This is what it looks like on your branch:
<img width="932" alt="image" src="https://github.com/NeogitOrg/neogit/assets/4964964/b5d45515-38d5-4429-aacd-fa976982ed91">

**Comment by katawful** [comment]
Works with my colorscheme timer, thanks

**Comment by Hubro** [comment]
Has there been a regression? I just installed Neogit for the first time today, to test it out. The colors are completely broken:

![image](https://github.com/NeogitOrg/neogit/assets/597206/34be4eb1-fea7-463d-84fe-5306cd31a217)

If I reload my colorscheme after opening `:Neogit`, it looks fine:

![image](https://github.com/NeogitOrg/neogit/assets/597206/7853fb3d-a5c8-4d1f-bad2-e792ae4ab827)

I'm on bc6aca9.

**Comment by zspekt** [comment]
@Hubro I'm having the same issue. Were you able to fix it?
