### ISSUE TITLE
Improve minimal init

### ISSUE THREAD

**Issue by treatybreaker** [NeogitOrg/neogit#621]
**Is your feature request related to a problem? Please describe.**
See discussion [here](https://github.com/NeogitOrg/neogit/pull/616/#discussion_r1264728918)

**Requirements**
Provide an improved minimal init that does a few things:
1. Should not use a shared cache
2. Should not pollute global filesystem
3. Each run should be reasonably separated from previous minimal init usages such that the state is not impacted by previous runs
4. Minimal init should not utilize package managers to install plugins, use built-in functionality to keep the minimal init simple
5. Minimal init *should* persist dependencies (such as plenary) between runs to keep repeated invocations quick *without* changing the behavior of subsequent runs

**Some Solutions**
See [this](https://github.com/NeogitOrg/neogit/pull/616/#discussion_r1264728918) discussion for some ideas tossed around. Currently the comparison should be between [this minimal init](https://github.com/NeogitOrg/neogit/pull/616/#discussion_r1264730696) and [@ten3roberts minimal init](https://github.com/NeogitOrg/neogit/pull/616/#discussion_r1264732449).

If the Neovim flags `-n --clean` do not completely separate each neovim run from another then @ten3roberts minimal init is preferred as it better cleans up between runs.

**Additional context**
Investigate if the Neovim flags `-n --clean` completely separate each Neovim run. Does not share a cache, state, data, config between runs. Only thing that should be shared between runs is the cached downloaded plugin dependencies like plenary.

I'll be doing this investigation when I have a convenient moment to do so.

**Comment by treatybreaker** [comment]
From my experiments using the flags `-n --clean` leave only one thing polluted, `$XDG_STATE_HOME`.

@ten3roberts Since that's the case I think going with your config *may*, be better as it already handles that case and we're not beholden to any changes those flags have on system state with your minimal init.

**Comment by CKolkey** [comment]
Using `NVIM_APPNAME` should prevent any cross-contamination of cache between the test run and a user's setup

**Comment by treatybreaker** [comment]
> Using `NVIM_APPNAME` should prevent any cross-contamination of cache between the test run and a user's setup

We're going to want to teardown the cache after the fact though -- it would irritate me quite badly if I saw `NVIM_NEOGIT` all around my system. To do that we'd still need to set the `XDG` vars.

Also, is `NVIM_APPNAME` nightly or 0.9? I forget when it was added.

**Comment by treatybreaker** [comment]
I'm thinking a combo of @ten3roberts's config with `NVIM_APPNAME` is probably ideal. If that sounds good to you @CKolkey & @ten3roberts I can roll with that and PR it when I get around to it. LMK.

**Comment by CKolkey** [comment]
Sounds great  😀
