### ISSUE TITLE
neogit returns errors in headless mode in the hl.make_palette function

### ISSUE THREAD

**Issue by polarmutex** [NeogitOrg/neogit#622]
### Description

neogit returns errors in headless mode in the hl.make_palette function

### Neovim version

NVIM v0.10.0-dev-622ae2f
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

Nixos

### Steps to reproduce

nvim --headless -c "q"

### Expected behavior

running in headless mode should not generate errors

### Actual behavior

lua/neogit/lib/color.lua:101: bad argument #1 to 'rshift' (number expected, got nil)

is generated

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by treatybreaker** [comment]
That's really weird! Running the minimal init provided with 
`nvim --clean --headless -c "q" -nu minimal-init.lua`
doesn't output an error.

Using my normal config though does. (`nvim --headless -c "q")

**Comment by treatybreaker** [comment]
The branch created for #617 seems to resolve the issue.

Can you give the [hard-code-colors](https://github.com/NeogitOrg/neogit/tree/hard-code-colors) branch a shot @polarmutex and report back?

**Comment by treatybreaker** [comment]
We may want to detect if neogit is running in headless mode, and if it is maybe don't load?

We can use `nvim_list_uis()` to check if we're in `--headless` or `--embed` mode. If that returns empty then we can skip all the color setup as then we are necessarily in one of those two modes.

**Comment by CKolkey** [comment]
Man, this colors thing is turning out to be a headache. Yeah, some kind of guard clause on it would be good, if it's causing issues.

**Comment by treatybreaker** [comment]
What I posted seems like a decent idea on the surface, but this will make any tests that validate colors in the future not consistent with normal headless usage. This is because we'd need to pass a force setup clause for highlights if we're currently testing neogit and in headless mode. If we guard entirely on headless/embed mode then we'll be unable to test highlights unless we create a flag for testing.

This is an issue because we want the tests and the normal setup for Neogit to be identical ideally.

If you think a test flag is ok to force setup of highlights then I'll make a PR for it, but I'm not sure it's the best route. I think using the defaults you've set in #617 is probably better.

**Comment by CKolkey** [comment]
Hopefully that works, yeah. I think, in addition to that, an autocmd that runs on `ColorScheme` or something to re-setup highlight groups..

**Comment by polarmutex** [comment]
I do not see the error with #617
