### ISSUE TITLE
Add a curated list of highlight groups and what they do

### ISSUE THREAD

**Issue by echasnovski** [NeogitOrg/neogit#627]
**Is your feature request related to a problem? Please describe.**
As a color scheme author I found it extremely hard to navigate what highlight groups are present and which ones do what. Using `:Inspect` most of the time doesn't show anything.

**Describe the solution you'd like**
A clear and concise description of plugin's highlight groups and what they do.

**Describe alternatives you've considered**
Browsing source code in an attempt to understand which highlight groups is responsible for the region I'd like to change highlighting.

**Additional context**

**Comment by CKolkey** [comment]
Super reasonable - I'll write something up

**Comment by CKolkey** [comment]
Ooops, yup, thanks.
