### ISSUE TITLE
Got error after update

### ISSUE THREAD

**Issue by hiberabyss** [NeogitOrg/neogit#635]
### Description

Have following error message after update  neogit plugin:

<img width="1438" alt="image" src="https://github.com/NeogitOrg/neogit/assets/2898670/d5a9d0b5-1e53-4485-91ab-5505576f56ae">

### Neovim version

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.1/share/nvim"

Run :checkhealth for more info

### Operating system and version

macOS 13.4.1 (c) 

### Steps to reproduce

Open vim, execute `:Neogit`

### Actual behavior

Have the error message.

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by CKolkey** [comment]
That config works fine for me :\

**Comment by CKolkey** [comment]
Do you have any custom mappings set?

**Comment by hiberabyss** [comment]
> Do you have any custom mappings set?

What kind of mapping may cause the problem?

**Comment by treatybreaker** [comment]
I know this bug. Let me guesss @hiberabyss you're disabling two more default maps by doing this:

```lua
[KEY_HERE] = ""
```

#629 contains a fix for it if that's what you're doing.

**Comment by hiberabyss** [comment]
Still have following error after updating:

<img width="1440" alt="image" src="https://github.com/NeogitOrg/neogit/assets/2898670/8b703a73-4039-4ae1-b355-fbeafa35b5b9">

Here is my neogit config:

```
require('neogit').setup{
  integrations = {
    diffview = true,
  },
  mappings = {
    status = {
      ["$"] = "",
      ['b'] = "",
    }
  }
}
```

**Comment by treatybreaker** [comment]
@hiberabyss This bug will affect anything on `master` currently, try using the branch [here](https://github.com/treatybreaker/neogit/tree/refactor/mappings) if you don't want to wait for a fix. That branch may take a bit to get merged as the changes are quite large.

If you want to use that branch though, you'd set those mappings like so:
```lua
require('neogit').setup{
  integrations = {
    diffview = true,
  },
  mappings = {
    status = {
      ["CommandHistory"] = "$", -- Replace $ with whatever key you want to bind to
      ["BranchPopup"] = "b", -- Replace b with whatever key you want to bind to
    }
  }
}
```

**Comment by hiberabyss** [comment]
Is it possible to split the bug fix into a separate MR and got merged?

**Comment by treatybreaker** [comment]
The bug fix is more of a consequence of the major refactoring that is occurring in that branch. 

The bugfix *is* the breaking change from that branch in making the mappings set based on the command not the keys.

So unfortunately, it's not exactly viable to split it away.

**Comment by hiberabyss** [comment]
Make sense. I'll comment the custom mappings temporarily and waiting for the MR to be merged.

Maybe the bug need to be mentions in the readme to avoid others facing the same problem.

Thanks for your great job! It's really useful.

**Comment by treatybreaker** [comment]
@hiberabyss  The latest changes on master should work with your bindings now.

#659 was merged resolving issues related to this. To disable mappings with the new changes just set the key you want unbound to `false`.

**Comment by hiberabyss** [comment]
It works. Thanks!

**Comment by treatybreaker** [comment]
Thanks @ten3roberts 😉

**Comment by kitallen23** [comment]
I'm trying to set a key to `false`, but get the error:
```
Config value: `mappings.status['u']` had error -> Expected `mappings.status['u']` to be of type 'string', got 'boolean'
stack traceback:
        [C]: in function 'error'
        ...nvim/site/pack/packer/start/neogit/lua/neogit/config.lua:567: in function 'setup'
        .../share/nvim/site/pack/packer/start/neogit/lua/neogit.lua:32: in function 'setup'
        /Users/kit/.config/nvim/init.lua:610: in main chunk
```

Worth mentioning is that my lua linter is telling me:
```
Cannot assign `boolean` to `"BranchPopup"|"CherryPickPopup"|"Close"|"CommandHistory"|"CommitPopup"...(+33)`.
```

I've just updated this package. I also tried uninstalling / reinstalling, to no avail.

My entire setup is:
```
require("neogit").setup {
    mappings = {
        status = {
            ["u"] = false,
            ["S"] = "Unstage",
        }
    }
}

```

**Comment by CKolkey** [comment]
@treatybreaker could you take a look when you have a minute?

**Comment by CKolkey** [comment]
You don't need to navigate in the popups though, everything is bound to a key - args/options have a prefix, `-` or `=` :)

**Comment by mangelozzi** [comment]
> You don't need to navigate in the popups though, everything is bound to a key - args/options have a prefix, `-` or `=` :)
> 
> ... but yea, stability is the goal. I don't foresee that specific thing changing anytime soon.

Thanks for this info will look into it. I currently browse files in this way:  Say I have like 80 changed files, and I am paging through them with `<C-f>` or `<C-b>`, then I may wish to go towards the bottom of the screen or middle to check some changes in files around there.

**Comment by CKolkey** [comment]
> > You don't need to navigate in the popups though, everything is bound to a key - args/options have a prefix, `-` or `=` :)
> 
> > 
> 
> > ... but yea, stability is the goal. I don't foresee that specific thing changing anytime soon.
> 
> 
> 
> Thanks for this info will look into it. I currently browse files in this way:  Say I have like 80 changed files, and I am paging through them with `<C-f>` or `<C-b>`, then I may wish to go towards the bottom of the screen or middle to check some changes in files around there.

Ah, ok, maybe we have a wire crossed. Per our nomenclature, a popup is one of the menus, like the buffer popup, commit popup, etc, that has different actions.

The view of all the changed files is the status buffer. Its an arbitrary distinction, since in vim terms they're both buffers, but the popups are more transient. 

Anyways, on the status buffer, the keymapping api has been pretty stable, but if there's a specific change that was annoying I'll take the feedback. 

Maybe its of value to you: you can use 1, 2, 3, 4 to set the fold level of everything, and {, } to navigate between items/hunks. Donno if that fits your use case, but maybe it could help :)

**Comment by mangelozzi** [comment]
> > > You don't need to navigate in the popups though, everything is bound to a key - args/options have a prefix, `-` or `=` :)
> > 
> > 
> > > 
> > 
> > 
> > > ... but yea, stability is the goal. I don't foresee that specific thing changing anytime soon.
> > 
> > 
> > Thanks for this info will look into it. I currently browse files in this way:  Say I have like 80 changed files, and I am paging through them with `<C-f>` or `<C-b>`, then I may wish to go towards the bottom of the screen or middle to check some changes in files around there.
> 
> Ah, ok, maybe we have a wire crossed. Per our nomenclature, a popup is one of the menus, like the buffer popup, commit popup, etc, that has different actions.
> 
> The view of all the changed files is the status buffer. Its an arbitrary distinction, since in vim terms they're both buffers, but the popups are more transient.
> 
> Anyways, on the status buffer, the keymapping api has been pretty stable, but if there's a specific change that was annoying I'll take the feedback.
> 
> Maybe its of value to you: you can use 1, 2, 3, 4 to set the fold level of everything, and {, } to navigate between items/hunks. Donno if that fits your use case, but maybe it could help :)

Thanks for the info, didnt know about  `{` and `}`! Maybe you should ignore what I said, you are making such great progress that I wouldnt want to slow you down. Just a thought ... for example I see recently the `hidden` key was added to each table within `sections`. This breaks peoples old config as they won't have the `hidden` key. Maybe for new config parameters, if they are not present, you choose a sensible default, so in this case, something like `false`, or `true`, or even the value of `folded`.

Cheers mate!
