### ISSUE TITLE
Unable to open popups from outside of Neogit

### ISSUE THREAD

**Issue by gegoune** [NeogitOrg/neogit#637]
### Description

I uset to have mappings such as `vim.keymap.set('n', '<leader>gc', neogit.popups.commit.create)` to create popups even from outside Neogit's buffer.

I also have a problem with opening popups with `:Neogit kind=pull` from outside of Neogit's buffer - nothing happens, intro screen disappears and that's it, no popup show up. It also doesn't work from within Neogit's buffer, same thing, nothing happens.

### Neovim version

NVIM v0.10.0-dev-682+gd0d132fbd-Homebrew
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

macOS 13.4.1 

### Steps to reproduce

1. Open nvim with minimal config
2. Run `:lua require('neogit').popups.commit.create()`

### Expected behavior

Open commit popup.

### Actual behavior

```
E5108: Error executing lua [string ":lua"]:1: attempt to index field 'commit' (a nil value)
stack traceback:
        [string ":lua"]:1: in main chunk
```

### Minimal config

```Lua
for name, url in pairs({
    neogit = "https://github.com/NeogitOrg/neogit",
    plenary = "https://github.com/nvim-lua/plenary.nvim",
    telescope = "https://github.com/nvim-telescope/telescope.nvim",
}) do
	local install_path = vim.fn.fnamemodify("/tmp/nvim_issue/" .. name, ":p")
	if vim.fn.isdirectory(install_path) == 0 then
		vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
	end
	vim.opt.runtimepath:append(install_path)
end

require("neogit").setup()
print("Minimal Config Ready!")
```

**Comment by CKolkey** [comment]
https://github.com/NeogitOrg/neogit/pull/601#issuecomment-1640265453

> ```lua
> vim.keymap.set('n', '<leader>gc', neogit.popups.open("commit"))
> ```
> 
> Would be enough if you do not want to pass extra data to the popup create function.

Looks like this was slightly more breaking than we realized - sorry about that.

**Comment by gegoune** [comment]
Not a problem at all! :) Thanks for all your work, really nice to see this plugin getting another life!

API call from mapping above also doesn't work, nothing happens when called.

**Comment by ten3roberts** [comment]
What happens if you do directly?

```vimscript
:lua require"neogit.popups".open("commit")()
```

**Comment by gegoune** [comment]
That works, thanks. I need to apologise - I wrongly assumed you forgot to wrap [that call](https://github.com/NeogitOrg/neogit/pull/601#issuecomment-1640265453) in function. Should have not doubted you!

However, running `lua require"neogit.popups".open("pull")()` results in

```
E5108: Error executing lua ...pack/packer/start/neogit/lua/neogit/popups/pull/init.lua:26: attempt to concatenate local 'current' (a nil value)
stack traceback:
	...pack/packer/start/neogit/lua/neogit/popups/pull/init.lua:26: in function 'c'
	...site/pack/packer/start/neogit/lua/neogit/popups/init.lua:8: in function 'f'
	...site/pack/packer/start/neogit/lua/neogit/popups/init.lua:17: in function <...site/pack/packer/start/neogit/lua/neogit/popups/init.lua:11>
	[string ":lua"]:1: in main chunk
```

**Comment by CKolkey** [comment]
Ah, "current" is the current branch name. If you haven't launched neogit yet, the repo hasn't been initialized. I think that's it's own bug-report.

**Comment by gegoune** [comment]
Ah, I see, so this is also different behaviour from before as this worked before. Would you like me to open separate issue for that (I did call it before opening Neogit, yes, this is most of the times my workflow)?

**Comment by CKolkey** [comment]
To cut down on repeated CLI calls, I started using more of the internal state that we build for the repository. This gets constructed before the status buffer is built, and updated frequently, but... if you never opened the status buffer, it's an empty table, essentially. 

If you could open a separate issue to track that, I'd appreciate it :)

**Comment by gegoune** [comment]
My pleasure! Opened. I will close this one now as my initial issue is resolved, thank you!
