### ISSUE TITLE
plenary error remapping `Toggle`

### ISSUE THREAD

**Issue by jamestrew** [NeogitOrg/neogit#661]
### Description

Remapping the "Toggle" action to `=` seems to be throwing plenary async error:
```
Error executing vim.schedule lua callback: ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine failed wit
h this message: vim/shared.lua:0: The reverse lookup found an existing value for "Toggle" while processing key "<tab>"
stack traceback:
        [C]: in function 'error'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:18: in function 'callback_or_next'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:45: in function <...ck/packer/start/plenary.nvim/lua/plenary/as
ync/async.lua:44>
```

I've git bisect'ed this issue to https://github.com/NeogitOrg/neogit/pull/618/commits/b57d5ee08be53a2c4ca35c1a7d4efe7cac0498a7

### Neovim version

NVIM v0.10.0-dev-653+gfbeef0d4e
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system and version

Linux archlinux 6.4.3-arch1-1

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. `:lua require("neogit").open()

### Expected behavior

No error and the ability to map `["="] = "Toggle"`

### Actual behavior

Error from above gets thrown and none of the neogit functionality is functional.

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup({
            mappings = { status = { ["="] = "Toggle" } },
          })
          vim.keymap.set("n", "<space>gs", require("neogit").open)
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by treatybreaker** [comment]
Seems to be related to #635. This is because the reverse mapping has two `Toggle` values and fails.

To work around this @jamestrew, you can try disabling `Toggle` mapping like so:
```lua
require("neogit").setup({
    mappings = {
        status = {
            ["="] = "Toggle",
            ["<tab>"] = "",
        },
    },
})
```

**Comment by treatybreaker** [comment]
@jamestrew The latest changes on master should work with your bindings now.

#659 was merged. To disable the mapping just set the key you don't desire to `false`.

**Comment by gegoune** [comment]
Tiny nitpick, sorry. :)
Disabling with `['<tab>'] = false` works while `['<Tab>'] = false` doesn't. Just so you know in case it causes some other issues.

**Comment by ten3roberts** [comment]
Oh good catch

The classic casing mismatch.

I'll jump on and fix it up in a little bit

**Comment by jamestrew** [comment]
I'm able to remap `Toggle` naturally now. 
Feel free to close this issue. Thanks everyone :+1:
