### ISSUE TITLE
Diffview integration cannot show diff for lazy-lock.json file

### ISSUE THREAD

**Issue by TroySigX** [NeogitOrg/neogit#662]
### Description

When I update the `lazy-lock.json` file in which a few lines in the file change, I'd open `Neogit` and toggle `Diffview` to see the diff. But I always get this error: `[Diffview.nvim] Failed to create diff buffer: ':0:lazy-lock.json'`. The standalone `Diffview` works just fine without errors.

### Neovim version

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

6.4.4-arch1-1

### Steps to reproduce

1. Update plugins using `lazy.nvim`, which will then updates the `lazy-lock.json` file
2. Open `Neogit`
3. Navigate to the `lazy-lock.json` file, and toggle `Diffview`

### Actual behavior

The mentioned error is shown

### Minimal config

```Lua
local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    'https://github.com/folke/lazy.nvim.git',
    '--branch=stable',
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

vim.loader.enable()

require('lazy').setup({
  {
    'NeogitOrg/neogit',
    dependencies = {
      'sindrets/diffview.nvim',
      'nvim-lua/plenary.nvim',
    },
    lazy = true,
    config = function()
        require('neogit').setup({
            disable_commit_confirmation = true,
            kind = 'tab',
            auto_show_console = false,
            popup = {
              kind = 'vsplit',
            },
            integrations = {
              diffview = true,
            },
        })
    end,
  },
})
```

**Comment by CKolkey** [comment]
Sounds like an issue for Diffview :\
