### ISSUE TITLE
Spin off branch

### ISSUE THREAD

**Issue by ten3roberts** [NeogitOrg/neogit#665]
**Is your feature request related to a problem? Please describe.**
Allow creating a new branch from the current branches unpushed/unmerged changes.

A common example is making commits to `main`, which are not pushed to `origin`, and *then* creating a branch with those commits and resetting `main` to `origin/main`. I've found myself reaching for this feature very often, as I often start just coding and forgetting to create a branch, or don't know what feature I will make yet.

**Describe the solution you'd like**

Magit uses `b s` and `b S` 

https://magit.vc/manual/magit/Branch-Commands.html

Contributions are very welcome

**Comment by morgsmccauley** [comment]
🙋🏼‍♂️ I'd like to pick this up! I don't have a lot of time so may take a little while, hope that's ok!

**Comment by ten3roberts** [comment]
I'd be more than happy if you do that. Slow and steady wins the race
