### ISSUE TITLE
Switch git directory of the neogit tab on the fly

### ISSUE THREAD

**Issue by 616b2f** [NeogitOrg/neogit#668]
**Is your feature request related to a problem? Please describe.**
I try to switch repositories on the fly with `:Neogit cwd=~/myfirstrepo` and after that with `:Neogit cwd=~/mysecondrepo`, but after the second command the tab where neogit is open does not switch to that directory.

**Describe the solution you'd like**
I wan't the neogit tab to be pointing to "~/mysecondrepo" after the second command.

**Describe alternatives you've considered**
can't think of any alternative right now.

**Additional context**
-

**Comment by treatybreaker** [comment]
I'll take a look into this a bit later today. I haven't actually looked at any of the `cwd` code, but I imagine it isn't a major patch.

**Comment by treatybreaker** [comment]
Well it's later "today" as in 2 days. But I'm looking here shortly after I get some dinner.

**Comment by 616b2f** [comment]
> Well it's later "today" as in 2 days. But I'm looking here shortly after I get some dinner.

No worry, I really appreciate you taking time to fix it, many thanks!
