### ISSUE TITLE
This commit has already been published to nil, do you really want to modify it?

### ISSUE THREAD

**Issue by fnune** [NeogitOrg/neogit#669]
### Description

When amending a commit, this message is shown even if the commit hasn't been pushed to a remote yet:

```
This commit has already been published to nil, do you really want to modify it?
```

### Neovim version

nvim --version
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info

### Operating system and version

Debian sid

### Steps to reproduce

1. Make a commit
2. Try to amend it before having pushed it

### Expected behavior

- No prompt shows, saving a keystroke

### Actual behavior

- Prompt shows uselessly

### Minimal config

```Lua
-
```

**Comment by CKolkey** [comment]
Good catch!

**Comment by fnune** [comment]
TY!
