### ISSUE TITLE
[Feature] Allow setting default setting values

### ISSUE THREAD

**Issue by briandipalma** [NeogitOrg/neogit#673]
**Is your feature request related to a problem? Please describe.**
I'm constantly amending a commit and pushing it up to my remote branches while working. So I have to select `--force-with-lease` all the time.

**Describe the solution you'd like**
I'd like to be able to be to either pass in options to the popup via the open call

```neogit.open({ "push" })```

or be able to set the default setting value via config in someway.

**Describe alternatives you've considered**
Always selecting the flag or just use lazygit for pushing which I can configure with default settings. It is just a push operation after all.

**Comment by CKolkey** [comment]
So I _think_ we can already do that. Check out the `ignored_settings` table in the config. 

https://github.com/NeogitOrg/neogit/blob/master/lua/neogit/config.lua#L92C3-L98C5

We ignore some stuff by default, specifically the `force` and `force-with-lease` flags, but if you pass an empty table there, those flags will be remembered next time you open that popup.

**Comment by briandipalma** [comment]
Thanks for the suggestion. It's almost what I want. It only persists it within the same directory/session though. I tend to use worktrees in my workflow so each worktree will still require me to toggle that flag on.

**Comment by CKolkey** [comment]
Hmm. You can set `use_per_project_settings = false` to just have a single set of global settings.

**Comment by briandipalma** [comment]
That works fine, thanks.
