### ISSUE TITLE
Missing Vimdocs

### ISSUE THREAD

**Issue by grassdne** [NeogitOrg/neogit#680]
Hey! Cool plugin! I noticed that your vim [documentation is horribly lacking](../blob/master/doc/neogit.txt) and wanted to let you all know that this is incredibly lame!

Just making sure you're aware 🙃

**Comment by CKolkey** [comment]
Perhaps you don't mean it, but your comment comes off as rude, and I don't appreciate it. 

That said, yes, the docs need work. Feel free to open a PR if you'd like to provide anything of value to this conversation, or you can wait for my one year old daughter to bang them out. She's almost done, just needs to learn how to talk first.
