### ISSUE TITLE
Add support for discard in visual mode

### ISSUE THREAD

**Issue by Shatur** [NeogitOrg/neogit#684]
**Is your feature request related to a problem? Please describe.**
Unlike stage, discard (`x`) currently works only in normal mode.

**Describe the solution you'd like**
It would be nice if discard could work in visual mode, like stage/unstage.
This is how it works in fugitive.

**Comment by Shatur** [comment]
Hm... Doesn't work for me. `x` in visual mode does nothing.

**Comment by ten3roberts** [comment]
Would this be fixed if you check out #777?

It is not fully done, but aims to refactor the visual selection amd normal mode logic for stage/unstage/discard and make then all consistent

**Comment by Shatur** [comment]
> selected a file or hunk header for example.

Yes, this is exactly what I select.

> Would this be fixed if you check out https://github.com/NeogitOrg/neogit/pull/777?

Yes, this is just what I need! I tried it out, it doesn't work work line by line as unstage works, but allows me to select multiple hunks at least.

**Comment by ten3roberts** [comment]
Yes. Currently fixing that now, as well as making sure everything else works.

This change also allows selection across sections, or files *and* hunks
