### ISSUE TITLE
Show error output console.

### ISSUE THREAD

**Issue by matheusfillipe** [NeogitOrg/neogit#686]
**Is your feature request related to a problem? Please describe.**
I want to be able to explore a git stderr output message. When there is an error the output comes as a floating window but  doesn't stick  for enough time to check errors. A typical use case is pre-commit. 

**Describe the solution you'd like**
Add an option to keep the output console shown.

**Comment by ten3roberts** [comment]
You should be able to open the console `#` to see the output.

Does that work for you?

**Comment by matheusfillipe** [comment]
Yes! Couldn't find this anywhere. Maybe this should be in the readme?
