### ISSUE TITLE
Neogit asking to initialise repository when it already exist

### ISSUE THREAD

**Issue by timjackleus** [NeogitOrg/neogit#688]
### Description

For the past few weeks, every time I run :Neogit within a repository, I receive a prompt that says Initialize repository in [path]. Notably, I'm using Lazyvim, but I've also tested with the provided minimal.lua and the behavior remains consistent.

Interestingly, when I select 'Yes' to initialize a repository, Neogit opens as anticipated. This indicates it does recognize the directory as a repository, but it prompts me each time regardless.

Any guidance on how to further debug this issue would be greatly appreciated!

### Neovim version

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

macOS 13.4.1

### Steps to reproduce

nvim -nu minimal.lua

### Expected behavior

To be presented the neogit "dashboard"

### Actual behavior

Prompt about if I want to initialise a Github repository or not, even though I'm inside one.

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "NeogitOrg/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by CKolkey** [comment]
If possible, can you describe how you're opening the repo? Are you passing a different cwd value? Is neovim opened in the root of the repo? That would be helpful.

**Comment by timjackleus** [comment]
Absolutely,
I'm always in the root of the repo just typing `nvim`.

**Comment by CKolkey** [comment]
Huh. Thats my workflow too. Is there anything strange about the repo setup? Like is it a bare repo or something weird like that. 

Oh, and whats the output of `git rev-parse --is-inside-work-tree` in that directory?

**Comment by timjackleus** [comment]
Thank you for your ongoing support!
Running the command you suggested returns `true` in all repositories. Interestingly, this helped me notice that the issue only occurs when I'm using Neogit within a Svelte.js repository. When I work within non-Svelte repositories, the problem disappears..

**Comment by timjackleus** [comment]
Just out of curiosity, was there a recent update that could have potentially resolved my issue? I keep my configuration pretty up-to-date, but since today's plugin update, the issue seems to have completely disappeared!

So happy to be able to use my #1 Neovim plugin again :) Thanks for all the support and hard work on this plugin!

**Comment by CKolkey** [comment]
https://github.com/NeogitOrg/neogit/pull/605 quite possibly solved it :) Glad to hear that it's fixed!
