### ISSUE TITLE
[bug/feature?] Keep focus in Neogit window after certain actions (e.g. branch change)

### ISSUE THREAD

**Issue by fnune** [NeogitOrg/neogit#689]
### Description

Recently, Neogit started focusing windows other than Neogit's after certain actions, e.g. checking out a branch.

In no cases is this what I want: I usually close the Neogit window after performing actions there, so to close it, now I have to focus it again and then close it.

Suggestion:

- Remove that refocusing behavior, defaulting to keeping the focus in the Neogit window
- Alternatively (I wouldn't use this option) make this configurable

### Neovim version

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info

### Operating system and version

Debian sid

### Steps to reproduce

1. Open Neogit in a `split`
2. Checkout some branch

### Expected behavior

Focus remains in the Neogit window

### Actual behavior

Focus is given to the other window, not Neogit's

### Minimal config

```Lua
-
```

**Comment by CKolkey** [comment]
Ahh, ok, so it looks like this occurs after leaving the telescope buffer, is that right?

**Comment by fnune** [comment]
Good catch, that's right. I tried another action, and even exiting the telescope buffer without confirming the action lands you on the other window.

**Comment by CKolkey** [comment]
Does this sort it out for you too? https://github.com/NeogitOrg/neogit/pull/690
