### ISSUE TITLE
Allow or document setting `base_branch` option

### ISSUE THREAD

**Issue by jssee** [NeogitOrg/neogit#692]
**Is your feature request related to a problem? Please describe.**
Most modern git repo's use "main" as the default base branch, and rebasing a feature branch onto the base branch is a fairly common operation. However neogit uses "master" as its default base branch, which is fine, but how a user can go about changing this option seems to be very obscured at the moment, if at all possible.  This makes `r b` basically unusable in most modern repos.

After some digging around, I found the option being set [here](https://github.com/NeogitOrg/neogit/blob/19936e9f3d6d7438b7b20a5960df6de0abfeb252/lua/neogit/popups/rebase/actions.lua#L11-L14), but I can't figure out how to actually change the value to "main". 

I have tried adding `base_branch = "main"` and `baseBranch = "main"` to my neogit lua config, and it doesnt work, and ive also tried adding 
```
[neogit]
  baseBranch = main
  ```
to my gitconfig, which also does not work.
  
**Describe the solution you'd like**
based on that code snippet i've linked, it seems to be possible to configure this but i cant seem to find any documentation about how to go about it. if its currently possible, then we should document it. if not, it would be nice to add that as an option, or possibly use a smarter default like the users own `git.config.init.defaultBranch` option.

**Comment by CKolkey** [comment]
You're right - the documentation is lacking. PR's welcome 😅 

There is an option in the branch-config popup to change this. `bC` then pick any branch. It's a default for the whole repo, so the branch doesn't matter in this case. Then use `b` to set the base branch.

<img width="805" alt="Screenshot 2023-08-02 at 16 59 29" src="https://github.com/NeogitOrg/neogit/assets/7228095/e673358b-8821-4c4f-ac1a-168e903aa805">

**Comment by jssee** [comment]
ah interesting. i had no idea these options were available, i wouldve opened a PR had i figured out how to get here. thanks!

is there a reason this is not an option that can be set globally in the plugin config, and then overridden in the `bC` menu on a per repo basis? Since the default option in the neogit codebase is not what is the default for most (newer) repo's, it seems this would provide a better experience for the majority of (newer) codebases.

**Comment by CKolkey** [comment]
Think I can do one better - https://github.com/NeogitOrg/neogit/pull/694 - if the config value isn't set, we'll check for the presence of `master` then `main` and if we find that they exist, use that value. If they don't, it's up to the user to manually set the value.

**Comment by jssee** [comment]
@CKolkey awesome stuff! thanks for taking the time to do this

**Comment by CKolkey** [comment]
of course :)
