### ISSUE TITLE
Update fails on docs generation

### ISSUE THREAD

**Issue by skoch13** [NeogitOrg/neogit#700]
### Description

When I try to update neogit it fails with the following error

![Screenshot 2023-08-04 at 13 50 40](https://github.com/NeogitOrg/neogit/assets/29177689/acd350b3-fb69-4211-a700-8a0ea0dad725)

### Neovim version

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.1/share/nvim"

### Operating system and version

macos 13.5

### Steps to reproduce

1. use LazyVim
2. update a plugin via lazy.nvim

### Actual behavior

Shown on the screenshot attached

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by ten3roberts** [comment]
You will most likely have to follow this https://github.com/NeogitOrg/neogit/issues/649#issuecomment-1653931405

**Comment by CKolkey** [comment]
That's my bad. Thanks for the heads up
