### ISSUE TITLE
Example config in the readme has an error

### ISSUE THREAD

**Issue by RoryNesbitt** [NeogitOrg/neogit#707]
### Description

[Readme line 234](https://github.com/NeogitOrg/neogit/blob/master/README.md?plain=1#L234) shows assigning `select` to a keybind. This needs to be capitalised or it throws an error on startup

### Neovim version

n/a

### Operating system and version

n/a

### Steps to reproduce

1. Read the readme
2. profit

### Actual behavior

Error on startup if using this binding

### Minimal config

n/a

**Comment by CKolkey** [comment]
Thanks!
