### ISSUE TITLE
Cannot set a section to `false` to disable it

### ISSUE THREAD

**Issue by SidOfc** [NeogitOrg/neogit#712]
### Description

Whenever I open Neovim I'm getting this error:

```plain
.../neogit/lua/neogit/config.lua:392: attempt to index local 'section' (a boolean value)
```

Which stems from this configuration:

```lua
require('neogit').setup({
  -- other config
  sections = {
    recent = false,
  },
})
```

When I remove above configuration the error disappears.
This configuration is documented in the project README.md.

Neogit does still function but the highlighting also breaks because of this.

### Neovim version

NVIM v0.10.0-dev-4791+gef44e5972-Homebrew
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

MacOS Ventura 13.4.1 (c)

### Steps to reproduce

1. Navigate to a git repo and copy `minimal.lua` to this directory
2. `nvim -nu minimal.lua`
3. Observe error in status bar

### Expected behavior

No error message and working highlighting

### Actual behavior

Receiving error message mentioned in description, Neogit shows no highlighting but does still function.

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup({
            sections = { recent = false }
          })
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by CKolkey** [comment]
Yup, sorry about that. You can now set `{ hidden = true }` for the section to hide it.

**Comment by SidOfc** [comment]
No problem, I always see a big commit log so a lot of work is being done, love the effort and Neogit (I really liked Magit but it didn't receive much maintenance). After updating the plugin and my configuration it's working like a charm once again.

Thank you for the quick fix, have a good one!
