### ISSUE TITLE
Display diffs for renamed files

### ISSUE THREAD

**Issue by Shatur** [NeogitOrg/neogit#715]
**Is your feature request related to a problem? Please describe.**
Sometimes if I move / rename a file, I also make some changes to it. It would be great to be able to see such changes.

**Describe the solution you'd like**
Display diffs for renamed files as usual like in fugitive.

**Comment by CKolkey** [comment]
It...does? You just have to be sure to stage both the creation of the new file, and the removal of the old one.

<img width="629" alt="Screenshot 2023-08-07 at 22 54 46" src="https://github.com/NeogitOrg/neogit/assets/7228095/4dc7786a-8b0d-4303-a524-124c39fd617f">

**Comment by Shatur** [comment]
Sorry, but under diffs I meant actual changes inside the renamed files. For example, you can rename the file and change a single line inside it. If you use `git diff --cached` it will display not only rename, but also changes in the renamed file.

**Comment by CKolkey** [comment]
Turns out it was actually pretty straightforward to add a special case for renamed files :)
