### ISSUE TITLE
Please restore kind=replace config option

### ISSUE THREAD

**Issue by festeh** [NeogitOrg/neogit#718]
### Description

Hi!

It seems that after #674 `kind=replace` config is disallowed, I hope that's just a bug. I suggest to restore it. As that's only in validation logic, it's trivial to fix it, but I can make a PR if you'd like.

### Neovim version

latest

### Operating system and version

linux

### Steps to reproduce

set kind=replace

### Actual behavior

validation error

### Minimal config

```Lua
require("neogit").setup{
  kind = "replace",
}
```

**Comment by CKolkey** [comment]
I think this was just a minor oversight - feel free to open a PR :)
