### ISSUE TITLE
[telescope picker] First two branches in select UI are sometimes invisible

### ISSUE THREAD

**Issue by fnune** [NeogitOrg/neogit#727]
### Description

![image](https://github.com/NeogitOrg/neogit/assets/16181067/7af8641b-68cd-4837-9a46-0c8ba092c566)

- This still happens when I switch colorschemes
- This only happens sometimes (about 30% of the time)
- The telescope picker allows me to pick the invisible items
- But they're invisible (duh)

### Neovim version

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

Debian 12 stable

### Steps to reproduce

- Open the telescope branch picker (`bl`)
- Do it enough times until this happens

### Expected behavior

- All list items are visible

### Actual behavior

- First two items are invisible

### Minimal config

```Lua
-
```

**Comment by fnune** [comment]
Ha! I think I have some more information.

If I hit `bl` fast enough, the bug reproduces.

If I leave some time between the `b` and the `l` for the popup to display, then it doesn't happen!

**Comment by fnune** [comment]
Funky: I disabled Telescope integration, and there's a _similar_ bug.

Here is the result when I do `bl` slowly:
![image](https://github.com/NeogitOrg/neogit/assets/16181067/ff8604bb-e7d0-4ea9-9be0-068793f116f9)

Here it is when I do it quickly:
![image](https://github.com/NeogitOrg/neogit/assets/16181067/cf527dbf-4fd4-43c3-9e4d-4164034f15ba)

I'm suspecting it's simply a matter of Neovim expecting some window to be open in order to resize it, but since I went too fast, it resized something else instead.

**Comment by CKolkey** [comment]
Ohh.. yeah, thats exactly whats happening haha. https://github.com/NeogitOrg/neogit/blob/master/lua/neogit/lib/popup/init.lua#L587-L589

Should probably check that the focused window is what we expect.

**Comment by fnune** [comment]
Awesome! <3
