### ISSUE TITLE
Worktree support

### ISSUE THREAD

**Issue by ten3roberts** [NeogitOrg/neogit#733]
# What they are
Git has a neat feature of *worktrees* where separate branches can co-exist in different subdiretories of the `.git` folder. All the editing then happens inside each of the relevant subdirectories, rather than at the root.

# Benefits
Worktrees allow you to have multiple branches "checked out" at the same time rather than just the one, with stashing, popping and forgetting to move between them during mid-development. This allows you to quickly switch what you are working on or checkout a piece of code in another branch.

Additionally, the build folder and other artifacts will be per-subdirectory and branch, which means that there is no recompilation or pollution of untracked files or missing node modules when switching between branches

# Plans
Neogit currently has very poor support for worktrees and bare repos, and is also lacking a popup and configuration view for adding and removing subtrees.

This feature (along with the bare repo) support has been half-requested for some time, though now after *The Merge* and all the improvements in our library and ui we are in a much better state to support this feature with a lot less complexity required to do so.

Feel free to comment below what you would like to have added and how your workflow for worktrees to look like such that we can make them possible 😊

**Comment by CKolkey** [comment]
Heh, `The Merge`.

I looked into this yesterday - it didn't look crazy complex, compared to, say, stashing. The Magit (https://github.com/magit/magit/blob/main/lisp/magit-worktree.el) functions are _mostly_ just wrappers around the git CLI.

The biggest challenge we'll have is that Magit opens a file-drawer (dired) like https://github.com/nvim-telescope/telescope-file-browser.nvim, which I don't feel like vendoring. _But_ if we stick to `vim.fn.input()` with nice autocompletion for filepaths I think that would suffice for a first draft.

**Comment by Clumsy-Coder** [comment]
ThePrimeagen made a video on this. Hoping to have neogit work in similar fashion.

https://www.youtube.com/watch?v=2uEqYw-N8uE&t=187s&pp=ygUMZ2l0IHdvcmt0cmVl

**Comment by frixaco** [comment]
Thanks for considering better worktree/bare repo support.

It'd be amazing to have this feature! It's currently the only feature that's stopping me from fully switching to Neogit.

**Comment by CKolkey** [comment]
https://github.com/NeogitOrg/neogit/pull/1066
