### ISSUE TITLE
Reset should open branch opener

### ISSUE THREAD

**Issue by troglotit** [NeogitOrg/neogit#738]
**Is your feature request related to a problem? Please describe.**
I am used to a workflow for reset to open a branch select menu. I know that current log opener can be more useful to some people, and, to be fair, typing `HEAD^^^` into branch select menu is not perfect, but my workflow of `SPC g g O h origin/develop` is already in my muscle memory.

**Describe the solution you'd like**
I'd like to neogit to open branch opener when I choose where to reset.

**Describe alternatives you've considered**
Leave it as it is, seems like branch opener menu is not capable of chewing branch names, `HEAD^^~^~^`, and hashes. (Which Git CLI is kinda expects)

**Additional context**
Image of Magit reset menu working with general git objects
![image](https://github.com/NeogitOrg/neogit/assets/10955264/5cfba771-8ef1-401d-a99f-d81a89b820a9)

**Comment by CKolkey** [comment]
Yeah, so this is two things:
1. The fuzzy finder doesn't work with git objects. It should - thats on the roadmap to add.
2. If you want to reset a branch to another branch - if I understand you right - then use `bX` and choose the branch you want to reset the current one to. Lemme know if thats what you had in mind.

**Comment by troglotit** [comment]
Thank you very much, that's exactly what I needed!
