### ISSUE TITLE
Show current local and remote commit hashes in NeogitStatus

### ISSUE THREAD

**Issue by mambusskruj** [NeogitOrg/neogit#753]
**Is your feature request related to a problem? Please describe.**
Yes, it's nice to show commit message header for local and remote sources, but in addition it would be nice to also include commit hash, so user will know if commits are identical.

**Describe the solution you'd like**
Show current local and remote commit hashes in NeogitStatus

**Comment by CKolkey** [comment]
Could be cool to have as an option, sure

**Comment by mambusskruj** [comment]
Yeah, because with commit amend it can starts to be confusing.

**Comment by CKolkey** [comment]
Makes sense. Though, with an ammended HEAD, you'll see both the "unpulled" and "unpushed" sections appear. 

Regardless, its a good idea.

**Comment by ten3roberts** [comment]
I started of this in that it shows the commit ref if you are in a detached HEAD state.

Do you think that the same format could be used for the normal HEAD states? Or would you consider changing it to something else?

**Comment by mambusskruj** [comment]
Thank you! I think its time to close the issue.
