### ISSUE TITLE
Setting a section to false will cause a crash

### ISSUE THREAD

**Issue by TheodorRene** [NeogitOrg/neogit#760]
### Description

I've disabled stashes in my config like so:

```lkua
require('neogit').setup {
    -- kind="floating",
    disable_commit_confirmation = true,
    disable_hint = true,
    integrations = {diffview = true},
    sections = {stashes = false}
}
```

In a recent update this gave me: 
```
Error detected while processing /home/theodorc/.config/nvim/init.vim:
line   14:
E5108: Error executing lua ...nvim/site/pack/packer/start/neogit/lua/neogit/config.lua:398: attempt to in
dex local 'section' (a boolean value)
stack traceback:
        ...nvim/site/pack/packer/start/neogit/lua/neogit/config.lua:398: in function 'validate_sections'
        ...nvim/site/pack/packer/start/neogit/lua/neogit/config.lua:568: in function 'validate_config'
        ...nvim/site/pack/packer/start/neogit/lua/neogit/config.lua:597: in function 'setup'
        .../share/nvim/site/pack/packer/start/neogit/lua/neogit.lua:32: in function 'setup'
        /home/theodorc/.config/nvim/lua/plugin_conf.lua:43: in main chunk
        [C]: in function 'require'
        [string ":lua"]:4: in main chunk
Press ENTER or type command to continue
```

Using the `{folded=false}` option fixes the crash, but not my issue. The README indicates that setting the whole section to false will not render the section

### Neovim version

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info

### Operating system and version

Ubuntu 22.04.1 LTS

(Very pleased with the plugin btw!)

**Comment by CKolkey** [comment]
Yup, sorry about that. You can now set `{ hidden = true }` for the section to hide it.

**Comment by TheodorRene** [comment]
No problem. Thanks!
