### ISSUE TITLE
Set `nolist` in popup windows to avoid visual noise

### ISSUE THREAD

**Issue by sotte** [NeogitOrg/neogit#770]
**Is your feature request related to a problem? Please describe.**
Popup windows don't set `nolist` and therefore can contain visual noise. See the `-` at the bottom right after "Edit", "Augment", and "Instant fixup"
![image](https://github.com/NeogitOrg/neogit/assets/79138/ea45b5f8-1ef7-4d5e-80ee-1ece70055797)

**Describe the solution you'd like**
Set `nolist` for all popup windows.

**Describe alternatives you've considered**
Have an autocommand for all the popup filetypes that set `nolist`

**Additional context**
Tested with current version: 1c8a67839dd1e7cc8ae3366cbe1a02ae315f1650

After setting `nolist` the popup looks like this:
![image](https://github.com/NeogitOrg/neogit/assets/79138/603abd47-b502-4225-882b-094ee1e1fde2)

**Comment by CKolkey** [comment]
Oh, yeah, thats a good call.

**Comment by sotte** [comment]
I think this should fix it. I'll create a MR.

![image](https://github.com/NeogitOrg/neogit/assets/79138/e58097ba-54c2-4c2c-b701-4b25b3a84510)

**Comment by sotte** [comment]
Scratch that, you're faster than me ;)

Thanks for the quick fix!

**Comment by CKolkey** [comment]
Hahaha, all good, I just happened to open my laptop a second ago. Thanks for the good idea :)
