### ISSUE TITLE
Don't use "k" as key for an action

### ISSUE THREAD

**Issue by titouancreach** [NeogitOrg/neogit#775]
### Description

<img width="922" alt="Screenshot 2023-08-22 at 10 31 48" src="https://github.com/NeogitOrg/neogit/assets/3995719/d6d60ef3-1bad-4ef8-b0ef-50a90a9e29ae">

In rebase popup (`ll` for exemple the `r`)

`k`  is bind to "remove a commit" but
  - "hjkl" shouldn't be an action since they are used to navigate 
  - when I press "k", it says it's not a implemented feature

### Neovim version

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

macOs

### Steps to reproduce

1. :Neogit
2. ll
3. choose a commit
4. r

### Expected behavior

k should go up

### Actual behavior

k shows a popup telling me it's an unimplemented feature

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by CKolkey** [comment]
Right, but you don't _need_ to navigate in the popup buffers. Everything can be triggered directly via a keybinding. The arguments and options take a prefix (`-` or `=`), then the letter. `k` is bound to the not-yet-implemented action "remove commit".

Out of curiosity, why do you want to navigate up and down? Maybe there a documentation issue here.

**Comment by titouancreach** [comment]
Ohhh, I was navigating up and down and pressing tab to toggle arguments (instead of pressing `-` then argument key)

**Comment by CKolkey** [comment]
Of course :)
