### ISSUE TITLE
Fails to start: status.lua:204: attempt to concatenate field 'abbrev'

### ISSUE THREAD

**Issue by fnune** [NeogitOrg/neogit#779]
### Description

```
Error executing vim.schedule lua callback: ...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine failed with this message: ...usto/.loca
l/share/nvim/lazy/neogit/lua/neogit/status.lua:204: attempt to concatenate field 'abbrev' (a nil value)
stack traceback:
        [C]: in function 'error'
        ...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:18: in function 'callback_or_next'
        ...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:45: in function <...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:44>
```

When launching Neogit

### Neovim version

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info

### Operating system and version

Debian unstable

### Steps to reproduce

- Open neogit

### Expected behavior

- Neogit opens

### Actual behavior

- Neogit crashes

### Minimal config

```Lua
-
```

**Comment by CKolkey** [comment]
Think I know whats up. Thanks for the tip :)

**Comment by CKolkey** [comment]
@fnune Do you mind testing if that solves it?

**Comment by fnune** [comment]
Yup that works. TY!
