### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by theherk** [NeogitOrg/neogit#783]
**Is your feature request related to a problem? Please describe.**
Tagging doesn't seem to be implemented yet.

**Describe the solution you'd like**
I'd enjoy a tagging interface just like [Magit's tagging](https://magit.vc/manual/magit/Tagging.html).

**Describe alternatives you've considered**
For the moment I just use the CLI or LazyGit.

**Additional context**
It could be that this is already implemented, and I'm blind but I don't see it, nor conversations about it, and I didn't see it in the `umbrella` list.

**Comment by CKolkey** [comment]
Yup! Not implemented yet. It's on the roadmap, but it's also a good first issue if someone wants to take a swing at it.

**Comment by jarviliam** [comment]
I can pick up the basic tagging popup

**Comment by CKolkey** [comment]
Nice :D lemme know if you have any questions
