### ISSUE TITLE
[feat] Current behavior of `x` on stashes confusing; support `x` on stashes?

### ISSUE THREAD

**Issue by fnune** [NeogitOrg/neogit#791]
**Is your feature request related to a problem? Please describe.**

Trying to use `x` on a stash is slightly deceptive:

![image](https://github.com/NeogitOrg/neogit/assets/16181067/453212b2-9166-4923-9052-053f61c284c4)

Here, I typed in `y` to discard the stash but nothing happened. This is because (I assume) `x` only works on hunks, and stashes cannot be "discarded" but should be "dropped" instead.

**Describe the solution you'd like**

Either:

- `x` works on stashes to drop them, or
- `x` does not work on stashes and does not prompt the users to discard at all.

**Comment by ten3roberts** [comment]
Yes, the status buffer stags/unstage/discard ars quite full of special cases and only really handles things predictable (somewhat) in a few sections.

I am working on refactor those to make it more consistent in #777.

Thanks for letting me know about this 😊

**Comment by fnune** [comment]
Thanks awesome! Thanks for your work :bow:

**Comment by kskarthik** [comment]
I'm eagerly waiting for this fix to land!

**Comment by fnune** [comment]
Thanks @CKolkey!
