### ISSUE TITLE
Saving popup configurations

### ISSUE THREAD

**Issue by TimUntersberger** [NeogitOrg/neogit#80]
As a user I would like to configure the popup once and then reuse my default configuration whenever using the popup.

**Comment by TimUntersberger** [comment]
Maybe this could be realized using the git config?

**Comment by mrswats** [comment]
I would expect something like this to be configurable through the setup function and have a default it being "tab".

**Comment by TimUntersberger** [comment]
> I would expect something like this to be configurable through the setup function and have a default it being "tab".

What do you mean? What should be "tab"?

**Comment by mrswats** [comment]
Yeah, so that if I want to use vsplit when I type `:Neogit` it opens in vsplit instead of having to remap it.

**Comment by TimUntersberger** [comment]
@mrswats `Neogit kind=vsplit`.

**Comment by soywod** [comment]
> Maybe this could be realized using the git config?

Indeed, it could be interesting to _visually_ enable/disable switches and activate/deactivate options depending on the user's git config!

**Comment by melkster** [comment]
Perhaps as a starting point it would be easiest to allow configuring the default options when calling `setup()`?

**Comment by sotte** [comment]
I want to be able to change some defaults. This feature request is a bit stale. There is this MR which outlines a possible solution, quite a nice one.
https://github.com/TimUntersberger/neogit/pull/167

One could also just use the existing config system and add switches/options for each popup section.

I'll outline a solution for the `commit_popup`.

https://github.com/TimUntersberger/neogit/blob/master/lua/neogit/config.lua#L18
```lua
  commit_popup = {
    kind = "split",
    switches = {
      all = false,
      allow_empty = false,
      verbose = false,
      no_verify = false,
      -- ...
    },
    options = {
      author = nil,
      -- ...
    }
  }

```
And then use the config when defining the UI
https://github.com/TimUntersberger/neogit/blob/1acb13c07b34622fe1054695afcecff537d9a00a/lua/neogit/popups/commit.lua#L40
```lua
    -- before
    -- :switch("v", "verbose", "Show diff of changes to be committed", false)
    -- after:
    :switch("v", "verbose", "Show diff of changes to be committed", config.values.commit_popup.switch.verbose),
```

This is a pretty simple solution.

What do you think?

**Comment by chrisgrieser** [comment]
I came here for the same request basically. 99% of the time, I use the same set of configs for committing, so popup feels a bit  tedious. I like the suggestion by @sotte

**Comment by CKolkey** [comment]
Settings are now persistent on master, with the possibility to ignore specific flags.

**Comment by CKolkey** [comment]
Its specific to each popup. So whichever popup has "--all", include the name between "Neogit" and "Popup"

```lua
ignored_settings = {
      "NeogitPushPopup--force-with-lease",
      "NeogitPushPopup--force",
      "NeogitPullPopup--rebase",
      "NeogitCommitPopup--allow-empty",
      "NeogitRevertPopup--no-edit",
    }
```

**Comment by mawkler** [comment]
@CKolkey Thank you, I got it to work with:

```lua
neogit.setup {
  ignored_settings = { 'NeogitCommitPopup--all' },
}
```

However, I got confused since I didn't notice that it was working because it restored my previous `--all` while I expected it to be disabled.

**Comment by CKolkey** [comment]
Glad to hear it :) You can always run `:NeogitResetState` to wipe any saved flags.

**Comment by mawkler** [comment]
@CKolkey Good to know!
