### ISSUE TITLE
Issues Related to "reverse" color schemes

### ISSUE THREAD

**Issue by chuck-flowers** [NeogitOrg/neogit#807]
### Description

This is related to another issue that I opened and was partially fixed (#793).

Instead of a hard error now, my highlighted changes are not legible because I believe the foreground and background highlighting are the same color.

### Neovim version

NVIM v0.9.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system and version

WSL2 Ubuntu 22.04 / Arch Linux Latest

### Steps to reproduce

1. Open neovim in a project with git changes
2. Open the neogit status page
3. Highlight

### Expected behavior

I expect the highlighted code blocks to be readable instead of solid colors (like in the below image)

### Actual behavior

![image](https://github.com/NeogitOrg/neogit/assets/9027535/58e1ea75-987e-403a-afee-bc952a5832ce)

### Minimal config

```Lua
-- gruvbox config (lazy)
return {
	'ellisonleao/gruvbox.nvim',
	config = function()
		local gruvbox = require 'gruvbox'

		gruvbox.setup({
			transparent_mode = false
		})

		vim.opt.termguicolors = true
		vim.o.background = 'dark'
		vim.cmd('colorscheme gruvbox')
	end
}

-- neogit config (lazy)
return {
	'NeogitOrg/neogit',
	dependencies = {
		'nvim-lua/plenary.nvim',
		'nvim-telescope/telescope.nvim',
		'sindrets/diffview.nvim'
	},
	opts = {},
	keys = {
		{
			'<leader>gs',
			function()
				require('neogit').open()
			end
		},
		{
			'<leader>gc',
			function()
				require("neogit").open({ "commit" })
			end
		},
		{
			'<leader>gl',
			function()
				require("neogit").open({ "log" })
			end
		}
	}
}
```

**Comment by zdcthomas** [comment]
I'm seeing the exact same behavior +1

**Comment by chuck-flowers** [comment]
@zdcthomas I might take a crack at writing a fix this weekend if I have time.

**Comment by CKolkey** [comment]
IMO the real fix is to open a PR for your colorschemes and get them to support all the highlight groups.. All the highlight logic I added is (mostly) a stop-gap. But, by all means, I'd happily accept improvements :)

**Comment by jamesbvaughan** [comment]
I'm seeing this with [`gruvbox.nvim`](https://github.com/ellisonleao/gruvbox.nvim). I can try making a PR there this week. I might wait until you're finished @chuck-flowers so that I can use yours as an example.

**Comment by chuck-flowers** [comment]
@jamesbvaughan My fork of gruvbox is on my profile. You can checkout the neogit branch to see what changes I made.

**Comment by zdcthomas** [comment]
What are the highlights being used that gruvbox doesn't support rn?

**Comment by chuck-flowers** [comment]
@zdcthomas I'm assuming he's talking about the `Neogit*` highlights. When I defined those in my fork, everything works properly.

**Comment by zdcthomas** [comment]
Then it feels like those shouldn't be expected to exist in all available color schemes, and instead by default they should be bound to another highlight that's more standard no?

**Comment by CKolkey** [comment]
Thats...exactly what's going on: https://github.com/NeogitOrg/neogit/blob/master/lua/neogit/lib/hl.lua#L56-L90 🤷🏼

**Comment by zdcthomas** [comment]
Oh sorry! I thought an update to gruvbox was being proposed! Idk where my heads at haha

**Comment by CKolkey** [comment]
All good :) No joke, this has been the hardest thing to get "right" since I did the major overhaul to this project.

**Comment by sealor** [comment]
I'm using `onedark` with a light background and also have issues with "invisible" text.

What do you think about the following approach?
Let's link all main highlight groups (especially with text) to the default vim highlight groups. Doing so will eliminate all problems with unreadable text. Furthermore the basic colors of the current scheme will be applied automatically.
For more advanced colors the color scheme should implement specific colors for every provided highlight group.

**Comment by CKolkey** [comment]
I'll go ahead and close this since @sealor did some work to improve the light colorscheme situation. Feel free to reopen if you're still experiencing issues :)

**Comment by elC0mpa** [comment]
> > IMO the real fix is to open a PR for your colorschemes and get them to support all the highlight groups.. All the highlight logic I added is (mostly) a stop-gap. But, by all means, I'd happily accept improvements :)
> 
> Do you have any recommended resource for understanding the semantics of "reverse"? If I understand its purpose better I'd be able to make an appropriate PR in the colorscheme or maybe add better fallback logic to neotest.
> 
> EDIT: It was actually a lot simpler than I thought. I've fixed the issue by defining the following as links:
> 
> * NeogitChangeAdded
> * NeogitChangeDeleted
> * NeogitDiffAdd
> * NeogitDiffDelete
> * NeogitDiffAddHighlight
> * NeogitDiffDeleteHighlight
> 
> I'll test these changes to the color scheme out for a few days and then submit them as a PR to gruvbox

Could you please explain me how to do this?
I am trying to get it right for gruvbox, assume that defining the highliht colors will fix it, but don´t know how to do it

**Comment by awalvie** [comment]
Running into the exact same problem with `nord` as well. Would appreciate if we could get some generalized docs about how to go about setting these highlight groups for our respective color schemes.

**Comment by CKolkey** [comment]
What would you like to see beyond https://github.com/NeogitOrg/neogit/blob/master/doc/neogit.txt#L199-L330 ?
