### ISSUE TITLE
[feat] Move cursor to "staging" section when opening neogit

### ISSUE THREAD

**Issue by ghostbuster91** [NeogitOrg/neogit#816]
Hi,

**Is your feature request related to a problem? Please describe.**
In the past, when I opened neogit my cursor was immediately put on the unstaged section.
However, recent changes added following section at the top of the neogit window:
![image](https://github.com/NeogitOrg/neogit/assets/5662622/40c7ab91-2498-4c33-b00a-88d15eb0c217)

and now the cursor is no longer at the unstaged section when I enter neogit window, but it is on the top of the new section. 

![image](https://github.com/NeogitOrg/neogit/assets/5662622/49e5fa3b-549a-4819-b4c4-369031154aef)

I think that the previous UX was better. 

**Describe the solution you'd like**
Opening neogit window should put the cursor on the top of unstaged section (or next section if there are no unstaged files). 

![image](https://github.com/NeogitOrg/neogit/assets/5662622/2d843e22-ea5f-4857-b2e9-9f4a7ef43ff8)

**Describe alternatives you've considered**
For now I am manually moving my cursor there as I don't know any motion that would come in handy in this particular case. 

Another way would be to use the motion described here https://github.com/NeogitOrg/neogit/issues/651 though I don't always want to expand these files.

**Comment by CKolkey** [comment]
Yea, that was a small regression, now that the headers are interactable. Thanks for the heads up :)
