### ISSUE TITLE
pushRemote is not respected from .git/config

### ISSUE THREAD

**Issue by lshoravi** [NeogitOrg/neogit#825]
### Description

Setting pushremote through UI or manually through `git push -u origin <my-branch>` correctly edits the pushRemote variable in my repo `.git/config`, looking like this:

```
[branch "my-branch"]
	pushRemote = origin
	remote = origin
	merge = refs/heads/my-branch


```
yet, the UI asks me to set pushremote with `p`:

![Screenshot 2023-09-15 at 11 14 17](https://github.com/NeogitOrg/neogit/assets/42211142/a43f563d-5650-444d-b447-ebdc09799596)

### Neovim version

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.1/share/nvim"

Run :checkhealth for more info

### Operating system and version

macOS 13.5.1

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. Open neogit in repository
3. Observe that the `p` action in the push popup doesn't respect the `.git/config` file setup

### Expected behavior

`p` uses existing pushremote

### Actual behavior

`p` asks to set pushremote

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by CKolkey** [comment]
Creating a branch, `test-pushremote`, followed by running:

```
$ git push -u origin test-pushremote
```

Yields a `.git/config` entry like so:
```
[branch "test-pushremote"]
	remote = origin
	merge = refs/heads/test-pushremote
```

That makes sense, since `-u` is short for `--set-upstream`, and `upstream` is different than `pushRemote`.

If I manually add `pushRemote = origin`, that value is picked up and used.

Maybe something else is going on here with your setup?

https://github.com/NeogitOrg/neogit/assets/7228095/1b75a9aa-42fe-46e7-b58c-84b186284bc3

**Comment by lshoravi** [comment]
This has resolved itself now, not sure what was interplaying.

**Comment by CKolkey** [comment]
Works for me :)
