### ISSUE TITLE
Use diffview as main status panel

### ISSUE THREAD

**Issue by searleser97** [NeogitOrg/neogit#846]
Could we use diffview as the main status window ?
It seems to be way better than current window, except that we cannot run neogit commands directly from there.

**Comment by CKolkey** [comment]
Eh, no, that's a different plugin. Maybe you can open a feature request over on https://github.com/sindrets/diffview.nvim to add some neogit like bindings? But there's nothing I can do about that from here.

**Comment by searleser97** [comment]
I'll start working on a side by side diffview for neogit then, I think this feature is worth it.

**Comment by CKolkey** [comment]
Cool :) I'm interested to see what you come up with.
