### ISSUE TITLE
Disable all default hotkey

### ISSUE THREAD

**Issue by mangelozzi** [NeogitOrg/neogit#847]
**Is your feature request related to a problem? Please describe.**
When I navigate the stash (I think referred to as the status) popup, I tend to use all the normal vim commands to navigate, e.g. `L` to jump down to the bottom of the screen, `l` to move right. However after an update, I often find there are new features, then when I try to navigate popups start flying up and I have nearly run some dangerous commands because the keys I press now have a new function associated with them.

**Describe the solution you'd like**
A setting to opt out of all the default keymappings, and only then one can specify which keymaps to use via the usual config:

```
mappings = {
   status = {
      ["q"] = "Close",
      ["<ESC>"] = "Close",
      ...
  }
}
```

**Describe alternatives you've considered**
I can disable all current hotkeys, but new ones keep popping up.

**Comment by CKolkey** [comment]
I feel you. This was a tough balance to strike. There are so many different popups, and using mnemonic keys started colliding with default vim keys. _That said_, you don't _need_ to move right or left in the status buffer, so I felt it wasn't a problem to reuse those keys.

I don't have any plans at this time to make an "opt out", but I'd consider a PR. I _do_ have some plans to make the key-mappings more configurable, and consistent, across all buffers/popups, though.

**Comment by mangelozzi** [comment]
> I feel you. This was a tough balance to strike. There are so many different popups, and using mnemonic keys started colliding with default vim keys. _That said_, you don't _need_ to move right or left in the status buffer, so I felt it wasn't a problem to reuse those keys.
> 
> I don't have any plans at this time to make an "opt out", but I'd consider a PR. I _do_ have some plans to make the key-mappings more configurable, and consistent, across all buffers/popups, though.

Thanks for the reply. Okay cool maybe I can figure out how to make the setting. Fair enough about `l`, but the reason I use it (probably uncommon), is sometimes I wish to put the cursor over a certain word, then I highlight the word, to check it is the same as another word, a way of checking variable names. I find the stage popup really great for navigating my code base too! Cheers mate!

**Comment by AdrienDML** [comment]
I would gladly appreciate configuring the key maps as i use t/k as my up/down movement key on my layout making neogit rather anoying to use xD.

**Comment by rmagatti** [comment]
Just coming here as a `jkl;` user to say I really like neogit but this `L` thing makes it really hard for me to use it well. I might try thinking of other ways to solve this with neogit and propose a couple of things here over the coming days

**Comment by CKolkey** [comment]
Hey! You can now set `use_default_keymaps` to `false`, and do all the keymaps yourself in the setup :)

https://github.com/NeogitOrg/neogit/blob/265e96128cf3bc3ba467c45f8fc112e91021e579/lua/neogit/config.lua#L829
