### ISSUE TITLE
Tab toggle diff toggles previous/above region

### ISSUE THREAD

**Issue by engeir** [NeogitOrg/neogit#857]
### Description

When toggling diffs with tab, the first diff in a file closes as expected, but moving to the next region instead opens the one above. Additionally, moving down several regions, tab will toggle the region two regions up. This happen only if regions above are closed.

https://github.com/NeogitOrg/neogit/assets/38856990/60a34e1d-3197-41ad-89c1-f45a029dcb83

### Neovim version

NVIM v0.9.2
Build type: Release
LuaJIT 2.1.1692716794

### Operating system and version

ubuntu 22.04

### Steps to reproduce

A file `file.txt` with changes several places.
1. `nvim -nu minimal.lua file.txt`.
2. Open neogit and attempt to toggle diff a region below an already closed region.

### Expected behavior

The region where the cursor is at is toggled.

### Actual behavior

Regions above where the cursor is at is toggled.

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "NeogitOrg/neogit",
        commit = "8727a3222a93d710a7000b750892cc25e2712937", -- Not working
        -- commit = "a48333352092237a968b9f7302f4265666a3ce03", -- Working
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by CKolkey** [comment]
@ten3roberts Do you mind taking a look? Seems like an issue with the `get_item_hunks()` function, or something similar, that you redid recently.
