### ISSUE TITLE
Feature request - make pop-ups actual pop-ups/floating windows

### ISSUE THREAD

**Issue by weilbith** [NeogitOrg/neogit#87]
Hey guys,
I'm just trying this plugin so see if it could be modern Fugitive replacement. One thing I realized is that many windows are called "pop-up"  (e.g. commit, stash, ...) but they aren't really. At least not for me using NeoVim. Is the naming "wrong" or is it a hint that it is only implemented for Vim (I think to remember that there this feature is called pop-up while floating windows in NeoVim). If none of these applies it would be cool to actually make these windows pop-ups/floating.

**Comment by TimUntersberger** [comment]
The name popup comes from magit before they renamed it to transient.

> If none of these applies it would be cool to actually make these windows pop-ups/floating.

Should be possible 👍

**Comment by weilbith** [comment]
Quick question: is this plugin meant to be NeoVim only or does it require to always support both Vims?

**Comment by RianFuro** [comment]
@weilbith Neogit is Neovim only. We're making heavy use of Neovim's lua integration, the exposed event loop of libuv and Neovim's api for creating signs and floating windows.

Neogit's core idea **could** potentially work in standard vim, but there are no plans for that and would essentially entail a complete rewrite of the plugin, seeing as we'd need to port the code over to viml.

**Comment by weilbith** [comment]
Okay, perfect. Then this whole feature is way simpler to implement. :+1:

**Comment by RianFuro** [comment]
Yep :) This is also kind of related to #63, so we might want to reconcile these 2 and find some common ground for a solution.

**Comment by TimUntersberger** [comment]
@RianFuro based on my current understanding these two issues have different problems. This one is just about modifying one buffer to be a floating window and the other one is about being able to split a floating window (which currently is not possible I think?)

**Comment by RianFuro** [comment]
@TimUntersberger Yeah, the being not possible part is what makes those issues semi-related again. 
One way to work around the problem would be to "manually split" the floating status buffer, by reducing it's height and opening a second floating window below; which is where the issues would overlap.

**Comment by thepenguinthatwants** [comment]
Stash is interesting, eventho it works I need to reopen neovim to see the changes.
