### ISSUE TITLE
Crash at plenary async module on all actions that show a select UI

### ISSUE THREAD

**Issue by fnune** [NeogitOrg/neogit#872]
### Description

```
Error executing vim.schedule lua callback: ...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine failed with this message: ....local/share/nvim/lazy/neogit/lua/neogit/lib/git/cli.lua:797: i
nvalid value (table) at index 9 in table for 'concat'
stack traceback:
        [C]: in function 'error'
        ...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:18: in function 'callback_or_next'
        ...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:45: in function 'on_select'
        .../.local/share/nvim/lazy/neogit/lua/neogit/lib/finder.lua:232: in function <.../.local/share/nvim/lazy/neogit/lua/neogit/lib/finder.lua:231>
```

This happens whenever I need to select something from a select UI:

![image](https://github.com/NeogitOrg/neogit/assets/16181067/b9d01a80-86dd-4264-8933-6a5dec1a4ec4)

Right after selecting, I get the trace above.

### Neovim version

```
 ~/Development/memfault => nvim --version
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/i9f72lw9lymhc10ib5x2knp2g0d09arz-neovim-unwrapped-0.9.1/share/nvim
"

Run :checkhealth for more info
```

### Operating system and version

 ~/Development/memfault => uname -a Linux nixos 6.1.55 #1-NixOS SMP PREEMPT_DYNAMIC Sat Sep 23 09:11:13 UTC 2023 x86_64 GNU/Linux

### Steps to reproduce

- Open any workflow that requires selecting
- It breaks

### Actual behavior

See the summary

### Minimal config

```Lua
-
```

**Comment by fnune** [comment]
Enabled Telescope integration to work around this. But the default selector UI is broken.

```lua
    integrations = {
      telescope = true,
    },
```

**Comment by coffebar** [comment]
For me, telescope integration is not working (crashing). And if I disable it, select something via another select UI, it crashes right after selection.

**Comment by CKolkey** [comment]
> For me, telescope integration is not working (crashing).
> 
> ```
> E5108: Error executing lua ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine failed with this message: ...cker/start/telescope.nvim/lua/telescope/
> actions/init.lua:74: Key does not exist for 'telescope.actions': nop
> ```

Thats... odd. If you run `:= require("telescope.actions").nop` in neovim, does anything print?

**Comment by coffebar** [comment]
It prints error.

```lua
-- debug
local actions = require("telescope.actions")
local keys = vim.tbl_keys(actions)
print(#keys) -- 75
print(vim.tbl_contains(keys, "nop")) -- false

```

My telescope setup options:

```lua
telescope.setup({
  pickers = {
    find_files = {
      find_command = {
        "rg",
        "--files",
        "--hidden",
      },
    },
  },
})
```

**Comment by coffebar** [comment]
It's because I have telescope tagged to 0.1.0 version, that doesn't have this

**Comment by CKolkey** [comment]
Try updating. I have 83 keys, including `nop` and `git_reset_hard`.

**Comment by coffebar** [comment]
> Try updating. I have 83 keys, including `nop` and `git_reset_hard`.

Updated, seems the second error message is gone. But `nop` error is present for me. 
Maybe it's possible to replace `nop` with an empty function

**Comment by coffebar** [comment]
I add this to my config:
```lua
local actions = require("telescope.actions")
actions.nop = function(_) end
```
And the error changed to:
```
E5108: Error executing lua ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine failed with this message: ...k/packer/start/telescope.nvim/lua/telesc
ope/mappings.lua:285: bad argument #1 to 'lower' (string expected, got table)
stack traceback:
        [C]: in function 'error'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:18: in function 'callback_or_next'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:45: in function 'step'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:48: in function 'execute'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:118: in function 'callback'
        ...cal/share/nvim/lazy/neogit/lua/neogit/lib/popup/init.lua:588: in function 'cb'
        .../.local/share/nvim/lazy/neogit/lua/neogit/lib/buffer.lua:449: in function <.../.local/share/nvim/lazy/neogit/lua/neogit/lib/buffer.lua:448>
        ...are/nvim/lazy/neogit/lua/neogit/lib/mappings_manager.lua:14: in function 'invoke'
        [string ":lua"]:1: in main chunk
```

**Comment by CKolkey** [comment]
@coffebar can you open a new issue with a minimal config that I can use to reproduce this?

**Comment by fnune** [comment]
Tested your fix @CKolkey, it works!
