### ISSUE TITLE
Error when opening Neogit on new repo

### ISSUE THREAD

**Issue by austinbutler** [NeogitOrg/neogit#879]
### Description

Error pops up on a new repo when running `:Neogit`:

```
git --no-pager -c color.ui=always --no-optional-locks rev-parse --short (initial):

    fatal: Needed a single revision


Open the console for details
Press ENTER or type command to continue
```

Pressing `ENTER` and continuing, Neogit seems to load fine. A similar tool like `gitui` doesn't have any issue working with the same new repo.

### Neovim version

```
NVIM v0.10.0-dev-6823fdb
Build type: Release
LuaJIT 2.1.1693350652
```

### Operating system and version

NixOS 23.11 

### Steps to reproduce

1. `mkdir test`
2. `cd test`
3. `git init`
4. `nvim`
5. `:Neogit`

### Expected behavior

No error.

### Actual behavior

Error.

**Comment by k0va1** [comment]
I have the same issue
