### ISSUE TITLE
Correctly focus the last tab when closing Neogit* buffers

### ISSUE THREAD

**Issue by asmodeus812** [NeogitOrg/neogit#909]
**Is your feature request related to a problem? Please describe.**
Would be great if the kind "tab" worked correctly with closing buffers, or at least provide a way to customize the generic Buffer mappings. The feature request is that when closing a tabbed neogit buffer and there is no alternate buffer on the  current tab, of any kind the last focused tab should be opened i.e g tab functionality. The current behaviour would just focus the next tab instead.

**Describe the solution you'd like**
Either a user configuration, or implemented in neogit

**Describe alternatives you've considered**
Overriding the Buffer:close but the buffer file has this at the top `package.loaded["neogit.buffer"] = nil` which would prevent us from overriding in a robust way.

**Additional context**
None

**Comment by gegoune** [comment]
I use `<Cmd>tabnext # <Bar> tabclose #<CR>` to close Diffview's tab, something similar can be done for Neogit too.
