### ISSUE TITLE
Can not set mappings between popup and status after recent breaking change

### ISSUE THREAD

**Issue by asmodeus812** [NeogitOrg/neogit#913]
### Description

Neogit reports that there are duplicate mappings, since instead of overriding them it tries to merge with the defaults which is bad imo. So for example i would like to have both x and X keys open two different popups, but since x is already taken by default in the status mappings map, i get this error.  Please allow us to completely override the default mappings, we might want to even disable certain ones, instead of merging them with the defaults.

E5108: Error executing lua: .../packages/start/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine failed with this message: vim/shared.lua:0: key found in more than one map: x
stack traceback:
        [C]: in function 'error'
        .../packages/start/plenary.nvim/lua/plenary/async/async.lua:18: in function 'callback_or_next'
        .../packages/start/plenary.nvim/lua/plenary/async/async.lua:45: in function 'step'
        .../packages/start/plenary.nvim/lua/plenary/async/async.lua:48: in function 'execute'
        .../packages/start/plenary.nvim/lua/plenary/async/async.lua:108: in function 'run'
        .../share/nvim/site/pack/packages/opt/neogit/lua/neogit.lua:103: in function 'open'
        /home/asmodeus/.config/nvim/lua/plugin/neogit.lua:9: in function 'open_vcs_element'
        /home/asmodeus/.config/nvim/lua/user/actions.lua:1049: in function 'open_vercontrol_view'
        /home/asmodeus/.config/nvim/lua/user/command.lua:1959: in function </home/asmodeus/.config/nvim/lua/user/command.
lua:1958>

### Neovim version

0.9.4

### Operating system and version

ubuntu

### Steps to reproduce

```
        mappings = {
            finder = {
                ["<cr>"] = "Select",
                ["<esc>"] = "Close",
                ["<c-j>"] = "Next",
                ["<c-p>"] = "Previous",
                ["<tab>"] = "MultiselectToggleNext",
                ["<s-tab>"] = "MultiselectTogglePrevious",
            },
            popup = {
                ["?"] = "HelpPopup",
                ["i"] = "IgnorePopup",
                ["b"] = "BranchPopup",
                ["p"] = "PushPopup",
                ["f"] = "FetchPopup",
                ["r"] = "RebasePopup",
                ["l"] = "LogPopup",
                ["z"] = "StashPopup",
                ["D"] = "DiffPopup",
                ["P"] = "PullPopup",
                ["c"] = "CommitPopup",
                ["C"] = "CherryPickPopup",
                ["x"] = "RevertPopup",
                ["X"] = "ResetPopup",
                ["m"] = "MergePopup",
                ["M"] = "RemotePopup",
            },
            status = {
                ["<c-r>"] = "RefreshBuffer",
                ["<c-v>"] = "VSplitOpen",
                ["<c-x>"] = "SplitOpen",
                ["<c-t>"] = "TabOpen",
                ["<esc>"] = close_git_view,
                ["<enter>"] = "GoToFile",
                ["<tab>"] = "Toggle",
                ["n"] = "InitRepo",
                ["s"] = "Stage",
                ["S"] = "StageUnstaged",
                ["u"] = "Unstage",
                ["U"] = "UnstageStaged",
                ["d"] = "DiffAtFile",
                ["R"] = "Discard",
                ["I"] = "InitRepo",
                ["L"] = "CommandHistory",
                ["}"] = "GoToNextHunkHeader",
                ["{"] = "GoToPreviousHunkHeader",
            },
        },
```

### Expected behavior

No errors

### Actual behavior

Error is observed opening the git status.

### Minimal config

```Lua
See above.
```

**Comment by CKolkey** [comment]
Cool, I knew I'd see stuff like this. The end goal is to make things _more_ flexible for everyone, but the path to getting there is... bumpy.

Anyways, thanks for the reproduction config. I'll try and sort this out asap.

**Comment by asmodeus812** [comment]
Not working on master/latest changes, tried that before posting this issue - @star-szr

**Comment by CKolkey** [comment]
> Maybe a config switch to disable all built-in keybindings would help?
> 
> [oil.nvim example](https://github.com/stevearc/oil.nvim#options):
> 
> ```lua
> use_default_keymaps = true,
> ```

I... I love the simplicity. Done. https://github.com/NeogitOrg/neogit/pull/926

> Though I do think using `false` should work for this use case too. I haven’t had a chance to dig into the code but I’m imagining we could remove all mappings set to `false` from the defaults before merging.

Easy, too. Great ideas :)

**Comment by fdelacruz** [comment]
Hi, I'm sorry..
Did that work for anybody??

**Comment by CKolkey** [comment]
Really hope so. Is stuff broken for you?

**Comment by fdelacruz** [comment]
Yeah, suddenly i'm getting the following:
<img width="1435" alt="Screen Shot 2023-11-14 at 11 54 54 AM" src="https://github.com/NeogitOrg/neogit/assets/148098/330c64bb-9a46-4f06-89c1-0d82ce782e20">
But, now that i look at it closer maybe it is not related to this issue here. 
Something about `Vim(sign):E155: Unknown sign: NeogitOpen:section`

**Comment by CKolkey** [comment]
Looks unrelated. I'll close this, and do you wanna open a new issue with your config?

**Comment by fdelacruz** [comment]
Actually, im still getting the OP error.
My use_default_keymaps was set to false, but when I set it to true the error is there and renders Neogit unusable.
