### ISSUE TITLE
Log -L option errors out

### ISSUE THREAD

**Issue by GCBallesteros** [NeogitOrg/neogit#919]
### Description

When the log functionality is combined with the -L flag (Trace line evolution) an error message is displayed and nothing else happens.

### Neovim version

NVIM v0.9.2
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

macOS Ventura 13.0

### Steps to reproduce

All defaults config of Neogit
```lua
return {
  "NeogitOrg/neogit",
  dependencies = {
    "nvim-lua/plenary.nvim", -- required
    "nvim-telescope/telescope.nvim", -- optional
    "sindrets/diffview.nvim", -- optional
  },
  config=true,
}
```

This happens on commit `5a2d468`

1. Git clone your favorite repo: `git clone https://github.com/NeogitOrg/neogit`
2. `cd neogit`
3. `:Neogit`
4.  Open log popup (`l`)
5. Configure `-L` option by typing `-L`
6. Enter options e.g. `1,10:README.md` to get the commits that affected lines 1 to 10 of `README.md`
7. Press `l` to run the log command

### Expected behavior

A new tab should open with a list of the commits that affect the specified range of lines and file. For example the following works just fine on the git CLI:

```
$ git log -s --pretty=oneline -L 1,5:lua/neogit/popups/log/init.lua
```
And will display all the commits that touched lines 1 to 5.

### Actual behavior

A new empty tab opens and the following error message is displayed:

```
...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine failed with this message: ...cal/share/nvim/lazy/neogit/lua/neogit/buffers/common.lua:115: attempt to index field 'ref_name' (a nil value)
stack traceback:
	[C]: in function 'error'
	...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:18: in function 'callback_or_next'
	...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:45: in function 'cb'
	...lem/.local/share/nvim/lazy/neogit/lua/neogit/process.lua:359: in function <...lem/.local/share/nvim/lazy/neogit/lua/neogit/process.lua:321>
```

### Minimal config

```Lua
The minimal config that shows up on Issue creation is enough to reproduce
```

**Comment by Aphosis** [comment]
It looks like the log action can't parse log output with patches, or at least, it works if you also specify `--no-patch` to the command line arguments.

It doesn't look like the option is exposed in the popup though, so I tested it with the following command:

```
:lua require("neogit").action("log", "log_current", {"-L:func:main/main.py", "--no-patch"})()
```
