### ISSUE TITLE
feat: Jump to section of commit when pressing `<cr>` on file name

### ISSUE THREAD

**Issue by GCBallesteros** [NeogitOrg/neogit#920]
**Is your feature request related to a problem? Please describe.**
Often one is only interested on the changes that impacted a specific file however the commit view always shows all the files that were affected. Adding functionality to navigate the commit view efficienty such as jumping to the diffs of a specific file or `[` and `]` style keybinding would be good.

**Describe the solution you'd like**
After running a log command a new buffer opens with the relevant commits. One can then press `<cr>` on them to open the diffs. The start of a typical diff view of the commit would look like:

```
Commit b2f7d0e9bc541e6626ee2c06f5e8a525e3ae6614

Author:     Cameron <Alleyria@gmail.com>
AuthorDate: Sat Oct 7 16:22:39 2023 +0200
Committer:  Cameron <Alleyria@gmail.com>
CommitDate: Tue Oct 31 21:58:19 2023 +0100

Use popup mappings defined by user for all buffers

3 files changed, 47 insertions(+), 47 deletions(-)
 lua/neogit/buffers/commit_view/init.lua | 12 +++++----- << pressing <cr> while on this lines jumps 
lua/neogit/buffers/log_view/init.lua    | 40 +++++++++++++++----------------
lua/neogit/buffers/reflog_view/init.lua | 42 ++++++++++++++++-----------------

... the diffs
```

It would be nice to be able to press `<cr>` again while on top of one of the lines shown on the start of the commit to jump to the relevant part of commit.

**Describe alternatives you've considered**
Searching for the filename using standard vim commands such as `/`. One way is to go to the file name then:
1. yiW to yank the path
2. Press `/` to enter search mode
3. Control-R to select a register
4. If you just yanked the 0 register should contain your path

**Comment by GCBallesteros** [comment]
Will this be an interesting feature to add? I have dived into the code and I think I have figured out how to go about it.

**Comment by CKolkey** [comment]
Absolutely! Open a PR, we can take a look
