### ISSUE TITLE
Show ongoing merge or rebase in overview

### ISSUE THREAD

**Issue by agraven** [NeogitOrg/neogit#951]
**Is your feature request related to a problem? Please describe.**
An active merge with conflicts or rebase that's stopped can significantly change how the unstaged/staged status of files should be interpreted, and changes what the desirable next course of action to perform is.

Displaying if there's an active rebase or merge in the overview would make this immediately clear, and would remove a lot of ambiguity of the current state of the repo. I am often uncertain about whether a merge or a rebase actually succeeded when I currently look at the overview.

**Describe the solution you'd like**
An extra field next to `Head:` and `Merge:` at the top that appears if there's an ongoing merge or rebase.

**Describe alternatives you've considered**
Displaying the information elsewhere in the UI

**Additional context**
This information is present in a regular `git status` invocation. fugitive also displays ongoing rebases, though not ongoing merges.

**Comment by CKolkey** [comment]
Oh, there should be a section in the status buffer that shows up during a rebase:
<img width="478" alt="Screenshot 2023-11-17 at 13 02 23" src="https://github.com/NeogitOrg/neogit/assets/7228095/3e154c7e-1751-4509-a6e3-8a6f0efa32b7">


If the rebase is over without conflict, it's probably too fast to appear, but you'll see it with a conflict.

**Comment by agraven** [comment]
I don't think that appeared for me. I'll see if I can reproduce it. Either way, displaying an ongoing merge would still be a nice addition.
