### ISSUE TITLE
Add Tag support

### ISSUE THREAD

**Issue by v0d1ch** [NeogitOrg/neogit#971]
First of all thank you for your hard work so far!
This package is the last thing I needed to reach _holy grail_ of dev setup: vim + magit! <3 

I was wondering if we can have tag support, similar to the magit one?

**Comment by CKolkey** [comment]
Thanks for the kind words! There is a tag popup mostly done - what tagging feature are you missing specifically?

**Comment by v0d1ch** [comment]
I would need just easy tag listing and from that list easy tag checkout or reset to certain tag.

**Comment by mortezadadgar** [comment]
@CKolkey does that solves the in which switching branches doesn't list tags?
like this:
![image](https://github.com/NeogitOrg/neogit/assets/27911493/4b322dd8-53e7-4608-9913-2ec24a3aca14)
![image](https://github.com/NeogitOrg/neogit/assets/27911493/8f4b1d99-d2c4-4b15-832b-2b43f0529138)
doesn't list any tags alongside branches like magit

**Comment by CKolkey** [comment]
@mortezadadgar In #1025 you can now check out tags from `b b` :) Thanks for pointing that out.

**Comment by mortezadadgar** [comment]
@CKolkey that was quick lmao, what about showing tags in git log?

**Comment by CKolkey** [comment]
Easy addition. Didn't cross my mind to just chuck them on the list. I _think_ I'm going to need to put some more work into using the full name for refs, like `heads/...` or `tags/...` or `remotes/...` when passing it to the CLI so we don't have any name collisions... I'll do that soon.

Not sure what you mean about tags in the log.. We also show tags in the log. 
![Screenshot 2023-12-14 at 09 34 17](https://github.com/NeogitOrg/neogit/assets/7228095/1ac4de78-0f3d-4212-8240-dcb8c68d31ea)

**Comment by mortezadadgar** [comment]
I'm speaking of showing these also in NeogitStatus window just like magit
![image](https://github.com/NeogitOrg/neogit/assets/27911493/9c78fe73-51df-47d0-90fd-875779e48342)

**Comment by CKolkey** [comment]
Ohh, in the recent-commits. Sorry, missed that detail. Yeah, we don't show decorations there (yet). Probably won't for a while, unfortunately. The status buffer uses it's own (older) rendering method, which relies on syntax highlighting instead of extmarks. And, considering how much it does, it's not a small task to rewrite it using the same pipeline as everything else.

Someday :)
