### ISSUE TITLE
Opening any Neogit popup halves the height of Neovim within my Terminal

### ISSUE THREAD

**Issue by snoblenet** [NeogitOrg/neogit#975]
### Description

When I open Neogit, initially there is no buggy behaviour. But as soon as I open any Neogit popup at all, Neovim halves the height that it uses in my terminal.

Before pressing `p`: 

![image](https://github.com/NeogitOrg/neogit/assets/62277/6e7fd15f-eefe-40e6-aa34-1082d1e26364)

After pressing `p`:

![image](https://github.com/NeogitOrg/neogit/assets/62277/be97d11d-af79-47ce-bd9d-34b9b31e312f)

This behaviour does not occur with any other plugin.

The only way to fix it is to quit and restart Neovim.

My terminal is Kitty 0.29.1.

My config:

```
return {
  'NeogitOrg/neogit',
  dependencies = {
    'nvim-lua/plenary.nvim', -- required
    'nvim-telescope/telescope.nvim', -- optional
    'sindrets/diffview.nvim', -- optional
    'ibhagwan/fzf-lua', -- optional
  },
  config = { disable_context_highlighting = true, kind = 'replace' },
}

```

Relevant `:CheckHealth` output:

```
==============================================================================
diffview: require("diffview.health").check()


Checking VCS tools ~
- WARNING Configured `hg_cmd` is not executable: 'hg'

==============================================================================
lazy: require("lazy.health").check()

lazy.nvim ~
- ERROR Issues were reported when loading your specs:
- WARNING {neogit}: setting a table to `Plugin.config` is deprecated. Please use `Plugin.opts` instead

==============================================================================
```

### Neovim version

NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1700008891

### Operating system and version

14.1.1

### Steps to reproduce

Not sure anyone else will be able to reproduce this, but I can reproduce it by pressing `p`, as per the two screenshots shown above.

### Expected behavior

Neovim continues to occupy the full terminal window.

### Actual behavior

Neovim starts to to occupy half the height of terminal window.

### Minimal config

```Lua
I doubt anyone else will be able to reproduce this
```

**Comment by snoblenet** [comment]
For now I am working around the issue with the following config.

```
return {
  'NeogitOrg/neogit',
  dependencies = {
    'nvim-lua/plenary.nvim', -- required
    'nvim-telescope/telescope.nvim', -- optional
    'sindrets/diffview.nvim', -- optional
    'ibhagwan/fzf-lua', -- optional
  },
  config = {
    disable_context_highlighting = true,
    kind = 'replace',
    status = {
      kind = 'vsplit',
    },
    commit_editor = {
      kind = 'vsplit',
    },
    commit_select_view = {
      kind = 'vsplit',
    },
    commit_view = {
      kind = 'vsplit',
    },
    log_view = {
      kind = 'vsplit',
    },
    rebase_editor = {
      kind = 'vsplit',
    },
    reflog_view = {
      kind = 'vsplit',
    },
    merge_editor = {
      kind = 'vsplit',
    },
    tag_editor = {
      kind = 'vsplit',
    },
    preview_buffer = {
      kind = 'vsplit',
    },
    popup = {
      kind = 'vsplit',
    },
  },
}

```

(I'm assuming `Neogit` like most Lua plugins does a deep merge between this settings and the default settings.)

**Comment by PixsaOJ** [comment]
also use `opts` instead of `config`
