### ISSUE TITLE
Show refs in NeogitCommitSelectView

### ISSUE THREAD

**Issue by gegoune** [NeogitOrg/neogit#979]
**Is your feature request related to a problem? Please describe.**
I believe having refs in commit select view would help users quickly pick up right commit.

**Describe the solution you'd like**
I would like to see refs when selecting commit to fixup against (commit popup -> fixup).

**Describe alternatives you've considered**
None really, I have been using it for a while and it works fine, it's just a small improvement I believe.

**Additional context**
I like to think about `NeogitCommitSelectView` as git log, which for me always shows refs and I am just very used to it.

Thanks for maintaining Neogit, the live you two have put into this plugin in recent months is astonishing!

**Comment by CKolkey** [comment]
Easy-peasy.

**Comment by gegoune** [comment]
Unbelievable. You are awesome. Thanks a bunch!
