### ISSUE TITLE
Allow interactive rebase to root commit

### ISSUE THREAD

**Issue by Silex** [NeogitOrg/neogit#987]
When you `ri` to the very first commit, magit detects this and automatically adds `--root` to the interactive rebase.

**Comment by CKolkey** [comment]
I think I tried to copy the logic, but perhaps didn't get it right:
https://github.com/NeogitOrg/neogit/blob/29561839c7167010611a6e9315dba7aa9f358024/lua/neogit/popups/rebase/actions.lua#L63-L82

**Comment by CKolkey** [comment]
I think i sorted this out. Should have an update out soon
